### PR TITLE
Bugfix/wrong assertion in class zone eligible checker

### LINKED ISSUE #18397: Wrong assertion in `ZoneEligibilityChecker`
### Sylius version(s) affected

1.14.11

### Description

You added this class `Sylius\Component\Core\Shipping\Checker\Eligibility\ZoneEligibilityChecker` in 1.14.11. It breaks our application because we send in a `ShippingSubjectInterface` and not a `ShipmentInterface` which you assert in the first line.

### How to reproduce

Input a `ShippingSubjectInterface` that _not_ a `ShipmentInterface`

### Possible Solution

Using `ifs` for checking and returning instead

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by michalkaczmarek-bitbag**
| Q               | A
|-----------------|-----
| Branch?         | 1.14
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/18397
| License         | MIT

### CODE REVIEW

File: src/Sylius/Component/Core/Shipping/Checker/Eligibility/ZoneEligibilityChecker.php [hunk 1]
```diff
@@ -30,14 +29,12 @@ public function __construct(private ZoneMatcherInterface $zoneMatcher)
...
-        Assert::isInstanceOf($shippingMethod, CoreShippingMethodInterface::class);
-
-        $shippingAddress = $shippingSubject->getOrder()?->getShippingAddress();
-        if (null === $shippingAddress) {
+        if (!$shippingAddress = $shippingSubject->getOrder()?->getShippingAddress()) {
             return true;
         }
 
+        Assert::isInstanceOf($shippingMethod, CoreShippingMethodInterface::class);
+
```
Comment (Rafikooo) [inline src/Sylius/Component/Core/Shipping/Checker/Eligibility/ZoneEligibilityChecker.php]: Asserts should be placed at the top of the method, before any logic.

File: src/Sylius/Component/Core/Shipping/Checker/Eligibility/ZoneEligibilityChecker.php [hunk 2]
```diff
@@ -30,14 +29,12 @@ public function __construct(private ZoneMatcherInterface $zoneMatcher)
 
     public function isEligible(ShippingSubjectInterface $shippingSubject, ShippingMethodInterface $shippingMethod): bool
     {
-        Assert::isInstanceOf($shippingSubject, ShipmentInterface::class);
-        Assert::isInstanceOf($shippingMethod, CoreShippingMethodInterface::class);
-
-        $shippingAddress = $shippingSubject->getOrder()?->getShippingAddress();
-        if (null === $shippingAddress) {
+        if (!$shippingAddress = $shippingSubject->getOrder()?->getShippingAddress()) {
```
Comment (Rafikooo) [inline src/Sylius/Component/Core/Shipping/Checker/Eligibility/ZoneEligibilityChecker.php]:
```suggestion
        if (!$shippingSubject instanceof ShipmentInterface::class) {
            return true;
        }

        $shippingAddress = $shippingSubject->getOrder()?->getShippingAddress();

        if ($shippingAddress === null) {
            return true;
        }
```
This way we safely skip non-shipment subjects early without throwing exceptions, keeping the logic simple and BC-friendly.

File: src/Sylius/Component/Core/Shipping/Checker/Eligibility/ZoneEligibilityChecker.php [hunk 3]
```diff
@@ -30,11 +30,14 @@ public function __construct(private ZoneMatcherInterface $zoneMatcher)
 
     public function isEligible(ShippingSubjectInterface $shippingSubject, ShippingMethodInterface $shippingMethod): bool
     {
-        Assert::isInstanceOf($shippingSubject, ShipmentInterface::class);
         Assert::isInstanceOf($shippingMethod, CoreShippingMethodInterface::class);
 
+        if (!$shippingSubject instanceof ShipmentInterface) {
+            return true;
+        }
```
Comment (Rafikooo) [inline src/Sylius/Component/Core/Shipping/Checker/Eligibility/ZoneEligibilityChecker.php:37]: Cover this path with a test.

**Review by Rafikooo — DISMISSED** [review]

**Review by Rafikooo — APPROVED** [review]
