### PR TITLE
[FIX] Default variant

### LINKED ISSUE #15547: DefaultProductVariantResolver is not getting the first positioned variant
**Sylius version affected**: 1.12

**Description & Steps to reproduce**  
For example I want to list products on the frontend.
I'm expecting to see the first variant of each product.
If I add a new variant to an existing product and I set its position to `0` to set it as the default product variant.
I should be able to see it, I see the first created variant instead.

**Possible Solution**
`\Sylius\Component\Product\Resolver\DefaultProductVariantResolver` must orderBy `position` (`ASC`) to retrieve the right variant.

Related comment : https://github.com/Sylius/Sylius/pull/15273/files#r1399230190

### PR DESCRIPTION
**Pull request by Prometee**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12                  |
| Bug fix?        | yes                                                       |
| New feature?    | yes                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | yes |
| Related tickets | fixes #15547                      |
| License         | MIT                                                          |

This PR fix an issue introduced by #15273.
Variants are by default ordered by position via a specific Doctrine resource configuration :
https://github.com/Sylius/Sylius/blob/1.12/src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/Product.orm.xml#L37-L38
This behaviour has to be cloned to retrieve the right variant.

### CODE REVIEW

File: src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductVariantRepository.php [hunk 1]
```diff
@@ -177,4 +177,18 @@ public function getCodesOfAllVariants(): array
             ->getArrayResult()
         ;
     }
+
+    public function findDefaultVariant(ProductInterface $product, bool $enabled = true): ?ProductVariantInterface
+    {
+        return $this->createQueryBuilder('o')
+            ->innerJoin('o.translations', 'translation')
```
Comment (loevgaard) [inline src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductVariantRepository.php]: Why this join?

File: src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php [hunk 2]
```diff
@@ -66,4 +66,6 @@ public function findByPhrase(string $phrase, string $locale, ?int $limit = null)
      * @return array|string[]
      */
     public function getCodesOfAllVariants(): array;
+
+    public function findDefaultVariant(ProductInterface $product, bool $enabled = true): ?ProductVariantInterface;
```
Comment (loevgaard) [inline src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php]: Sylius' policy on this is probably that it's okay, but this is a BC break

File: UPGRADE-1.12.md [hunk 3]
```diff
@@ -2,6 +2,13 @@
 
 1. The `Sylius\Component\User\Model\UserInterface` extends the `Symfony\Component\PasswordHasher\Hasher\PasswordHasherAwareInterface`
    interface to fix the compatibility with Symfony 6.
+2. The constructor of `Sylius\Component\Product\ResolverDefaultProductVariantResolver` has been modified, a new argument has been added :
```
Comment (loevgaard) [inline UPGRADE-1.12.md]:
```suggestion
2. The constructor of `Sylius\Component\Product\DefaultProductVariantResolver.php` has been modified, a new argument has been added :
```

File: src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php (hunk 2 above)
Comment (loevgaard) [reply src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php]: If you don't want to break BC then you can add the position sorting in the `findOneBy` call that was there before

File: UPGRADE-1.12.md (hunk 3 above)
Comment (diimpp) [reply UPGRADE-1.12.md]:
```suggestion
2. The constructor of `Sylius\Component\Product\Resolver\DefaultProductVariantResolver` has been modified, a new argument has been added :
```

Looking for other UPGRADE entries, `.php` part is usually not used.

File: src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php (hunk 2 above)
Comment (diimpp) [reply src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php]: Can you please elaborate on the nature of BC, I'm not following.

File: src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductVariantRepository.php (hunk 1 above)
Comment (Prometee) [reply src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductVariantRepository.php]: Not required and re-thinking of it, it will create issues with Shop with a very large amount of enabled locales. So I think it should be removed.

**Comment by vvasiloi** [comment]
So it was a regression. We need a test to prevent that from happening again.

File: UPGRADE-1.12.md (hunk 3 above)
Comment (Prometee) [reply UPGRADE-1.12.md]: I miss the backslash between `Resolver` and `DefaultProductVariantResolver ` ;)

File: src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php (hunk 2 above)
Comment (vvasiloi) [reply src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php]: I think it's better to have custom methods instead of using methods like `findOneBy` because it makes refactoring and customizations easier.
But perhaps a major release is better for this purpose.

Comment (Prometee) [reply src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php]: You are right, reverting it.

File: src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductVariantRepository.php [hunk 4]
```diff
@@ -177,4 +177,18 @@ public function getCodesOfAllVariants(): array
...
+            ->andWhere('o.product = :product')
+            ->andWhere('o.enabled = :enabled')
+            ->setParameter('product', $product)
+            ->setParameter('enabled', $enabled)
+            ->addOrderBy('o.position', 'ASC')
+            ->getQuery()
```
Comment (diimpp) [inline src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductVariantRepository.php]: Won't `getQuery()->getResult()` return array?

File: src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php (hunk 2 above)
Comment (vvasiloi) [reply src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php]: The `enabled` parameter bothers me a bit. I don't see why would it ever be `false`.
It should rather be something like `onlyEnabled` and if it's `true` then conditionally add the `where o.enabled = true` clause.
Otherwise, there's no way to get the default variant regardless of its status.

File: src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductVariantRepository.php (hunk 4 above)
Comment (Prometee) [reply src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductVariantRepository.php]: oh yes you are right, I was about to test the PR and then read the PR suggestion. But anyway I reverted this reprository method to the `findOneBy` instead to avoid BC break.

File: src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php (hunk 2 above)
Comment (vvasiloi) [reply src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php]: Oh, never mind, you're reverting it.

Comment (Prometee) [reply src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php]: @vvasiloi To answer your question, I named the repository without "Enabled" word so it can be used in a shop or admin context without overriding this method. It was just to prepare some hypothetic futur feature like we discussed 😉

Comment (diimpp) [reply src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php]: Custom `findDefaultVariant` method was much better, I still don't understand about BC.

It was introduced in previous minor version -- it cannot be considered BC unless you will remove repository class entirely.
If somebody extended this class in previous version, then it will be still working as is.

Voting to revert to `findDefaultVariant`

**Comment by Prometee** [comment]
> So it was a regression. We need a test to prevent that from happening again.

@vvasiloi Scenario added 😉

File: features/product/viewing_products/viewing_product_price_on_products_list.feature [hunk 5]
```diff
@@ -33,3 +33,13 @@ Feature: Viewing a product price on products list
         When I browse products from taxon "T-Shirts"
         Then I should see the product "T-Shirt watermelon" with price "$19.00"
         And I should see "T-Shirt watermelon" product not discounted on the list
+
+    @ui @api
+    Scenario: Viewing a product with a positioned default variant
+        Given the store has a product "T-Shirt watermelon" priced at "$19.00"
+        And the product "T-Shirt watermelon" has also an "Extra Large" variant at position -1
+        And this product's price is "$10.00"
```
Comment (Prometee) [inline features/product/viewing_products/viewing_product_price_on_products_list.feature]: It will need a new way of setting the price, because here it asks the DefaultProductVariantResolver what is the available variant and set the price...

File: features/product/viewing_products/viewing_product_price_on_products_list.feature [hunk 6]
```diff
@@ -33,3 +33,13 @@ Feature: Viewing a product price on products list
...
+        And the store classifies its products as "T-Shirts"
+        And this product belongs to "T-Shirts"
+        When I browse products from taxon "T-Shirts"
+        Then I should see the product "T-Shirt watermelon" with price "$10.00"
```
Comment (vvasiloi) [inline features/product/viewing_products/viewing_product_price_on_products_list.feature:45]: I couldn't understand at first how this test ensures the variants order is correct.
I had to look at how `this product's price is "$10.00"` is handled under the hood, in `Sylius\Behat\Context\Setup\ProductContext::theProductChangedItsPriceTo`  and saw that it uses the default variant resolver to get the variant and sets the price to it.
Now, how do you know that it actually didn't override the price for the variant priced at `$19.00`?

File: features/product/viewing_products/viewing_product_price_on_products_list.feature (hunk 5 above)
Comment (vvasiloi) [reply features/product/viewing_products/viewing_product_price_on_products_list.feature]: Yes, that's what I noted in my comment below.

Comment (vvasiloi) [reply features/product/viewing_products/viewing_product_price_on_products_list.feature]: Check the methods that use `createProductVariant` in `ProductContext`.
There are methods like `theProductHasVariants`, `theProductHasVariantWithCode`, `theProductHasVariantPricedAt`, `theProductHasVariantAtPosition`.

Comment (vvasiloi) [reply features/product/viewing_products/viewing_product_price_on_products_list.feature]: A combination of `theProductHasVariantAtPosition` and `thisVariantIsAlsoPricedAtInChannel` should do the job.

File: features/product/viewing_products/viewing_product_price_on_products_list.feature (hunk 6 above)
Comment (Prometee) [reply features/product/viewing_products/viewing_product_price_on_products_list.feature:45]: I manage to add the right price on the second variant using a new `@Given` sentence :
```
@Given /^(this variant) has price at ("[^"]+")$/
```

I also use `0` instead of `-1`, setting `0` set the first created variant to the position `1` and make the second one as the default one.

Comment (vvasiloi) [reply features/product/viewing_products/viewing_product_price_on_products_list.feature:45]: Check my comments in the other thread. I believe you can do it without adding a new method to the context.

File: features/product/viewing_products/viewing_product_price_on_products_list.feature (hunk 5 above)
Comment (Prometee) [reply features/product/viewing_products/viewing_product_price_on_products_list.feature]: Ah yes you are right, I did not pay attention to this method `thisVariantIsAlsoPricedAtInChannel` ! Thx 😉

Comment (Prometee) [reply features/product/viewing_products/viewing_product_price_on_products_list.feature]: @vvasiloi Not possible, because it adds a new channel pricing instead of using the existing one : 

```
An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '24-WEB-US' for key 'sylius_channel_pricing.product_variant_channel_idx'
```

Comment (vvasiloi) [reply features/product/viewing_products/viewing_product_price_on_products_list.feature]: Then maybe modify the method to check if it already has channel pricing before adding a new one?

Comment (vvasiloi) [reply features/product/viewing_products/viewing_product_price_on_products_list.feature]: That's what I expected it to do tbh...

**Comment by Prometee** [comment]
Do I have to silent the PSALM error ? Any other way to circle around this error ?
Or do I have to (re-)insert a BC break by adding a new Product Variant repository method ?

**Comment by vvasiloi** [comment]
> Do I have to silent the PSALM error ? Any other way to circle around this error ? Or do I have to (re-)insert a BC break by adding a new Product Variant repository method ?

Maybe just use `findBy` instead. 🤷‍♂️ It doesn't matter if we also add a custom method in 2.0

**Comment by vvasiloi** [comment]
Or we remove psalm 😆  /cc @jakubtobiasz

File: features/product/viewing_products/viewing_product_price_on_products_list.feature (hunk 5 above)
Comment (Prometee) [reply features/product/viewing_products/viewing_product_price_on_products_list.feature]: I enhance this method and it works on my env.

File: src/Sylius/Component/Product/Resolver/DefaultProductVariantResolver.php [hunk 7]
```diff
@@ -21,16 +21,30 @@ final class DefaultProductVariantResolver implements ProductVariantResolverInter
...
+                    'enabled' => true,
+                ],
+                [
+                    'position' => 'ASC',
+                    'id' => 'ASC',
+                ],
+                1
+            );
 
             return $productVariant;
```
Comment (vvasiloi) [inline src/Sylius/Component/Product/Resolver/DefaultProductVariantResolver.php]:
```suggestion
            $productVariants = $this->productVariantRepository->findBy(
                [
                    'product' => $subject,
                    'enabled' => true,
                ],
                [
                    'position' => 'ASC',
                    'id' => 'ASC',
                ],
                1
            );

            return $productVariants[0] ?? null;
```

**Review by vvasiloi — DISMISSED** [review]

**Review by vvasiloi — APPROVED** [review]

**Review by oallain — APPROVED** [review]

**Review by lchrusciel — APPROVED** [review]

**Comment by lchrusciel** [comment]
Thank you, @Prometee!
