### PR TITLE
[ResourceBundle] Deprecate passing container to ORMTranslatableListener

### LINKED ISSUE #9677: Deprecate passing container to ORMTranslatableListener
**Sylius version affected**: Since 1.0.0, but fix should be applied to the master branch

**Description**:

`ORMTranslatableListener` requires `ContainerInterface` as the second argument only to get one service from it:

https://github.com/Sylius/Sylius/blob/1494e9696ca9b7699abfea304509c03d9f5f3164/src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php#L45-L51

The solution would be to:
1) Drop typehint on that argument
2) Rename it to `$translatableEntityLocaleAssigner`
3) Make a series of conditions:
    - if an instance of `ContainerInterface` is passed, trigger a deprecation and get that service from container
    - if an instance of `TranslatableEntityLocaleAssignerInterface` is passed, do nothing
    - if something else is passed, throw an exception

### PR DESCRIPTION
**Pull request by kayneth**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | yes
| Related tickets | fixes #9677
| License         | MIT

### CODE REVIEW

File: src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php [hunk 1]
```diff
@@ -40,14 +40,32 @@
...
         RegistryInterface $resourceMetadataRegistry,
-        ContainerInterface $container
+        $translatableEntityLocaleAssigner
     ) {
         $this->resourceMetadataRegistry = $resourceMetadataRegistry;
-        $this->translatableEntityLocaleAssigner = $container->get('sylius.translatable_entity_locale_assigner');
+
+        if ($translatableEntityLocaleAssigner instanceof ContainerInterface) {
+            @trigger_error(
+                sprintf('Passing an instance of "%s" is deprecated since 1.0. Use %s instead.',
```
Comment (pamil) [inline src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php]: `1.0` -> `Sylius 1.4` probably :)

Comment (pamil) [reply src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php]: And we might use double quotes around the second class name as well.

File: src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php [hunk 2]
```diff
@@ -40,14 +40,32 @@
 
     /**
      * @param RegistryInterface $resourceMetadataRegistry
-     * @param ContainerInterface $container
+     * @param $translatableEntityLocaleAssigner
      */
     public function __construct(
         RegistryInterface $resourceMetadataRegistry,
-        ContainerInterface $container
+        $translatableEntityLocaleAssigner
```
Comment (pamil) [inline src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php]: Since this PR targets `master`, we could put `object` as a typehint.

File: src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php [hunk 3]
```diff
@@ -40,14 +40,32 @@
...
+            );
+            $translatableEntityLocaleAssigner = $translatableEntityLocaleAssigner->get('sylius.translatable_entity_locale_assigner');
+        }
+
+        if(!$translatableEntityLocaleAssigner instanceof TranslatableEntityLocaleAssignerInterface)
+        {
+            throw new \InvalidArgumentException(sprintf(
+                '`$translatableEntityLocaleAssigner` was expected to return an instance of "%s" , "%s" found',
+                TranslatableEntityLocaleAssignerInterface::class,
+                is_object($translatableEntityLocaleAssigner) ? get_class($translatableEntityLocaleAssigner) : gettype($translatableEntityLocaleAssigner)
```
Comment (pamil) [inline src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php]: Following up the comment about constructor `object` typehint, we might remove this ternary operator and use `get_class` only.

File: src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php [hunk 4]
```diff
@@ -40,14 +40,32 @@
...
+            ));
+        }
+
+        $this->translatableEntityLocaleAssigner = $translatableEntityLocaleAssigner;
```
Comment (pamil) [inline src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php]: In the end, we might extract this constructor logic to a private method like `processTranslatableEntityLocaleAssigner` (that is probably not the best name :)), returning an instance of `TranslatableEntityLocaleAssignerInterface` or throwing an exception if couldn't get it.

Comment (kayneth) [reply src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php]: I canno't come with a better name for that method :/

**Comment by kayneth** [comment]
Hi ! Sorry for the delay but I managed to update this PR :+1:

**Comment by pamil** [comment]
No problem. Thank you, Dylan! 🥇

File: src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php [hunk 5]
```diff
@@ -214,4 +214,30 @@ private function hasUniqueConstraint(ClassMetadata $metadata, array $columns): b
...
+
+    /**
+     * @param object $translatableEntityLocaleAssigner
+     * @return TranslatableEntityLocaleAssignerInterface
+     */
+    private function processTranslatableEntityLocaleAssigner(object $translatableEntityLocaleAssigner): TranslatableEntityLocaleAssignerInterface
+    {
+        if ($translatableEntityLocaleAssigner instanceof ContainerInterface) {
+            @trigger_error(
+                sprintf('Passing an instance of "%s" is deprecated since 1.4. Use "%s" instead.',
```
Comment (teohhanhui) [inline src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php]: The error message is rather confusing...

File: src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php [hunk 6]
```diff
@@ -214,4 +214,30 @@ private function hasUniqueConstraint(ClassMetadata $metadata, array $columns): b
...
+                    ContainerInterface::class, TranslatableEntityLocaleAssignerInterface::class), E_USER_DEPRECATED
+            );
+            $translatableEntityLocaleAssigner = $translatableEntityLocaleAssigner->get('sylius.translatable_entity_locale_assigner');
+        }
+
+        if(!$translatableEntityLocaleAssigner instanceof TranslatableEntityLocaleAssignerInterface)
+        {
+            throw new \InvalidArgumentException(sprintf(
+                '`$translatableEntityLocaleAssigner` was expected to return an instance of "%s" , "%s" found',
```
Comment (teohhanhui) [inline src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php]: The error message is wrong...

File: src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php (hunk 5 above)
Comment (kayneth) [reply src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php]: Because we don't explicitly tell the user why ?

Comment (teohhanhui) [reply src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php]: I think the main problem is that we ask the user to "use `TranslatableEntityLocaleAssignerInterface` instead of `ContainerInterface`" (???)
