### PR TITLE
[API] Fix HTTP error codes for cart operations (fixes #18475)

### LINKED ISSUE #18475: [API] `sylius_api_shop_order_order_item_post` with not found order token throws 500, not 4**
### Sylius version(s) affected

2.1.7

### Description

When POSTing on `/api/v2/shop/orders/{cartToken}/items` (route is `sylius_api_shop_order_order_item_post`) and order with `cartToken` cannot be found, Sylius throws a 500 error, like this one:

```json
{
  "@context": "\/api\/v2\/contexts\/Error",
  "@id": "\/api\/v2\/errors\/500",
  "@type": "hydra:Error",
  "detail": "Cart with given token has not been found.",
  "status": 500,
  "type": "\/errors\/500",
  "trace": ["..."],
  "hydra:description": "Cart with given token has not been found.",
  "hydra:title": "An error occurred"
}
```

I guess it should be a 4**, am I right?

### How to reproduce

Create an order with:

```
POST /api/v2/shop/orders/not_a_thing/items
Content-Type: application/ld+json

{
  "productVariant": "{{existingProductVariant}}",
  "quantity": 1
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Rafikooo**
## Summary
- Replace generic 500 errors with proper 4xx HTTP codes for cart API operations
- Add dedicated exception classes for better error handling
- Ensure consistent error responses across cart endpoints

## Changes
- Add `CartNotFoundException` returning HTTP 422 for non-existent carts
- Add `ProductVariantNotFoundException` returning HTTP 422 for invalid product variants
- Update `AddItemToCartHandler` to throw dedicated exceptions instead of InvalidArgumentException
- Update `BlameCartHandler` to use ConflictHttpException (409) for cart conflicts
- Add functional tests to verify proper HTTP error codes

## Why 422 instead of 404?
For POST operations that cannot be processed due to missing resources, 422 Unprocessable Entity is more semantically correct than 404 Not Found, as it indicates the request cannot be processed rather than the endpoint not existing.

Fixes #18475

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved error handling and HTTP status codes for cart operations with clearer messages when carts or product variants cannot be found.

* **Tests**
  * Added test coverage for error scenarios during cart item addition and checkout operations.

### CODE REVIEW

File: src/Sylius/Bundle/ApiBundle/Exception/CartNotFoundException.php [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+ * file that was distributed with this source code.
+ */
+
+declare(strict_types=1);
+
+namespace Sylius\Bundle\ApiBundle\Exception;
+
+use Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException;
+
+final class CartNotFoundException extends UnprocessableEntityHttpException
```
Comment (NoResponseMate) [inline src/Sylius/Bundle/ApiBundle/Exception/CartNotFoundException.php]:
```suggestion
final class UnprocessableCartException extends UnprocessableEntityHttpException
```
?
Having a `NotFound*` exception return codes other than 404 is confusing, as we already have a few actual' NotFound' exceptions in the API scope that behave as expected.

File: src/Sylius/Bundle/ApiBundle/Exception/ProductVariantNotFoundException.php [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+ * file that was distributed with this source code.
+ */
+
+declare(strict_types=1);
+
+namespace Sylius\Bundle\ApiBundle\Exception;
+
+use Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException;
+
+final class ProductVariantNotFoundException extends UnprocessableEntityHttpException
```
Comment (NoResponseMate) [inline src/Sylius/Bundle/ApiBundle/Exception/ProductVariantNotFoundException.php]: Similar case as w/ the cart exception

**Review by NoResponseMate — APPROVED** [review]
