### PR TITLE
Bugfix/invalid credentials message is not translated during ajax login

### LINKED ISSUE #12738: "Invalid credentials" message is not translated during AJAX login
**Sylius version affected**: reproduced on 1.8.x but I'm sure all version are affected

**Description**  
During the login via AJAX request the "Invalid credentials" message is not translated in the user locale language.

**Steps to reproduce**  
* Go to https://demo.sylius.com/admin and login to the admin panel
* Go to Channels -> Fashion Web Store
* Set the channel locale to a locale for which there's a translation of the Symfony's "Invalid credentials" message (for example German).
* Go to the frontend https://demo.sylius.com
* Add a product to cart
* Go to the checkout addressing page
* Enter shop@example.com in the Email field
* Enter a wrong password in the Password field
* Click login
* You'll see "Invalid credentials" but you should see the German translation of that message (Fehlerhafte Zugangsdaten.)

**Possible Solution**  
The problem is here:

https://github.com/Sylius/Sylius/blob/ec917067c5bc7ab38f119edac76566a88a7f5aa6/src/Sylius/Bundle/UserBundle/Authentication/AuthenticationFailureHandler.php#L27

The custom AuthenticationFailureHandler does not translate the message.

I'll provide a PR for that.

### PR DESCRIPTION
**Pull request by michalkaczmarek-bitbag**
| Q               | A
|-----------------|-----
| Branch?         | 1.14
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | https://github.com/Sylius/Sylius/issues/12738
| License         | MIT

### CODE REVIEW

File: src/Sylius/Bundle/UserBundle/spec/Authentication/AuthenticationFailureHandlerSpec.php [hunk 1]
```diff
@@ -42,9 +48,14 @@ function it_is_a_authentication_failure_handler(): void
     function it_returns_json_response_if_request_is_xml_based(
```
Comment (Rafikooo) [inline src/Sylius/Bundle/UserBundle/spec/Authentication/AuthenticationFailureHandlerSpec.php]:
```suggestion
    function it_returns_translated_json_response_if_request_is_xml_based(
```

File: src/Sylius/Bundle/UserBundle/spec/Authentication/AuthenticationFailureHandlerSpec.php [hunk 2]
```diff
@@ -42,9 +48,14 @@ function it_is_a_authentication_failure_handler(): void
...
         Request $request,
         AuthenticationException $authenticationException,
+        TranslatorInterface $translator,
     ): void {
         $request->isXmlHttpRequest()->willReturn(true);
+        $request->getLocale()->willReturn('fr');
         $authenticationException->getMessageKey()->willReturn('Invalid credentials.');
+        $translator->trans('Invalid credentials.', [], 'security', 'fr')
+            ->willReturn('Identifiants invalides.')
+            ->shouldBeCalled();
```
Comment (Rafikooo) [inline src/Sylius/Bundle/UserBundle/spec/Authentication/AuthenticationFailureHandlerSpec.php]: I recommend running `vendor/bin/ecs` before pushing the PR.
```suggestion
            ->shouldBeCalled()
        ;
```

File: src/Sylius/Bundle/UserBundle/Authentication/AuthenticationFailureHandler.php [hunk 3]
```diff
@@ -13,18 +13,37 @@
...
+        parent::__construct($httpKernel, $httpUtils, $options, $logger);
+    }
+
     public function onAuthenticationFailure(Request $request, AuthenticationException $exception): Response
     {
+        $translationMessage = $this->translator->trans($exception->getMessageKey(), [], 'security', $request->getLocale());
+
         if ($request->isXmlHttpRequest()) {
-            return new JsonResponse(['success' => false, 'message' => $exception->getMessageKey()], 401);
+            return new JsonResponse(['success' => false, 'message' => $translationMessage], 401);
```
Comment (Rafikooo) [inline src/Sylius/Bundle/UserBundle/Authentication/AuthenticationFailureHandler.php]: You could inline the service call:
```suggestion
            return new JsonResponse([
                'success' => false,
                'message' => $this->translator->trans($exception->getMessageKey(), [], 'security', $request->getLocale());], 
                Symfony\Component\HttpFoundation\Response::HTTP_UNAUTHORIZED,
            );
```
(Import `Symfony\Component\HttpFoundation\Response:` at the top od the class)

File: src/Sylius/Bundle/UserBundle/Authentication/AuthenticationFailureHandler.php [hunk 4]
```diff
@@ -13,18 +13,37 @@
...
+        array $options = [],
+        ?LoggerInterface $logger = null,
+        private readonly ?TranslatorInterface $translator = null,
+    ) {
+        parent::__construct($httpKernel, $httpUtils, $options, $logger);
+    }
+
     public function onAuthenticationFailure(Request $request, AuthenticationException $exception): Response
     {
+        $translationMessage = $this->translator->trans($exception->getMessageKey(), [], 'security', $request->getLocale());
```
Comment (GSadee) [inline src/Sylius/Bundle/UserBundle/Authentication/AuthenticationFailureHandler.php]: As the `$translator` is nullable, you should handle also the case when it will be passed as null

File: src/Sylius/Bundle/UserBundle/Authentication/AuthenticationFailureHandler.php [hunk 5]
```diff
@@ -13,18 +13,44 @@
...
-            return new JsonResponse(['success' => false, 'message' => $exception->getMessageKey()], 401);
+            return new JsonResponse([
+                'success' => false,
+                'message' => $this->translator?->trans(
+                    $exception->getMessageKey(),
+                    [],
+                    'security',
+                    $request->getLocale(),
+                ) ?? $exception->getMessageKey(),
+                Response::HTTP_UNAUTHORIZED,
```
Comment (Rafikooo) [inline src/Sylius/Bundle/UserBundle/Authentication/AuthenticationFailureHandler.php]: The response code is the second parameter of the `JsonResponse` object:
```suggestion
            ], Response::HTTP_UNAUTHORIZED);
```

File: src/Sylius/Bundle/UserBundle/spec/Authentication/AuthenticationFailureHandlerSpec.php [hunk 6]
```diff
@@ -39,12 +45,18 @@ function it_is_a_authentication_failure_handler(): void
         $this->shouldImplement(AuthenticationFailureHandlerInterface::class);
     }
 
-    function it_returns_json_response_if_request_is_xml_based(
+    function it_returns_translated_json_response_if_request_is_xml_based(
```
Comment (Rafikooo) [inline src/Sylius/Bundle/UserBundle/spec/Authentication/AuthenticationFailureHandlerSpec.php]:
```suggestion
    function it_returns_translated_json_response_if_request_is_ajax_based(
```

File: src/Sylius/Bundle/UserBundle/spec/Authentication/AuthenticationFailureHandlerSpec.php
Comment (Rafikooo) [inline src/Sylius/Bundle/UserBundle/spec/Authentication/AuthenticationFailureHandlerSpec.php:1]: I suggest removing this test class and porting the PHPUnit version from Sylius 2.1:
https://github.com/Sylius/Sylius/blob/2.1/src/Sylius/Bundle/UserBundle/tests/Authentication/AuthenticationFailureHandlerTest.php  
Then expand it with the new cases, including one that covers the other path: `it_returns_untranslated_json_response_if_translator_is_not_available`. This way we can save pain during upmerge.

File: src/Sylius/Bundle/UserBundle/spec/Authentication/AuthenticationFailureHandlerSpec.php (hunk 6 above)
Comment (michalkaczmarek-bitbag) [reply src/Sylius/Bundle/UserBundle/spec/Authentication/AuthenticationFailureHandlerSpec.php]: This class has been removed. Added class with PHPUnit tests according to below suggestion in comment.

**Review by Rafikooo — APPROVED** [review]
