### PR TITLE
[Admin] Fix statistics to take into account only fulfilled orders

### LINKED ISSUE #8251: Statistics in show customer in admin dashboard, count also orders in state awaiting_payment
Hello.

One customer with order to bank transfer, has a order with following state.
order-mysql

I understand that in statistics of user, this order should not be included.

statistics_user

### PR DESCRIPTION
**Pull request by GSadee**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | yes |
| Related tickets | fixes #8251 |
| License         | MIT |

It is based on #8285 and associated with #8516

### CODE REVIEW

File: src/Sylius/Behat/Context/Setup/OrderContext.php [hunk 1]
```diff
@@ -806,4 +805,108 @@ private function addVariantWithPriceToOrder(OrderInterface $order, ProductVarian
...
+     * @param ProductInterface $product
+     * @param $isFulfilled
+     */
+    private function createOrdersForCustomer(
+        CustomerInterface $customer,
+        $orderCount,
+        ChannelInterface $channel,
+        $productCount,
+        ProductInterface $product,
+        $isFulfilled = false
```
Comment (pamil) [inline src/Sylius/Behat/Context/Setup/OrderContext.php]: Missing typehints

File: src/Sylius/Behat/Context/Setup/OrderContext.php [hunk 2]
```diff
@@ -806,4 +805,108 @@ private function addVariantWithPriceToOrder(OrderInterface $order, ProductVarian
...
+     * @param $numberOfOrders
+     * @param $total
+     * @param $isFulfilled
+     */
+    private function createOrdersWithProduct(
+        $numberOfCustomers,
+        $numberOfOrders,
+        $total,
+        ProductInterface $product,
+        $isFulfilled = false
```
Comment (pamil) [inline src/Sylius/Behat/Context/Setup/OrderContext.php]: Missing typehints & outdated docblock

File: src/Sylius/Behat/Context/Setup/OrderContext.php [hunk 3]
```diff
@@ -806,4 +805,108 @@ private function addVariantWithPriceToOrder(OrderInterface $order, ProductVarian
...
         $order->addItem($item);
     }
+
+    /**
+     * @param $numberOfCustomers
+     * @param $numberOfOrders
+     * @param $total
+     * @param $isFulfilled
+     */
+    private function createOrders($numberOfCustomers, $numberOfOrders, $total, $isFulfilled = false)
```
Comment (pamil) [inline src/Sylius/Behat/Context/Setup/OrderContext.php]: Missing typehints

File: src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php [hunk 4]
```diff
@@ -88,7 +88,7 @@ public function findForCustomerStatistics(CustomerInterface $customer): array
     {
         return $this->createByCustomerIdQueryBuilder($customer->getId())
             ->andWhere('o.state NOT IN (:states)')
-            ->setParameter('states', [OrderInterface::STATE_CART, OrderInterface::STATE_CANCELLED])
+            ->setParameter('states', [OrderInterface::STATE_NEW, OrderInterface::STATE_CANCELLED])
```
Comment (lchrusciel) [inline src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php]: Shouldn't the cart s be excluded also?

Comment (GSadee) [reply src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php]: And it is in `createByCustomerIdQueryBuilder($customerId)`

Comment (pamil) [reply src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php]: Shouldn't we get only `OrderInterface::STATE_FULFILLED` carts?

Comment (GSadee) [reply src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php]: And we get only `OrderInterface::STATE_FULFILLED`. I know that this line is not fully readable, but when I tried:
```
->andWhere('o.state = :state')
->setParameter('state', OrderInterface:: STATE_FULFILLED)
```
it doesn't work, because of parameter which was set in `createByCustomerIdQueryBuilder($customerId)`

Comment (pamil) [reply src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php]: Hmm, what about not using that `createByCustomerIdQueryBuilder` at all here? It looks tricky.

File: src/Sylius/Behat/Context/Setup/OrderContext.php [hunk 5]
```diff
@@ -806,4 +811,113 @@ private function addVariantWithPriceToOrder(OrderInterface $order, ProductVarian
...
+        int $numberOfCustomers,
+        int $numberOfOrders,
+        string $total,
+        bool $isFulfilled = false
+    ): void {
+        $customers = $this->generateCustomers($numberOfCustomers);
+        $sampleProductVariant = $this->sharedStorage->get('variant');
+        $total = $this->getPriceFromString($total);
+
+        for ($i = 0; $i < $numberOfOrders; $i++) {
```
Comment (lchrusciel) [inline src/Sylius/Behat/Context/Setup/OrderContext.php]: We could think about using ExampleFacotories to create test orders but that an idea for later

File: src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php [hunk 6]
```diff
@@ -86,9 +86,12 @@ public function findByCustomer(CustomerInterface $customer): array
...
     {
-        return $this->createByCustomerIdQueryBuilder($customer->getId())
-            ->andWhere('o.state NOT IN (:states)')
-            ->setParameter('states', [OrderInterface::STATE_CART, OrderInterface::STATE_CANCELLED])
+
+        return $this->createQueryBuilder('o')
+            ->andWhere('o.customer = :customerId')
+            ->andWhere('o.state = :state')
+            ->setParameter('customerId', $customer->getId())
+            ->setParameter('state', OrderInterface::STATE_FULFILLED)
```
Comment (lchrusciel) [inline src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php]: 👍

**Comment by lchrusciel** [comment]
Nice one Grzegorz!
