### PR TITLE
FIX zoneMembers not unique ID

### LINKED ISSUE #15442: [API] ZoneMember @id not unique
**Sylius version affected**: 1.12.11 (tested with this version, probably also older versions are affected)

**Description**  
Is there a major flaw within the Zone/ZoneMember API v2?
The members have the `@id` e.g. `/api/v2/admin/zone-members/DE`
But this `id` is not unique, there could be multiple zones which have DE as a member.
So this could easily lead to a _"More than one result was found for query although one row or none was expected"_ error, e. g. editing zone members with PUT (if you have multiple country zones with DE members)

**Steps to reproduce**  
1. Create multiple country Zones with member DE
2. Try to edit zones with PUT API v2 endpoint `api/v2/admin/zones/<zone-code>` (e. g. removing and re-adding DE as member)

**Possible Solution**  
The country code DE should not be part of the `@id`, the `@id` needs to be the real `id` of the ZoneMember object (?)

### PR DESCRIPTION
**Pull request by TheMilek**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12                   |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no  |
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/15442                      |
| License         | MIT                                                          |

### CODE REVIEW

File: src/Sylius/Behat/Context/Api/Admin/ManagingZonesContext.php [hunk 1]
```diff
@@ -360,6 +375,27 @@ public function thisZoneShouldHaveOnlyTheProvinceMember(ZoneInterface $zone, Zon
...
+    /**
+     * @Then /^(this zone) should have ("([^"]+)" and "([^"]+)" country members)$/
+     */
+    public function thisZoneShouldHaveTheCountryAndTheProvinceMembers(
+        ZoneInterface $zone,
+        array $zoneMembers,
+    ): void {
+        foreach ($zoneMembers as $zoneMember) {
+            Assert::true($this->responseChecker->hasItemWithValue(
+                $this->client->subResourceIndex(Resources::ZONES, 'members', $zone->getCode()),
```
Comment (Wojdylak) [inline src/Sylius/Behat/Context/Api/Admin/ManagingZonesContext.php]: You can make one request and then use the `getLastResponse` method.

File: features/addressing/managing_zones/removing_and_adding_zone_members_that_have_the_same_code_in_more_than_one_zone.feature [hunk 2]
```diff
@@ -0,0 +1,26 @@
+@managing_zones
+Feature: Removing and adding zone members that have the same code in more than one zone
```
Comment (Wojdylak) [inline features/addressing/managing_zones/removing_and_adding_zone_members_that_have_the_same_code_in_more_than_one_zone.feature]: For me, this should be only an API test, because the problem is that we set the identifier to the code field. The test should verify that we can get a zone member if there are two zones with the same country (zone member). WDYT?

File: features/addressing/managing_zones/removing_and_adding_zone_members_that_have_the_same_code_in_more_than_one_zone.feature [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+    In order to be able to edit zone's zone members
```
Comment (GSadee) [inline features/addressing/managing_zones/removing_and_adding_zone_members_that_have_the_same_code_in_more_than_one_zone.feature]:
```suggestion
    In order to be able to edit zone's members
```
😅

File: features/addressing/managing_zones/removing_and_adding_zone_members_that_have_the_same_code_in_more_than_one_zone.feature (hunk 2 above)
Comment (GSadee) [reply features/addressing/managing_zones/removing_and_adding_zone_members_that_have_the_same_code_in_more_than_one_zone.feature]: I'm also not sure that this scenario fully covers the problem we are trying to fix. Or at least it could be simplified to only adding the zone member with the same code that exists for other member in other zone, this removing part seems to be not necessary.

File: src/Sylius/Behat/Context/Api/Admin/ManagingZonesContext.php [hunk 4]
```diff
@@ -360,6 +375,27 @@ public function thisZoneShouldHaveOnlyTheProvinceMember(ZoneInterface $zone, Zon
...
+                'code',
+                $zoneMember->getCode(),
+            ));
+        }
+
+        Assert::same(
+            $this->responseChecker->countCollectionItems($this->client->subResourceIndex(Resources::ZONES, 'members', $zone->getCode())),
```
Comment (GSadee) [inline src/Sylius/Behat/Context/Api/Admin/ManagingZonesContext.php]: As above, use last response to this checker

File: src/Sylius/Behat/Context/Ui/Admin/ManagingZonesContext.php [hunk 5]
```diff
@@ -145,6 +145,16 @@ public function iAddAZoneMember($name)
         $this->createPage->chooseMember($name);
     }
 
+    /**
+     * @When I add the country :country again
+     */
+    public function iAddTheCountryAgain(string $country): void
```
Comment (GSadee) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingZonesContext.php]:
```suggestion
     * @When I add the country :countryName again
     */
    public function iAddTheCountryAgain(string $countryName): void
```

File: src/Sylius/Behat/Context/Ui/Admin/ManagingZonesContext.php [hunk 6]
```diff
@@ -212,6 +222,18 @@ public function thisZoneShouldHaveOnlyTheProvinceMember(ZoneInterface $zone, Zon
         Assert::same($this->updatePage->countMembers(), 1);
     }
 
+    /**
+     * @Then /^(this zone) should have ("([^"]+)" and "([^"]+)" country members)$/
+     */
+    public function thisZoneShouldHaveCountryMembers(ZoneInterface $zone, array $zoneMembers)
```
Comment (GSadee) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingZonesContext.php]: Missing return type

File: src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ZoneMember.xml [hunk 7]
```diff
@@ -25,14 +25,15 @@
         <itemOperations>
             <itemOperation name="admin_get">
                 <attribute name="method">GET</attribute>
+                <attribute name="path">/zone_members/{id}</attribute>
```
Comment (GSadee) [inline src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ZoneMember.xml]:
```suggestion
                <attribute name="path">/zone-members/{id}</attribute>
```
and add the note to the UPGRADE file about changing this endpoint

File: features/addressing/managing_zones/removing_and_adding_zone_members_that_have_the_same_code_in_more_than_one_zone.feature (hunk 2 above)
Comment (TheMilek) [reply features/addressing/managing_zones/removing_and_adding_zone_members_that_have_the_same_code_in_more_than_one_zone.feature]: yeah I changed the context as it should focus more on the `re-adding` as the problem occurs in that case

**Review by NoResponseMate — APPROVED** [review]

**Comment by NoResponseMate** [comment]
Thank you, @TheMilek!
