### PR TITLE
[Fix] Take care of no session available in cart storage

### LINKED ISSUE #14829: Sylius crashes when sending preflight request (OPTIONS) in dev & debug mode
**Sylius version affected**: 1.12.4

**Description**  
**Main Problem:** Sylius crashes when sending preflight request (OPTIONS) in dev & debug mode

We are working on a Next/Sylius application and I am having trouble using both the frontend & backend locally with debug & dev mode.

1. Why this happens?

Whenever I try to send a request from the frontend to the backend, the Preflight request fails (the OPTIONS request sent before the POST for instance).
=> Because an error is thrown `There is currently no session available` (`SessionNotFoundException`) which is normal for an `OPTIONS` request I guess
=> Because Sylius tries to check via the `SessionProvider::getSession` if the user has a cart for the specific channel (`CartSessionStorage::hasForChannel`)
=> Because the `SessionAndChannelBasedCartContext` is part of the `CompositeCartContext` and is called in the `CartCollector` class
=> Because I am assuming Sylius adds a `CartCollector` to the collectors of the Symfony Profiler to display debug data regarding the `cart` 

2. Why this does not happen in production?

In production we have the profiler disabled with `APP_DEBUG` set to 0 and `APP_ENV` set to `prod`.

**Steps to reproduce**  
1. Setup a frontend on `localhost:3000` for example
2. Send a request to your backend on `localhost:8000`
3. Send an OPTIONS request on any `v2/shop/` route with `APP_DEBUG` set to 1, `APP_ENV` set to `dev` and the profiler in `dev/framework.yaml` set to
```
framework:
    profiler: { only_exceptions: false }
```

**Possible Solution**  
Right now we are removing the `framework.yaml` when we want to work with the API (headless mode) and we add it back when working in the admin

I'd be glad to know if someone encountered this using a similar setup or if it is something that has never been spotted with Sylius.

### PR DESCRIPTION
**Pull request by NoResponseMate**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12 |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no?                                                       |
| Deprecations?   | no |
| Related tickets | fixes #14829                       |
| License         | MIT                                                          |

### CODE REVIEW

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thanks, Jan! :1st_place_medal:

File: src/Sylius/Bundle/CoreBundle/Storage/CartSessionStorage.php [hunk 1]
```diff
@@ -35,7 +36,11 @@ public function __construct(
 
     public function hasForChannel(ChannelInterface $channel): bool
     {
-        return SessionProvider::getSession($this->requestStackOrSession)->has($this->getCartKeyName($channel));
+        try {
+            return SessionProvider::getSession($this->requestStackOrSession)->has($this->getCartKeyName($channel));
+        } catch (SessionNotFoundException) {
+            return false;
```
Comment (lecajer) [inline src/Sylius/Bundle/CoreBundle/Storage/CartSessionStorage.php:42]: Thanks, I need this fix.
I got `SessionNotFoundException` `There is currently no session available.`
When API recieves `OPTIONS /api/v2`
