### PR TITLE
[Admin][Promotion] Fix removing taxon used in promotion rule

### LINKED ISSUE #10225: Removing taxon used in promotion breaks the promotion edit page
**Sylius version affected**: 1.2.x

**Description**  
It seems that admin user is able to delete a taxon that is used in the rules on a promotion. Deleting the taxon makes the promotion edit page unusable:

```
Uncaught PHP Exception Symfony\Component\Form\Exception\TransformationFailedException: "Unable to transform value for property path "[taxon]": Object "AppBundle\Entity\Taxon" with identifier "code"="identifier-code-here" does not exist." at /app/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 1048
```

Probably best that the taxon cannot be used, or the promotion stays accessible. Anyhow the admin needs to know this is happening, as it might lead to unexpected results.

### PR DESCRIPTION
**Pull request by GSadee**
| Q               | A
| --------------- | -----
| Branch?         | 1.3
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #10225
| License         | MIT

Zrzut ekranu 2019-05-10 o 12 50 29

### CODE REVIEW

File: src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php [hunk 1]
```diff
@@ -617,6 +617,27 @@ public function thePromotionsShouldHavePriority(PromotionInterface $promotion, i
...
+     * @Then the :promotion promotion should not have any rule configured
+     */
+    public function thePromotionShouldNotHaveAnyRuleConfigured(PromotionInterface $promotion): void
+    {
+        $this->iWantToModifyAPromotion($promotion);
+
+        Assert::false($this->updatePage->hasAnyRule());
+    }
+
+
```
Comment (Tomanhez) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php]: Redundant blank line

File: src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php [hunk 2]
```diff
@@ -617,6 +620,26 @@ public function thePromotionsShouldHavePriority(PromotionInterface $promotion, i
         Assert::same($this->updatePage->getPriority(), $priority);
     }
 
+    /**
+     * @Then the :promotion promotion should have :ruleName rule configured
+     */
+    public function thePromotionShouldHaveRuleConfigured(PromotionInterface $promotion, string $ruleName): void
+    {
+        $this->iWantToModifyAPromotion($promotion);
```
Comment (lchrusciel) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php]: Can we also make a `submit` on this page? Just to ensure, that clicking a button will not 💥

File: src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+    {
+        $promotionRules = $this->promotionRuleRepository->findBy(['type' => HasTaxonRuleChecker::TYPE]);
+
+        /** @var PromotionRuleInterface $promotionRule */
+        foreach ($promotionRules as $promotionRule) {
+            $configuration = $promotionRule->getConfiguration();
+            if (in_array($taxonCode, $configuration['taxons'])) {
+                $taxons = array_filter(
+                    $configuration['taxons'],
+                    function (string $code) use ($taxonCode) {
```
Comment (lchrusciel) [inline src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php]: we could add return typehint here

File: src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+    /** @var EntityManagerInterface */
+    private $manager;
+
+    public function __construct(RepositoryInterface $promotionRuleRepository, EntityManagerInterface $manager)
+    {
+        $this->promotionRuleRepository = $promotionRuleRepository;
+        $this->manager = $manager;
+    }
+
+    public function removeTaxonFromPromotionRules(GenericEvent $event): void
```
Comment (lchrusciel) [inline src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php]: I have two problems with this implementation. First of all, it will work only for taxons deleted through Resource Controller. Secondly, we are hardcoded to only two existing rules that contain relation to the taxon(or taxons).

I would prefer, to decouple this logic from ResourceController, but I'm not sure if it's a good place to do it. For sure, it is a good place to start a discussion.
According to the second problem, it could be resolved with some new interface and iteration over all promotion rules in our store. Something like: TaxonsAwarePromotionRule or something similar. WDYT?

File: src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+    }
+
+    private function resolveHasTaxonRules(string $taxonCode): void
+    {
+        $promotionRules = $this->promotionRuleRepository->findBy(['type' => HasTaxonRuleChecker::TYPE]);
+
+        /** @var PromotionRuleInterface $promotionRule */
+        foreach ($promotionRules as $promotionRule) {
+            $configuration = $promotionRule->getConfiguration();
+            if (in_array($taxonCode, $configuration['taxons'])) {
```
Comment (lchrusciel) [inline src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php]: WDYT about simplifing this `if`?
```php
if (($key = array_search($taxonCode, $configuration['taxons'])) !== false) {
    unset($configuration['taxons'][$key]);
}
```
or
```php
$configuration['taxons'] = array_diff($configuration['taxons'], [$taxonCode])
```

File: src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php (hunk 2 above)
Comment (GSadee) [reply src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php]: Added in other step

File: src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php (hunk 4 above)
Comment (GSadee) [reply src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php]: We've discussed the first problem, that this behaviour could be associated with the resource event.
About the second one, I've moved the logic of removing taxon from configuration to separate services.

File: src/Sylius/Behat/Page/Admin/Promotion/UpdatePage.php [hunk 6]
```diff
@@ -92,6 +92,29 @@ public function hasEndsAt(\DateTimeInterface $dateTime): bool
             && $this->getElement('ends_at_time')->getValue() === date('H:i', $timestamp);
     }
 
+    public function hasAnyRule(): bool
+    {
+        $items = $this->getElement('rules')->findAll('css', 'div[data-form-collection="item"]');
+
+        return 0 > count($items);
```
Comment (lchrusciel) [inline src/Sylius/Behat/Page/Admin/Promotion/UpdatePage.php]: Shouldn't it be like this:
```suggestion
        return 0 < count($items);
```
?

File: src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php [hunk 7]
```diff
@@ -0,0 +1,62 @@
...
+    private $hasTaxonRuleUpdater;
+
+    /** @var TaxonAwareRuleUpdaterInterface */
+    private $totalOfItemsFromTaxonRuleUpdater;
+
+    /** @var SessionInterface */
+    private $session;
+
+    public function __construct(
+        TaxonAwareRuleUpdaterInterface $hasTaxonRuleUpdater,
```
Comment (lchrusciel) [inline src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php]: Would it work with variadic in the constructor?

```php
    public function __construct(
		SessionInterface $session,
        TaxonAwareRuleUpdaterInterface ....$ruleUpdaters
        
    ) {
        $this->session = $session;
        $this->ruleUpdaters = $ruleUpdaters;
    }
```

and iterate over them?

File: src/Sylius/Behat/Service/NotificationChecker.php [hunk 8]
```diff
@@ -35,12 +35,21 @@ public function checkNotification(string $message, NotificationType $type): void
...
         throw new NotificationExpectationMismatchException($type, $message);
     }
+
+    private function resolveClass(NotificationType $type): string
+    {
+        if ($type->__toString() === 'info') {
+            return 'info';
+        }
+
+        return $type->__toString() === 'success' ? 'positive' : 'negative';
```
Comment (Zales0123) [inline src/Sylius/Behat/Service/NotificationChecker.php]: What about having some type-class-map? Sth like:

```php
private function resolveClass(NotificationType $type): string
{
    $typeClassMap = [
        'info' => 'info',
        'failure' => 'negative',
        'success' => 'positive',
    ];

    Assert::keyExist($typeClassMap, $type->__toString());

    return $typeClassMap($type->__toString());
}
```

? I know it's a little bit longer, but much cleaner IMO and more extendable. But also it can be done as an improvement in a separate PR, so no pressure 🖖

File: src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php [hunk 9]
```diff
@@ -0,0 +1,59 @@
...
+    /** @var SessionInterface */
+    private $session;
+
+    /** @var TaxonAwareRuleUpdaterInterface[] */
+    private $ruleUpdaters;
+
+    public function __construct(
+        SessionInterface $session,
+        TaxonAwareRuleUpdaterInterface ...$ruleUpdaters
+
```
Comment (Zales0123) [inline src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php]: 😱

File: src/Sylius/Behat/Service/NotificationChecker.php [hunk 10]
```diff
@@ -35,12 +36,25 @@ public function checkNotification(string $message, NotificationType $type): void
...
+
+    private function resolveClass(NotificationType $type): string
+    {
+        $typeClassMap = [
+            'failure' => 'negative',
+            'info' => 'info',
+            'success' => 'positive',
+        ];
+
+        Assert::keyExists($typeClassMap, $type->__toString());
```
Comment (lchrusciel) [inline src/Sylius/Behat/Service/NotificationChecker.php]: I'm just wondering, what is better
```suggestion
        Assert::keyExists($typeClassMap, (string) $type);
```

**Comment by lchrusciel** [comment]
Thank you, Grzegorz! :1st_place_medal:
