### PR TITLE
Optimize matching zones to a given address

### LINKED ISSUE #9777: Performance issue: too many database queries when many zones
**Sylius version affected**: 1.2.5

**Description**  

Using the State Machine, there are three steps (add address, add shipping add payment) which are creating lots of database queries to sylius_zone_member and sylius_zone and has a huge performance impact. I would like to keep my zones in order to create some logic for shipping.

**Steps to reproduce**  

We can use Sylius Front to reproduce the bug. After sending the form from the next URLs, you can see the perf (i have 325 zones but only 31 countries):
/checkout/address => 1602 queries (sylius_zone_member 325, sylius_zone > 1000) 
/checkout/select-shipping => 2825 queries (sylius_zone_member 325, sylius_zone > 1000) 
/checkout/select-payment => 1598 queries (sylius_zone_member 325, sylius_zone > 1000)

**Possible Solution**  

- Use only country to select the three step.
- Avoid using the same requests 3 times
- Lower highly number of request

### PR DESCRIPTION
**Pull request by jakubtobiasz**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13
| Bug fix?        | performance fix
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | closes #9777
| License         | MIT                                                          |

Test data:
~1000 zones <-> zone members 1:1
~20 zones created with up to 7 level of nesting (zone in the zone in the zone...)

Before:
CleanShot 2023-09-15 at 17 07 08@2x

After:
CleanShot 2023-09-15 at 17 08 42@2x

### CODE REVIEW

**Review by GSadee — DISMISSED** [review]

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+    }
+
+    /**
+     * @param array<ZoneInterface> $zones
+     *
+     * @return array<ZoneInterface>
+     */
+    public function findAllByZones(array $zones, ?string $scope = null): array
+    {
+        $zones = array_map(
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]:
```patch
--- $zones
+++ $zonesCodes
```
or some other option not to over-write variable, I think phpstan will raise an issue for this.

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+        return $query->getQuery()->getOneOrNullResult();
+    }
+
+    /** @return ZoneInterface[] */
+    public function findAllByAddress(AddressInterface $address, ?string $scope = null): array
+    {
+        return $this->getFindByAddressQueryBuilder($address, $scope)->getQuery()->getResult();
+    }
+
+    private function getFindByAddressQueryBuilder(AddressInterface $address, ?string $scope = null): QueryBuilder
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]:
```patch
--- private function getFindByAddressQueryBuilder
+++ protected function createByAddressQueryBuilder
```

File: src/Sylius/Component/Addressing/spec/Matcher/ZoneMatcherSpec.php [hunk 3]
```diff
@@ -13,274 +13,65 @@
...
-use Sylius\Component\Addressing\Model\ProvinceInterface;
 use Sylius\Component\Addressing\Model\ZoneInterface;
-use Sylius\Component\Addressing\Model\ZoneMemberInterface;
-use Sylius\Component\Resource\Repository\RepositoryInterface;
+use Sylius\Component\Addressing\Repository\ZoneRepositoryInterface;
 
 final class ZoneMatcherSpec extends ObjectBehavior
 {
-    function let(RepositoryInterface $repository): void
+    public function let(ZoneRepositoryInterface $zoneRepository): void
```
Comment (diimpp) [inline src/Sylius/Component/Addressing/spec/Matcher/ZoneMatcherSpec.php]: Spec methods shouldn't contain visibility like `public`

**Review by diimpp — COMMENTED** [review]
I see it's a WIP, I'm just passing by :sweat_smile:

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php (hunk 2 above)
Comment (diimpp) [reply src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]: Not quite sure about `protected` vs `public`, checked few components repos and if `createXXXQueryBuilder` methods are present, then they are public.

Comment (Prometee) [reply src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]: I would vote for public method, those methods are very handful in most of the cases

File: src/Sylius/Bundle/AddressingBundle/test/var/db.sql
Comment (jakubtobiasz) [inline src/Sylius/Bundle/AddressingBundle/test/var/db.sql:1]: I have no idea how to make it working without the sqlite database file :|. If anyone has an idea – I encourage to share or directly contribute. Otherwise let's merge it and wait for new test apps.

Comment (jakubtobiasz) [reply src/Sylius/Bundle/AddressingBundle/test/var/db.sql:1]: CleanShot 2023-09-15 at 19 12 49@2x
🤷🏼‍♂️

File: src/Sylius/Bundle/AddressingBundle/Tests/Matcher/ZoneMatcherTest/fixtures.yaml [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+        code: VISEGRAD_GROUP
+        name: Visegrad Group
+        type: zone
+        members: ["@member_poland_visegrad_group"]
+    zone_eu:
+        code: EU
+        name: European Union
+        type: zone
+        members: ["@member_visegrad_group"]
+        scope: 'only_eu'
```
Comment (NoResponseMate) [inline src/Sylius/Bundle/AddressingBundle/Tests/Matcher/ZoneMatcherTest/fixtures.yaml]: I'd be for using preexisting scopes ie `tax`/`shipping`/`all`, though the first two live in core it'd be less confusing than now

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 5]
```diff
@@ -0,0 +1,126 @@
...
+
+        return $query;
+    }
+
+    /**
+     * @param array<ZoneInterface> $zones
+     *
+     * @return array<ZoneInterface>
+     */
+    public function findAllByZones(array $zones, ?string $scope = null): array
```
Comment (NoResponseMate) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]:
```suggestion
    public function findZonesByMembers(array $members, ?string $scope = null): array
```
?

File: src/Sylius/Bundle/AddressingBundle/Tests/Matcher/ZoneMatcherTest/fixtures.yaml (hunk 4 above)
Comment (jakubtobiasz) [reply src/Sylius/Bundle/AddressingBundle/Tests/Matcher/ZoneMatcherTest/fixtures.yaml]: Tbh I don't see a need for that change. Let's wait for more voices.

File: src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Zone.orm.xml [hunk 6]
```diff
@@ -23,7 +23,7 @@
         <field name="type" column="type" type="string" length="8" />
         <field name="scope" column="scope" type="string" nullable="true"/>
 
-        <one-to-many field="members" target-entity="Sylius\Component\Addressing\Model\ZoneMemberInterface" mapped-by="belongsTo" orphan-removal="true">
+        <one-to-many field="members" target-entity="Sylius\Component\Addressing\Model\ZoneMemberInterface" mapped-by="belongsTo" orphan-removal="true" fetch="EAGER">
```
Comment (jakubtobiasz) [inline src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Zone.orm.xml]: Eager loading might be redundant here.

**Comment by jakubtobiasz** [comment]
TODO: Add an information about created repo in the UPGRADE file.

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 7]
```diff
@@ -0,0 +1,126 @@
...
+        return $query->getQuery()->getOneOrNullResult();
+    }
+
+    /** @return ZoneInterface[] */
+    public function findAllByAddress(AddressInterface $address, ?string $scope = null): array
+    {
+        return $this->createFindByAddressQueryBuilder($address, $scope)->getQuery()->getResult();
+    }
+
+    public function createFindByAddressQueryBuilder(AddressInterface $address, ?string $scope = null): QueryBuilder
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]:
```patch
--- createFindByAddressQueryBuilder
+++ createByAddressQueryBuilder
```

image
image

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 8]
```diff
@@ -0,0 +1,126 @@
...
+
+        return $query;
+    }
+
+    /**
+     * @param array<ZoneInterface> $members
+     *
+     * @return array<ZoneInterface>
+     */
+    public function findZonesByMembers(array $members, ?string $scope = null): array
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]: Generally speaking current entity/resource shouldn't be mentioned in method name. It's alright to do in rare cases like `findCart` in `OrderRepository`, but over here clarification doesn't add value.
 
```patch
--- findZonesByMembers
+++ findByMembers
```

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 9]
```diff
@@ -0,0 +1,126 @@
...
+    {
+        $zonesCodes = array_map(
+            fn (ZoneInterface $zone): string => $zone->getCode(),
+            $members,
+        );
+
+        $query = $this->createQueryBuilder('z')
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]: In what I've seen so far in sylius, repositories don't change default alias and uses `o`.

```patch
--- $this->createQueryBuilder('z')
+++ $this->createQueryBuilder('o')
```

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 10]
```diff
@@ -0,0 +1,126 @@
...
+            ->select('z', 'm')
+            ->leftJoin('z.members', 'm')
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]: Unless `members` is reserved word like `order`, keeping full property name is more readable and more in line with other sylius repositories.

```patch
--- ->leftJoin('z.members', 'm')
+++ ->leftJoin('z.members', 'members')
```

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 11]
```diff
@@ -0,0 +1,126 @@
...
+                ->andWhere($query->expr()->in('z.scope', ':scopes'))
+                ->setParameter('scopes', [$scope, Scope::ALL])
+            ;
+        }
+
+        $query
+            ->andWhere('z.type = :type')
+            ->andWhere($query->expr()->in('m.code', ':zones'))
+            ->setParameter('type', ZoneInterface::TYPE_ZONE)
+            ->setParameter('zones', $zonesCodes)
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php:116]: A minor nitpick, parameter name and variable name usually should match.

```patch
--- ->andWhere($query->expr()->in('m.code', ':zones'))
+++ ->andWhere($query->expr()->in('m.code', ':zonesCodes'))
```

```patch
--- ->setParameter('zones', $zonesCodes)
+++ ->setParameter('zonesCodes', $zonesCodes)
```

File: src/Sylius/Component/Addressing/spec/Matcher/ZoneMatcherSpec.php [hunk 12]
```diff
@@ -13,274 +13,65 @@
...
         AddressInterface $address,
-        ZoneMemberInterface $memberCountry,
-        ZoneInterface $zoneCountry,
+        ZoneInterface $zoneOne,
+        ZoneInterface $zoneTwo,
+        ZoneInterface $zoneThree,
     ): void {
-        $repository->findBy(['scope' => ['shipping', 'all']])->willReturn([$zoneCountry]);
+        $zoneOne->getScope()->willReturn('nato');
+        $zoneTwo->getScope()->willReturn('all');
```
Comment (diimpp) [inline src/Sylius/Component/Addressing/spec/Matcher/ZoneMatcherSpec.php]: I'm not suggesting this change, but noting, that it could be done.

```patch
--- $zoneTwo->getScope()->willReturn('all');
+++ $zoneTwo->getScope()->willReturn(Scope::ALL);
```

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 13]
```diff
@@ -0,0 +1,126 @@
...
+                END) AS HIDDEN sort_order')
+            ->orderBy('sort_order', 'ASC')
+            ->setMaxResults(1)
+        ;
+
+        return $query->getQuery()->getOneOrNullResult();
+    }
+
+    /** @return ZoneInterface[] */
+    public function findAllByAddress(AddressInterface $address, ?string $scope = null): array
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]: `findAll` and `findBy` is a bit of contradiction  :slightly_smiling_face:

Generally speaking `findBy` is expected to return collection unless `fineOneBy` is specified, so clarification is not needed.

```patch
--- findAllByAddress
+++ findByAddress
```

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 14]
```diff
@@ -0,0 +1,126 @@
...
+ */
+class ZoneRepository extends EntityRepository implements ZoneRepositoryInterface
+{
+    public function findOneByAddress(AddressInterface $address, ?string $scope = null): ?ZoneInterface
+    {
+        $query = $this->createFindByAddressQueryBuilder($address, $scope);
+
+        $query
+            ->addSelect('(CASE
+                    WHEN z.type = \'province\' THEN 1
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]: Can those values be converted to const usage? (`ZoneInterface::TYPE_PROVIENCE`, etc)

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 15]
```diff
@@ -0,0 +1,126 @@
...
+                    WHEN z.type = \'country\' THEN 2
+                    WHEN z.type = \'zone\' THEN 3
+                    ELSE 4
+                END) AS HIDDEN sort_order')
+            ->orderBy('sort_order', 'ASC')
+            ->setMaxResults(1)
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php:35]: I'm not convinced on this technique.

If query is constructed to return single result and there are more than one results, then we should get an `Exception` instead of returning first available result.

It's sort of a `LogicException` case, which should lead directly to a fix in the code by developer. (query itself or entity mappings).

Can we have more opinion on this @Sylius/core-team (Does it work to tag whole team? :D)

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 16]
```diff
@@ -0,0 +1,126 @@
...
+
+        $query = $this->createQueryBuilder('z')
+            ->select('z', 'm')
+            ->leftJoin('z.members', 'm')
+        ;
+
+        if (null !== $scope) {
+            $query
+                ->andWhere($query->expr()->in('z.scope', ':scopes'))
+                ->setParameter('scopes', [$scope, Scope::ALL])
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]: `$scope` might be `all` as well, which will result in `['all', 'all']` 

Possible solution is 
```patch
--- [$scope, Scope::ALL]
++ array_unique([$scope, Scope::ALL])
```

though maybe there are smarter one liners to do the same.

File: src/Sylius/Bundle/AddressingBundle/Tests/Matcher/ZoneMatcherTest/fixtures.yaml (hunk 4 above)
Comment (diimpp) [reply src/Sylius/Bundle/AddressingBundle/Tests/Matcher/ZoneMatcherTest/fixtures.yaml]: I do agree with Jan, scopes are for application level zones re-use, strings like `only_eu` or `nato` don't match intended use.

This tests/specs double as documentation and misuse will be confusing for new developers.

For example I've once added relation between Zone and PaymentMethods, so I've add new custom scope `payment`.

**Review by diimpp — CHANGES_REQUESTED** [review]

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php (hunk 15 above)
Comment (GSadee) [reply src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php:35]: Reproducing the previous logic with a query, this is what we want to achieve, to get one zone with the highest priority or just the first one when the priorities are the same, even if more than one zone matches the address. Perhaps it would be good to rename the method to make it clearer, sth like: `findOneWithHighestPriorityByAddress` or move the logic of choosing the one zone to the ZoneMatcher 🤔

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 17]
```diff
@@ -0,0 +1,126 @@
...
+    {
+        return $this->createFindByAddressQueryBuilder($address, $scope)->getQuery()->getResult();
+    }
+
+    public function createFindByAddressQueryBuilder(AddressInterface $address, ?string $scope = null): QueryBuilder
+    {
+        $query = $this->createQueryBuilder('z')
+            ->select('z', 'm')
+            ->leftJoin('z.members', 'm')
+        ;
```
Comment (GSadee) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]:
```suggestion
        $query = $this->createQueryBuilder('o')
            ->select('o', 'members')
            ->leftJoin('z.members', 'members')
        ;
```
🤔

File: src/Sylius/Bundle/AddressingBundle/Tests/Matcher/ZoneMatcherTest/fixtures.yaml (hunk 4 above)
Comment (GSadee) [reply src/Sylius/Bundle/AddressingBundle/Tests/Matcher/ZoneMatcherTest/fixtures.yaml]: I agree also that it will be clearer to use preexisting scopes, I do not see any benefit of using the custom scopes here

Comment (jakubtobiasz) [reply src/Sylius/Bundle/AddressingBundle/Tests/Matcher/ZoneMatcherTest/fixtures.yaml]: Done

**Review by NoResponseMate — DISMISSED** [review]

File: src/Sylius/Bundle/AddressingBundle/DependencyInjection/Configuration.php [hunk 18]
```diff
@@ -142,7 +143,7 @@ private function addResourcesSection(ArrayNodeDefinition $node): void
                                         ->scalarNode('model')->defaultValue(Zone::class)->cannotBeEmpty()->end()
                                         ->scalarNode('interface')->defaultValue(ZoneInterface::class)->cannotBeEmpty()->end()
                                         ->scalarNode('controller')->defaultValue(ResourceController::class)->cannotBeEmpty()->end()
-                                        ->scalarNode('repository')->cannotBeEmpty()->end()
+                                        ->scalarNode('repository')->defaultValue(ZoneRepository::class)->cannotBeEmpty()->end()
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/DependencyInjection/Configuration.php:146]: Sylius bundles never specify repository at `Configuration.php`

image

I'm questioning this for years, but never actually research how and why it works this way.

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php (hunk 15 above)
Comment (diimpp) [reply src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php:35]: @GSadee my question is more about this,

```php
$query
    ...
    ->setMaxResults(1);

return $query->getQuery()->getOneOrNullResult();
```

If somehow `$query` returns not a singular result, then we should get exception, but `>setMaxResults(1);` will return first out of multiple and we will never get an exception, even if query or data mappings no longer valid.

So I think this combo usage introduces possibility for a bug.

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 19]
```diff
@@ -0,0 +1,121 @@
...
+    {
+        $query = $this->createQueryBuilder('o')
+            ->select('o', 'members')
+            ->leftJoin('o.members', 'members')
+        ;
+
+        if (null !== $scope) {
+            $query
+                ->andWhere($query->expr()->in('o.scope', ':scopes'))
+                ->setParameter('scopes', [$scope, Scope::ALL])
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]:
```suggestion
                ->setParameter('scopes', array_unique([$scope, Scope::ALL]))
```

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 20]
```diff
@@ -0,0 +1,121 @@
...
+use Sylius\Component\Addressing\Repository\ZoneRepositoryInterface;
+
+/**
+ * @implements ZoneRepositoryInterface<ZoneInterface>
+ */
+class ZoneRepository extends EntityRepository implements ZoneRepositoryInterface
+{
+    public function findOneByAddressAndType(AddressInterface $address, string $type, ?string $scope = null): ?ZoneInterface
+    {
+        $query = $this->createByAddressQueryBuilder($address, $scope);
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]:
```suggestion
        $queryBuilder = $this->createByAddressQueryBuilder($address, $scope);
```

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 21]
```diff
@@ -0,0 +1,121 @@
...
+
+        $query
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]:
```suggestion
        $queryBuilder
```

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 22]
```diff
@@ -0,0 +1,121 @@
...
+            ->andWhere($query->expr()->eq('o.type', ':type'))
+            ->setParameter('type', $type)
+            ->setMaxResults(1)
+        ;
+
+        return $query->getQuery()->getOneOrNullResult();
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]:
```suggestion
        return $queryBuilder->getQuery()->getOneOrNullResult();
```

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 23]
```diff
@@ -0,0 +1,121 @@
...
+
+    /** @return ZoneInterface[] */
+    public function findByAddress(AddressInterface $address, ?string $scope = null): array
+    {
+        return $this->createByAddressQueryBuilder($address, $scope)->getQuery()->getResult();
+    }
+
+    public function createByAddressQueryBuilder(AddressInterface $address, ?string $scope = null): QueryBuilder
+    {
+        $query = $this->createQueryBuilder('o')
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]:
```suggestion
        $queryBuilder = $this->createQueryBuilder('o')
```

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 24]
```diff
@@ -0,0 +1,121 @@
...
+            ->select('o', 'members')
+            ->leftJoin('o.members', 'members')
+        ;
+
+        if (null !== $scope) {
+            $query
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]:
```suggestion
            $queryBuilder
```

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 25]
```diff
@@ -0,0 +1,121 @@
...
+
+        $orConditions = [];
+
+        if ($address->getCountryCode() !== null) {
+            $orConditions[] = $query->expr()->andX(
+                $query->expr()->eq('o.type', ':country'),
+                $query->expr()->eq('members.code', ':countryCode'),
+            );
+
+            $query->setParameter('country', ZoneInterface::TYPE_COUNTRY);
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]:
```suggestion
            $queryBuilder->setParameter('country', ZoneInterface::TYPE_COUNTRY);
```

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 26]
```diff
@@ -0,0 +1,121 @@
...
+            $query->setParameter('countryCode', $address->getCountryCode());
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]:
```suggestion
            $queryBuilder->setParameter('countryCode', $address->getCountryCode());
```

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 27]
```diff
@@ -0,0 +1,121 @@
...
+        if (null !== $scope) {
+            $query
+                ->andWhere($query->expr()->in('o.scope', ':scopes'))
+                ->setParameter('scopes', array_unique([$scope, Scope::ALL]))
+            ;
+        }
+
+        $query
+            ->andWhere('o.type = :type')
+            ->andWhere($query->expr()->in('members.code', ':zones'))
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]: "Direct" syntax is more common to see in sylius repos and IMO more readable.
Doc [examples](https://www.doctrine-project.org/projects/doctrine-orm/en/2.16/reference/query-builder.html) tend to use `expr()` only for `orX`/`andX` cases.

```suggestion
            ->andWhere('members.code IN :zones')
```

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 28]
```diff
@@ -0,0 +1,121 @@
...
+            ->setParameter('type', ZoneInterface::TYPE_ZONE)
+            ->setParameter('zones', $zonesCodes)
+        ;
+
+        return $query->getQuery()->getResult();
```
Comment (diimpp) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]:
```suggestion
        return $queryBuilder->getQuery()->getResult();
```

**Review by diimpp — DISMISSED** [review]
`Request changes` is mostly for

```patch
--- $query
+++ $queryBuilder`
```

which I just noticed. (I didn't mark them all)

P.S. Sorry for the "waves" reviews, I hope next one be the last one.

File: src/Sylius/Bundle/AddressingBundle/DependencyInjection/Configuration.php (hunk 18 above)
Comment (jakubtobiasz) [reply src/Sylius/Bundle/AddressingBundle/DependencyInjection/Configuration.php:146]: If there's a custom repository then it's declared in the config 
CleanShot 2023-09-25 at 10 44 58

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php (hunk 27 above)
Comment (jakubtobiasz) [reply src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php]: We use both across the Sylius, there's no standard, maybe that's an idea to standarize it 🤷🏼‍♂️

**Review by TheMilek — APPROVED** [review]

**Review by Rafikooo — APPROVED** [review]

**Review by Prometee — APPROVED** [review]

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thanks, Jacob! :tada:

File: src/Sylius/Bundle/AddressingBundle/DependencyInjection/Configuration.php (hunk 18 above)
Comment (diimpp) [reply src/Sylius/Bundle/AddressingBundle/DependencyInjection/Configuration.php:146]: It's not true for 1.12, every instance that you've found was introduced in 1.13.

I still don't know why it was done this way and how it even work, but custom repositories are not specified for Configuration for any of the bundle

File: src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php [hunk 29]
```diff
@@ -0,0 +1,121 @@
...
+use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;
+use Sylius\Component\Addressing\Model\AddressInterface;
+use Sylius\Component\Addressing\Model\Scope;
+use Sylius\Component\Addressing\Model\ZoneInterface;
+use Sylius\Component\Addressing\Repository\ZoneRepositoryInterface;
+
+/**
+ * @implements ZoneRepositoryInterface<ZoneInterface>
+ */
+class ZoneRepository extends EntityRepository implements ZoneRepositoryInterface
```
Comment (NoResponseMate) [inline src/Sylius/Bundle/AddressingBundle/Repository/ZoneRepository.php:26]: The fact that a new repository for an existing resource has shown up should be noted in the upgrade file. If someone has already created a custom one prior, the matcher will just fail.

File: src/Sylius/Component/Addressing/Matcher/ZoneMatcher.php [hunk 30]
```diff
@@ -16,98 +16,65 @@
...
+     * @param ZoneRepositoryInterface<ZoneInterface> $zoneRepository
      */
-    private const PRIORITIES = [
-        ZoneInterface::TYPE_PROVINCE,
-        ZoneInterface::TYPE_COUNTRY,
-        ZoneInterface::TYPE_ZONE,
-    ];
-
-    public function __construct(private RepositoryInterface $zoneRepository)
+    public function __construct(private ZoneRepositoryInterface $zoneRepository)
```
Comment (NoResponseMate) [inline src/Sylius/Component/Addressing/Matcher/ZoneMatcher.php:26]: Should also be noted in the upgrade file
