### PR TITLE
Replace `json_array` with `json` type as requested by the deprecation

### LINKED ISSUE #13211: Unknown column type "json_array"
**Sylius version affected**: 1.9, 1.10

**Description**  

During the migration, we have an error on unknown column type "json_array":

```
Error:  Migration Sylius\Bundle\CoreBundle\Migrations\Version20201130071338 failed during Execution. Error: "Unknown column type "json_array" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgotten to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information."

In Exception.php line 125:
                                                                               
  Unknown column type "json_array" requested. Any Doctrine type that you use   
  has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get  
   a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(  
  ). If this error occurs during database introspection then you might have f  
  orgotten to register all database types for a Doctrine Type. Use AbstractPl  
  atform#registerDoctrineTypeMapping() or have your custom types implement Ty  
  pe#getMappedDatabaseTypes(). If the type name is empty you might have a pro  
  blem with the cache or forgot some mapping information.  
```

**Steps to reproduce**  

Install/update your dependencies and run the `doctrine:migration:migrate` command

(your tests failed with the same error: https://github.com/Sylius/Sylius/pull/13210/checks?check_run_id=3922340759)

**Possible Solution**  

Add a conflict with doctrine/dbal v3, or add the "array_json" type if is unknown

### PR DESCRIPTION
**Pull request by Prometee**
| Q               | A
| --------------- | -----
| Branch?         | 1.9, 1.10
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #13211 
| License         | MIT

`doctrine/dbal:"^3"` remove `json_array` field type, previously it was deprecated in favor of `json` field type.

### CODE REVIEW

**Comment by vvasiloi** [comment]
@Prometee yes, better do it in a separate PR with either an explicit `require` constraint, or a `conflict`.
This will also prevent the plugins without a composer.lock file (which are the most if not all) from breaking.

**Comment by lchrusciel** [comment]
Hey Francis,

can you fix the build, remove dbal conflict and add one additional workflow to check if the new configuration works properly with dbal 2.10/2.9 and 3.0?

**Comment by Prometee** [comment]
Hi @lchrusciel,

I remove 1 commit about conflict and rebase the branch with the `1.9` one, but the build seems to fail because of another issue.
When you said "add one additional workflow", you mean GitHub Action workflow ? I can't see any existing workflow doing what you asked for. Can you enlighten me ?

**Comment by Prometee** [comment]
Waiting for this PR : https://github.com/Payum/Payum/pull/924 to be merged and released.

**Comment by maximehuran** [comment]
Hi, 

On a fresh Sylus installation with MySQL 8, I have a database schema is not in sync with the current mapping file.

Here is the generated migration with a diff : 

```php
<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220107153032 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sylius_gateway_config CHANGE config config JSON NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sylius_gateway_config CHANGE config config JSON CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci` COMMENT \'(DC2Type:json_array)\'');
    }
}
```

FYI I have added this on my `composer.json` : 
```json
    "conflict": {
        "doctrine/dbal": "^3"
    }
```

**Comment by vvasiloi** [comment]
@Prometee https://github.com/Payum/Payum/pull/924 was merged, Payum 1.7.0 released and all Sylius [builds fail](https://github.com/Sylius/Sylius/actions/runs/1664915145) now and all fresh installs as @maximehuran pointed out.
I prepared the changes for a PR, but then I remembered about this one.
We should probably combine them, WDYT?

**Review by stloyd — APPROVED** [review]

**Review by vvasiloi — APPROVED** [review]

**Comment by vvasiloi** [comment]
@lchrusciel the failed jobs don't seem to be related to the changes. Maybe we should restart the workflow.

File: src/Sylius/Bundle/CoreBundle/Migrations/Version20211018130725.php [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+
+final class Version20211018130725 extends AbstractMigration
+{
+    public function getDescription(): string
+    {
+        return 'Change json_array(deprecated) to json type';
+    }
+
+    public function up(Schema $schema): void
+    {
```
Comment (lchrusciel) [inline src/Sylius/Bundle/CoreBundle/Migrations/Version20211018130725.php:27]:
```suggestion
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');
    
```

File: src/Sylius/Bundle/CoreBundle/Migrations/Version20211018130725.php [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+        $this->addSql('ALTER TABLE sylius_payment CHANGE details details JSON NOT NULL');
+        $this->addSql('ALTER TABLE sylius_product_attribute_value CHANGE json_value json_value JSON DEFAULT NULL');
+        $this->addSql('ALTER TABLE sylius_gateway_config CHANGE config config JSON NOT NULL');
+    }
+
+    public function down(Schema $schema): void
+    {
```
Comment (lchrusciel) [inline src/Sylius/Bundle/CoreBundle/Migrations/Version20211018130725.php:34]:
```suggestion
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');
        
```

**Review by lchrusciel — APPROVED** [review]
I've just restarted them.

Probably we should also allow dbal v3 with these changes. But that may be done in separate PR. Still, we need to have green build and composer is making some problems from what I see

File: src/Sylius/Bundle/CoreBundle/Migrations/Version20211018130725.php (hunk 1 above)
Comment (Prometee) [reply src/Sylius/Bundle/CoreBundle/Migrations/Version20211018130725.php:27]: @lchrusciel on it right now !

**Comment by Prometee** [comment]
@lchrusciel yes I already retest it on my local env and all BeHat JS are green. I guess their is some weird network issue happening here. Restarting the build can help if it fails again...

**Comment by vvasiloi** [comment]
@lchrusciel all green.

**Comment by lchrusciel** [comment]
TBH, I should just mention all of you. So thank you all Francis, Joseph, Victor, Manuele, Michael and Maxime for your work, comments, spotting problems etc :)

**Comment by vvasiloi** [comment]
@lchrusciel this should go to 1.11 and master too.

**Comment by lchrusciel** [comment]
I have some issues with upmerging atm. I've contacted @Zales0123 & @GSadee to do it, they should do it tomorrow morning. Also, we should release a new version of Sylius
