### PR TITLE
#9699 Fix for viewing products when they belong to a taxon and to one…

### LINKED ISSUE #9699: Product pagination bug
**Sylius version affected**: every

**Description**  
https://demo.sylius.com/en_US/taxons/t-shirts So we request 9 products per page, but only 6 are visible, the others are on the second page. My guess is this should not happen.

**Steps to reproduce**  
Visit https://demo.sylius.com/en_US/taxons/t-shirts

**Possible Solution**  
Dunno.

### PR DESCRIPTION
**Pull request by laurent35240**
… of children taxon

| Q               | A
| --------------- | -----
| Branch?         | 1.2
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #9699 
| License         | MIT

### CODE REVIEW

**Comment by lchrusciel** [comment]
Yup. I prefer to ensure, that we are not adding any regression. However, there should be some tests for that anyway.

File: src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php [hunk 1]
```diff
@@ -70,6 +70,7 @@ public function createShopListQueryBuilder(
         array $sorting = []
     ): QueryBuilder {
         $queryBuilder = $this->createQueryBuilder('o')
+            ->distinct()
```
Comment (pamil) [inline src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php]: It's so simple when you see it, but couldn't figure it out when I was trying to solve this issue, good job 🎉

**Comment by pamil** [comment]
Thank you, Laurent! :tada:
