### PR TITLE
[Shop] Promotion integrity checker fix

### LINKED ISSUE #9940: Two promotions, where one invalidates the other, makes checkout impossible
**Sylius version affected**: 1.2.10

**Description**  
If you have two promotions that both apply for a cart, but when both apply, checkout becomes impossible if one changes the order value as such to invalidate the other.

**Steps to reproduce**  

1. Create a Christmas promotion (this is a demo one)
- no usage limit
- Priority 0
- no date restriction
- configuration
- - One rule
- - - Cart Quantity = 0
- - One action
- - - Order Percentage discount = 26
2. Create a New Years promotion (this is also a demo one)
- usage limit = 10
- priority 2
- dates to cover the testing period
- configuration
- - One rule
- - - item total = $100
- - One action
- - - order fixed discount = 10
3. Go to the front-end
4. Add 1 $100 item to the basket (20% tax item)
5. Proceed through the checkout to the complete page, and confirm both promotions have applied bringing the total down to $79.92 (free shipping)
6. Click place order
7. You should see an error of "Error. You are no longer eligible for this promotion New Year."

**Possible Solution**  
Not a clue at the moment

### LINKED ISSUE #10282: Removing promotion adjustment never recalculate the tax on the order item unit
**Sylius version affected**: 1.4.1

**Steps to reproduce** 

Into the cart : 1 article at $149 (without taxes)
Applied promotion : 50% off (order_promotion)
Tax 14,975% (Canadian tax)
Total : $85.66

When I want to complete the order checkout I have this error :
`Your order total has been changed, check your order information and confirm it again.`

**Description**  

This error occurred because `OrderPromotionIntegrityChecker` remove the promotion to check it, but the tax adjustment on the `OrderItemUnit` is never updated when the promotion adjustment is removed.

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A
| --------------- | -----
| Branch?         | 1.4
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | Fixes #10282, #9940 
| License         | MIT

Big thanks to @vvasiloi, @Prometee, and @oallain for providing detailed bug report, behat scenario and possible issues! 

It appears that by rebound I fixed #9940 as well. Described in https://github.com/Sylius/Sylius/pull/10603/commits/5e41cedd7842f99cdaa3a14fb5f473f637e57e5e

### CODE REVIEW

**Comment by Prometee** [comment]
Wow ! Many thanks to you too making this fix !

File: src/Sylius/Bundle/ShopBundle/EventListener/OrderPromotionIntegrityChecker.php [hunk 1]
```diff
@@ -61,24 +51,21 @@ public function check(ResourceControllerEvent $event): void
...
-
-        $promotions = $order->getPromotions()->toArray();
+        $previouslyAppliedPromotionsCodeToNameMap = $this->createPromotionCodeToNameMap($order);
 
-        if ($this->promotionApplicator !== null) {
-            foreach ($promotions as $promotion) {
-                $this->promotionApplicator->revert($order, $promotion);
-                $order->removePromotion($promotion);
-            }
+        if ($this->orderProcessor !== null) {
```
Comment (vvasiloi) [inline src/Sylius/Bundle/ShopBundle/EventListener/OrderPromotionIntegrityChecker.php]: It is not optional in the constructor and without it the whole thing won't work.

File: src/Sylius/Bundle/ShopBundle/EventListener/OrderPromotionIntegrityChecker.php [hunk 2]
```diff
@@ -61,24 +51,21 @@ public function check(ResourceControllerEvent $event): void
 
         Assert::isInstanceOf($order, OrderInterface::class);
 
-        // we create a new promotion collection and remove them from cart
-        // so we can verify with original conditions (without the price being applied before check)
-
-        $promotions = $order->getPromotions()->toArray();
+        $previouslyAppliedPromotionsCodeToNameMap = $this->createPromotionCodeToNameMap($order);
```
Comment (vvasiloi) [inline src/Sylius/Bundle/ShopBundle/EventListener/OrderPromotionIntegrityChecker.php]: Did you think about just cloning order's promotion collection instead?
Something like this should work: `$previousPromotions = new ArrayCollection($order->getPromotions()->toArray());`
And after processing just loop through `$order->getPromotions()` and check if `$previousPromotions->contains($promotion)`.
Not necessarily better, just a matter of taste I guess.

File: src/Sylius/Bundle/ShopBundle/EventListener/OrderPromotionIntegrityChecker.php [hunk 3]
```diff
@@ -87,10 +74,22 @@ public function check(ResourceControllerEvent $event): void
 
                 break;
```
Comment (vvasiloi) [inline src/Sylius/Bundle/ShopBundle/EventListener/OrderPromotionIntegrityChecker.php]: Have someone though about what will happen when there are several promotions that are no applicable? 😄
My guess is that it will remove all, but notify only about the first.

**Comment by vvasiloi** [comment]
@lchrusciel good solution! 🎉 Left a few comments, maybe you find something worth considering.

File: features/checkout/order_promotion/order_promotion_integrity_validation.feature [hunk 4]
```diff
@@ -23,6 +23,16 @@ Feature: Order promotions integrity
         Then I should be informed that this promotion is no longer applied
         And I should not see the thank you page
 
+    @ui
+    Scenario: Basket with several promotions is able to checkout
```
Comment (GSadee) [inline features/checkout/order_promotion/order_promotion_integrity_validation.feature]:
```suggestion
    Scenario: Being able to completing checkout with several promotions
```

File: features/checkout/order_promotion/order_promotion_integrity_validation.feature [hunk 5]
```diff
@@ -37,3 +47,13 @@ Feature: Order promotions integrity
...
+
+    @ui
+    Scenario: Excluded tax are not taken into account into promotion integrity check
+        Given the store has "VAT" tax rate of 20% for "Clothes" within the "US" zone
+        And this product belongs to "Clothes" tax category
+        And this promotion gives "50%" discount to every order
+        And I added product "PHP T-Shirt" to the cart
+        When I proceed selecting "Offline" payment method
+        And I confirm my order
+        And I should see the thank you page
```
Comment (GSadee) [inline features/checkout/order_promotion/order_promotion_integrity_validation.feature]:
```suggestion
        Then I should see the thank you page
```

File: src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutCompleteContext.php [hunk 6]
```diff
@@ -186,9 +186,9 @@ public function shouldBeAppliedToMyOrderShipping($promotionName)
     /**
      * @Given my tax total should be :taxTotal
      */
-    public function myTaxTotalShouldBe($taxTotal)
+    public function myTaxTotalShouldBe(string $taxTotal): void
     {
-        Assert::true($this->completePage->hasTaxTotal($taxTotal));
+        Assert::same(str_replace('Tax total: ', '', $this->completePage->getTaxTotal()), $taxTotal);
```
Comment (GSadee) [inline src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutCompleteContext.php]: IMO this `str_replace()` should be in `getTaxTotal()` method

File: src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php [hunk 7]
```diff
@@ -180,9 +180,9 @@ public function hasShippingPromotion($promotionName)
     /**
      * {@inheritdoc}
      */
```
Comment (GSadee) [inline src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php]: Docblock could be removed if you are changing this method

File: src/Sylius/Bundle/ShopBundle/EventListener/OrderPromotionIntegrityChecker.php [hunk 8]
```diff
@@ -61,36 +59,26 @@ public function check(ResourceControllerEvent $event): void
...
 
-        if ($this->promotionApplicator !== null) {
-            foreach ($promotions as $promotion) {
-                $this->promotionApplicator->revert($order, $promotion);
-                $order->removePromotion($promotion);
-            }
-        }
+        /** @var PromotionInterface $previousPromotion */
+        foreach ($previousPromotions as $previousPromotion) {
+            if (!$order->getPromotions()->contains($previousPromotion)) {
```
Comment (GSadee) [inline src/Sylius/Bundle/ShopBundle/EventListener/OrderPromotionIntegrityChecker.php]: Unnecessary blank line

**Comment by pamil** [comment]
Thank you, Łukasz! :1st_place_medal:
