### PR TITLE
Fix error with being unable to add product review while being logged in using remember me

### LINKED ISSUE #14898: Incorrect use of IS_AUTHENTICATED_FULLY with "remember me" functionality
**Description**  
A few places across multiple bundles check against `IS_AUTHENTICATED_FULLY` (user went through form log in in this session) expecting the weaker behaviour of `IS_AUTHENTICATED_REMEMBERED` (any logged in user, also through "remember me"). [Reference @SymfonyDocs](https://symfony.com/doc/6.3/security.html#checking-to-see-if-a-user-is-logged-in).

Since Sylius offers "remember me" functionality, it may cause unexpedted results.

One of them is described in #9430.

**Steps to reproduce**  
1. Log in shop user with the "remember me" enabled
2. Access Sylius frontend using Remember me functionality
3. Go to product review form

**Possible Solution**  
For #9430, the check can be changed to `is_granted('IS_AUTHENTICATED')` or `is_granted('IS_AUTHENTICATED_REMEMBERED')`. Alternatively `{% if form.author is defined %}` will also solve the issue, since adding the sub form is already dependant on having a logged in user.

All other checks should be reviewed case-by-case, but I believe it's safe to assume that almost anything in a template can be safely replaced with `is_granted('IS_AUTHENTICATED')` (or `IS_AUTHENTICATED_REMEMBERED`)

### PR DESCRIPTION
**Pull request by TheMilek**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12                   |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                      |
| BC breaks?      | no                                                      |
| Deprecations?   | no  |
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/14898 and https://github.com/Sylius/Sylius/issues/9430                      |
| License         | MIT                                                          |

As being said [here](https://github.com/Sylius/Sylius/issues/14898) we were checking access against `IS_AUTHENTICATED_FULLY` while creating product review and it leads to a problem, that prevents us from creating review while using remember me functionality:

image

By changing it to `IS_AUTHENTICATED_REMEMBERED` resolves the bug

### CODE REVIEW

**Review by jakubtobiasz — DISMISSED** [review]

File: src/Sylius/Behat/Context/Setup/ShopSecurityContext.php [hunk 1]
```diff
@@ -67,4 +67,24 @@ public function iAmLoggedInCustomer(?string $fullName = null): void
 
         $this->sharedStorage->set('user', $user);
     }
+
+    /**
+     * @Given I am a logged in customer by using remember me option
+     */
+    public function iAmLoggedInCustomerByUsingRememberMeOption(?string $fullName = null): void
```
Comment (NoResponseMate) [inline src/Sylius/Behat/Context/Setup/ShopSecurityContext.php]:
```suggestion
    /**
     * @Given I am a logged in customer by using remember me option
     */
    public function iAmLoggedInCustomerByUsingRememberMeOption(): void
```
It is not used right now, there is no point in adding it in advance.

**Review by NoResponseMate — DISMISSED** [review]

**Review by jakubtobiasz — DISMISSED** [review]

**Review by jakubtobiasz — APPROVED** [review]

**Comment by jakubtobiasz** [comment]
Thank you, @TheMilek!
