### PR TITLE
[FIX] Fixing action clear cart after added address on shipping step

### LINKED ISSUE #18421: Clear cart fails on checkout page
### Sylius version(s) affected

2.1.6

### Description

`Doctrine\ORM\EntityNotFoundException:
Entity of type 'App\Entity\Addressing\Address' for IDs id(1572) was not found`
occurs when trying to clear cart from the checkout page (https://demo.sylius.com/en_US/cart/) when address is already set.

Image

https://demo.sylius.com/en_US/_components/sylius_shop:cart:form/clearCart returns HTTP 500

### How to reproduce

1. Go to the demo shop: https://demo.sylius.com/ 
2. Add any product to the cart.
3. Go to checkout and enter the address (https://demo.sylius.com/en_US/checkout/address), then click next.
4. Go back to the cart checkout page (https://demo.sylius.com/en_US/cart/).
5. Click `Clear cart`.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by michalkaczmarek-bitbag**
| Q               | A
|-----------------|-----
| Branch?         | 2.1 
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #18421 
| License         | MIT

## Summary by CodeRabbit

* **Bug Fixes**
  * Clearing the cart now fully resets the cart and its form, removing lingering validation state and previously entered data; a fresh cart is created automatically after clearing for more reliable checkout behavior.

* **Tests**
  * Added a UI scenario for clearing the cart after entering a billing address and updated UI/API test suites to include checkout address setup.

### CODE REVIEW

File: src/Sylius/Bundle/ShopBundle/Twig/Component/Cart/FormComponent.php
Comment (Rafikooo) [inline src/Sylius/Bundle/ShopBundle/Twig/Component/Cart/FormComponent.php:1]: Missing tests — you could add something like:
```gherkin
  @ui @javascript
  Scenario: Clearing cart after adding an address in checkout
      Given I added the product "T-Shirt banana" to the cart
      And I am at the checkout addressing step
      And I specified the billing address as "..."
      When I go to my cart summary page
      And I clear my cart
      Then my cart should be cleared
      And I should not see any errors
```
However, I’d prefer a unit test to avoid adding new JS Behat scenarios.

File: features/shop/cart/shopping_cart/clearing_cart.feature [hunk 1]
```diff
@@ -15,3 +15,11 @@ Feature: Clearing cart
         When I check the details of my cart
         And I clear my cart
         Then my cart should be cleared
+
+    @ui @javascript
```
Comment (Rafikooo) [inline features/shop/cart/shopping_cart/clearing_cart.feature]:
```suggestion
    @api @ui @javascript
```

**Review by Rafikooo — APPROVED** [review]
