### PR TITLE
Fix  #17865 issue

### LINKED ISSUE #17865: [2.0] Call to a member function getCode() on null
### Sylius version(s) affected

2.0.6

### Description

The `PaymentMethodChangeEventListener` generate an error if the new payment method is null.

This case is very specific and normally not possible.

### How to reproduce

Make a order with a paiement method.

Change the paiement method to `null`

### Possible Solution

Check if the older and newer paiment method is not `null` before call `cancelPaymentRequests` in `Sylius\Bundle\PaymentBundle\EventListener\PaymentMethodChangeEventListener` line 41.

```diff
- if ($oldMethod !== $newMethod) {
+ if ($oldMethod !== null && $newMethod !== null && $oldMethod !== $newMethod) {
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by macintoshplus**
| Q               | A
|-----------------|-----
| Branch?         | 2.0
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #17865
| License         | MIT

### CODE REVIEW

File: src/Sylius/Bundle/PaymentBundle/EventListener/PaymentMethodChangeEventListener.php [hunk 1]
```diff
@@ -38,7 +38,7 @@ public function postUpdate(PostUpdateEventArgs $args): void
         if (array_key_exists('method', $changeSet)) {
             [$oldMethod, $newMethod] = $changeSet['method'];
 
-            if ($oldMethod !== $newMethod) {
+            if ($oldMethod !== null && $newMethod !== null && $oldMethod !== $newMethod) {
                 $this->paymentRequestCanceller->cancelPaymentRequests($entity->getId(), $newMethod->getCode());
             }
         }
```
Comment (Prometee) [inline src/Sylius/Bundle/PaymentBundle/EventListener/PaymentMethodChangeEventListener.php]: Is it possible to refactor those lines to use "Return Early Pattern", it will be more readable and understandable?

**Review by Prometee — CHANGES_REQUESTED** [review]

**Review by mpysiak — APPROVED** [review]

**Review by NoResponseMate — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you @macintoshplus! 🎉
