### PR TITLE
Handle Symfony 8+ strip region in RequestHeaderBasedLocaleContext

### LINKED ISSUE #18928: Locale code "en_150" is not handled correctly
### Sylius version(s) affected

2.2.3

### Description

In class `RequestHeaderBasedLocaleContext` we call the `\Symfony\Component\HttpFoundation\Request::getPreferredLanguage` method to retrieve the "best locale" given the app available locales. But from Symfony 8 ([commit here](https://github.com/symfony/http-foundation/commit/664fd60c7bb086df94d00058ebb4ba2eb8b5abf1)), the getPreferredLanguage returns only the "language" part of the locale ("en" in our case) for locales that uses "macro regions" like en_150.

I think RequestHeaderBasedLocaleContext should check if the returned language matches the available one or match the first one that "starts with" that language

### How to reproduce

There a lot of ways. The first one that come to mind: use "en_150" and "it_IT" locales and defined some route that has different paths for these two locales. It will generate a 404 for the en_150 one.

### Possible Solution

I think RequestHeaderBasedLocaleContext should check if the returned language matches the available one or match the first one that "starts with" that language

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by marekrzytki**
| Q               | A
|-----------------|-----
| Branch?         | 2.2
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/18928
| License         | MIT

## Summary by CodeRabbit

* **Bug Fixes**
  * Enhanced locale resolution with a fallback mechanism that performs prefix matching against available locales, providing more reliable language code detection when the primary negotiation method is unsuccessful.

### CODE REVIEW

File: src/Sylius/Bundle/LocaleBundle/tests/Context/RequestHeaderBasedLocaleContextTest.php [hunk 1]
```diff
@@ -145,4 +165,58 @@ public function testResolvesLocaleFromMainRequestPreferredLanguageInLowerCasedLa
...
+        $this->localeProvider->expects(self::once())
+            ->method('getDefaultLocaleCode')
+            ->willReturn('en_150');
+
+        $this->localeProvider->expects(self::once())
+            ->method('getAvailableLocalesCodes')
+            ->willReturn(['en_150']);
+
+        self::assertSame('en_150', $this->requestHeaderBasedLocaleContext->getLocaleCode());
+    }
```
Comment (NoResponseMate) [inline src/Sylius/Bundle/LocaleBundle/tests/Context/RequestHeaderBasedLocaleContextTest.php]: Could you maybe refactor all of the tests here (the ones actually checking resolving logic) to use a data provider w/ [acceptLanguage, default, availableLocales, result] as parameters?
Current tests are basically the same, and having the specifics yielded would simplify checking lots of cases.

File: src/Sylius/Bundle/LocaleBundle/Context/RequestHeaderBasedLocaleContext.php [hunk 2]
```diff
@@ -61,7 +61,26 @@ public function getLocaleCode(): string
...
+        if (in_array($bestLocaleCode, $this->availableLocalesCodes, strict: true)) {
+            return $bestLocaleCode;
+        }
+
+        // Symfony 8+ strips numeric region subtags (UN M.49, e.g. "150" in "en_150"), returning only the
+        // language part. Fall back to the first available locale that starts with that language prefix.
+        $localesMatchingLanguagePrefix = array_values(array_filter(
+            $this->availableLocalesCodes,
+            static fn (string $code): bool => str_starts_with($code, $bestLocaleCode . '_') ||
+                str_starts_with($code, $bestLocaleCode . '-'),
```
Comment (NoResponseMate) [inline src/Sylius/Bundle/LocaleBundle/Context/RequestHeaderBasedLocaleContext.php]: Can this part even occur? Pretty sure we only use the floor delimiter for locales

File: src/Sylius/Bundle/LocaleBundle/tests/Context/RequestHeaderBasedLocaleContextTest.php [hunk 3]
```diff
@@ -54,95 +54,113 @@ public function testThrowsLocaleNotFoundExceptionIfMainRequestIsNotFound(): void
         $this->requestHeaderBasedLocaleContext->getLocaleCode();
     }
 
-    public function testThrowsLocaleNotFoundExceptionIfLocaleFromMainRequestPreferredLanguageCannotBeResolved(): void
+    /**
+     * @dataProvider provideResolvingCases
```
Comment (NoResponseMate) [inline src/Sylius/Bundle/LocaleBundle/tests/Context/RequestHeaderBasedLocaleContextTest.php]: Would be nice to have these as attributes instead of annotations

**Review by NoResponseMate — DISMISSED** [review]

**Review by TheMilek — DISMISSED** [review]

File: src/Sylius/Bundle/LocaleBundle/tests/Context/RequestHeaderBasedLocaleContextTest.php (hunk 3 above)
Comment (marekrzytki) [reply src/Sylius/Bundle/LocaleBundle/tests/Context/RequestHeaderBasedLocaleContextTest.php]: Fixed

**Comment by TheMilek** [comment]
lets change the base branch to 2.3, as 2.2 will not support symfony 8 anyway 🤔

**Review by TheMilek — APPROVED** [review]
