### PR TITLE
Fix for #8759 (ability to specify custom fixture suite during install)

### LINKED ISSUE #8759: Ability to specify fixture suite during sylius:install
When we have some custom fixture suite - steps to install Sylius become not user-friendly. 
We should:

1. Run `php bin/console sylius:install`
2. Answer 'Y' for 'Would you like to reset it?
3. Answer 'N' for 'Loading sample data for environment dev. Continue?
4. Type dummy E-mail and password (they will be rewrited during loading fixtures - next step)
5. Load our custom fixture suite (`php bin/console sylius:fixtures:load CUSTOM_SUITE_NAME --no-interaction`)

Note, that we can't use `--no-interaction` at first step as far as in that case `default` fixture suite will be executed and (in case we have some entities customized) it will fail (like `Some custom fields can't be null`) during creation. Thats why we should perform so many steps and its not good.

May I perform pull request?

### PR DESCRIPTION
**Pull request by igormukhingmailcom**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | yes
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #8759
| License         | MIT

### CODE REVIEW

**Comment by igormukhingmailcom** [comment]
Guys, I also suggest to not ask confirmation question if suite was specified (at https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Command/InstallSampleDataCommand.php#L55) like this:

```php
if (!$questionHelper->ask(
    $input, 
    $output, 
    new ConfirmationQuestion(
        'Continue? (y/N) ', 
        null !== $suite // <------------- Question will be answered YES by default in no interaction mode if suite was provided
    )
)) {
```

This not breaks BC as far as new option/`$suite` is `null` by default (so `null !== $suite ` is `false` by default as it was before), but allows us to run install commands with `--fixture-suite=custom --no-interaction` options and load fixtures automatically (now, if you run install with `--no-interaction` option - sample data loading step will be skipped).

**Comment by igormukhingmailcom** [comment]
Hi, @lchrusciel
I've fixed build fail

File: src/Sylius/Bundle/CoreBundle/Command/InstallSampleDataCommand.php [hunk 1]
```diff
@@ -68,8 +72,13 @@ protected function execute(InputInterface $input, OutputInterface $output): ?int
             return 1;
         }
 
+        $parameters = ['--no-interaction' => true];
+        if ($suite) {
+            $parameters['suite'] = $suite;
```
Comment (lchrusciel) [inline src/Sylius/Bundle/CoreBundle/Command/InstallSampleDataCommand.php]: Can you make explict comparition here? What do we accept as a proper value? Not empty string?

File: src/Sylius/Bundle/CoreBundle/Command/InstallDatabaseCommand.php [hunk 2]
```diff
@@ -54,6 +58,10 @@ protected function execute(InputInterface $input, OutputInterface $output): void
         $this->runCommands($commands, $output);
         $outputStyle->newLine();
 
-        $this->commandExecutor->runCommand('sylius:install:sample-data', [], $output);
+        $parameters = [];
+        if ($suite) {
```
Comment (lchrusciel) [inline src/Sylius/Bundle/CoreBundle/Command/InstallDatabaseCommand.php]: Can you make explict comparition here? What do we accept as a proper value? Not empty string?

File: src/Sylius/Bundle/CoreBundle/Command/InstallSampleDataCommand.php [hunk 3]
```diff
@@ -43,16 +45,18 @@ protected function execute(InputInterface $input, OutputInterface $output): ?int
...
+        $suite = $input->getOption('fixture-suite');
 
         $outputStyle = new SymfonyStyle($input, $output);
         $outputStyle->newLine();
         $outputStyle->writeln(sprintf(
-            'Loading sample data for environment <info>%s</info>.',
-            $this->getEnvironment()
+            'Loading sample data for environment <info>%s</info> from suite <info>%s</info>.',
+            $this->getEnvironment(),
+            $suite
```
Comment (Zales0123) [inline src/Sylius/Bundle/CoreBundle/Command/InstallSampleDataCommand.php]: We should probably have some default value here? `$suite ?? 'default'`?

File: src/Sylius/Bundle/CoreBundle/Command/InstallDatabaseCommand.php [hunk 4]
```diff
@@ -54,6 +58,10 @@ protected function execute(InputInterface $input, OutputInterface $output): void
         $this->runCommands($commands, $output);
         $outputStyle->newLine();
 
-        $this->commandExecutor->runCommand('sylius:install:sample-data', [], $output);
+        $parameters = [];
+        if (null !== $suite) {
```
Comment (Zales0123) [inline src/Sylius/Bundle/CoreBundle/Command/InstallDatabaseCommand.php]: Do we need to check this? If we pass just `['--fixture-suite' => $suite]` even if suite is null it should still work?

File: src/Sylius/Bundle/CoreBundle/Command/InstallSampleDataCommand.php (hunk 3 above)
Comment (igormukhingmailcom) [reply src/Sylius/Bundle/CoreBundle/Command/InstallSampleDataCommand.php]: You're right

File: src/Sylius/Bundle/CoreBundle/Command/InstallDatabaseCommand.php (hunk 4 above)
Comment (igormukhingmailcom) [reply src/Sylius/Bundle/CoreBundle/Command/InstallDatabaseCommand.php]: Yes, we need it

**Comment by igormukhingmailcom** [comment]
Hi, @Zales0123 . 
Any change to merge this?

**Comment by mamazu** [comment]
That would indeed be a nice feature to have.

**Comment by igormukhingmailcom** [comment]
@Zales0123 @lchrusciel Could any of you review please?

File: src/Sylius/Bundle/CoreBundle/Command/InstallSampleDataCommand.php [hunk 5]
```diff
@@ -33,6 +34,7 @@ protected function configure(): void
 The <info>%command.name%</info> command loads the sample data for Sylius.
 EOT
             )
+            ->addOption('fixture-suite', 's', InputOption::VALUE_OPTIONAL, 'Load specified fixture suite during install', null)
```
Comment (lchrusciel) [inline src/Sylius/Bundle/CoreBundle/Command/InstallSampleDataCommand.php]: Won't it be better to have `default` as a default value instead of null? We will reduce one if statement `$suite ?? 'default'`, while `null !== $suite` could be changed to `'default' !== $suite`. 

This will mean, that we cannot load not interactively default fixtures. However, I'm not convinced about this change anyway. The feature is useful, but consequences may be huge, so I would not load it.

**Comment by lchrusciel** [comment]
I'm ok with the changes, thanks a lot for the contribution 👍

**Comment by Zales0123** [comment]
Thank you, Igor! 🏅
