### PR TITLE
Fix #7093 #7094 #7096

### LINKED ISSUE #7093: [SyliusUserBundle] "The helper "dialog" is not defined."
Hi,

I downloaded a fresh dev-master of sylius-standard and I wanted to play with the Sylius API.
So, after creating my first admin user account, when interacting with `sylius:install`, I wanted to call `sylius:user:promote` to add a `ROLE_API_ACCESS` to my account.

Then I got the following exception:
```
  [Symfony\Component\Console\Exception\InvalidArgumentException]
  The helper "dialog" is not defined.
```

Indeed the code relies on `$this->getHelper('dialog')` to interact with the human behind the terminal, which is deprecated since Symfony 2.5 and removed since Symfony 3.0:
http://symfony.com/doc/current/components/console/helpers/dialoghelper.html

A minor refactoring should be done to use the new Question helper.

### LINKED ISSUE #7094: [SyliusUserBundle] Promoting / Demoting only work on "shop" users
After fixing #7093 on my side, I wanted to promote a `ROLE_API_ACCESS` to my user account, in order to use the API.

Then the console told me there was no account registered with the email address I entered.

This is because the promote / demote actions only rely on `sylius.repository.shop_user`, although my account is an admin account.

I suggest asking the human to specify which type of account it should retrieve before applying any modification.

### PR DESCRIPTION
**Pull request by bpolaszek**
New PR from #7096.

| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | yes |
| BC breaks?      | maybe* |
| Related tickets | fixes #7093 #7094  |
| License         | MIT |

## Promoting / Demoting user roles
[SyliusUserBundle] Refactored question helper - fixes #7093 
[SyliusUserBundle] Added a new interaction to specify the user type - fixes #7094 

## * BC breaks 
* I don't know if this can be called a "BC break" since the code was already broken since Symfony 3.0, and the patch should work on Symfony 2.5+.
* The protected function `Sylius\Bundle\UserBundle\Command\AbstractRoleCommand::executeRoleCommand` has a new 1st argument: `InputInterface`. This indeed leads to a BC break to possible custom inheritances of `Sylius\Bundle\UserBundle\Command\AbstractRoleCommand`, but the probability to drink a beer with an alien on the Eiffel Tower one day is more important than facing that kind of issue, IMHO.

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
Please fix CS, you can use `php-cs-fixer` for that with [these options](https://github.com/Sylius/Sylius/blob/master/etc/phpcs/common.php#L26) (I hope they are up to date).

**Comment by bpolaszek** [comment]
Done.

File: src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php [hunk 1]
```diff
@@ -28,27 +30,47 @@
...
     {
+
+        // User types configured in the Bundle
+        $availableUserTypes = $this->getAvailableUserTypes();
+        if (empty($availableUserTypes)) {
+            throw new \Exception(sprintf('At least one user type should implement %s', UserInterface::class));
+        }
+
+        if (!$input->getOption('user-type')) {
+
```
Comment (lchrusciel) [inline src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php]: redundant blank line

File: src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php [hunk 2]
```diff
@@ -28,27 +30,47 @@
...
+            // Do not ask if there's only 1 user type configured
+            if (count($availableUserTypes) === 1) {
+                $input->setOption('user-type', $availableUserTypes[0]);
+            } else {
+                $question = new ChoiceQuestion('Please enter the user type:', $availableUserTypes, 1);
+                $question->setErrorMessage('Choice %s is invalid.');
+                $userType = $this->getHelper('question')->ask($input, $output, $question);
+                $input->setOption('user-type', $userType);
```
Comment (lchrusciel) [inline src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php]: Instead of setting an option we should just have a variable work on variable

File: src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php [hunk 3]
```diff
@@ -28,27 +30,47 @@
...
-
-                    return $email;
+            $question = new Question('Please enter an email:');
+            $question->setValidator(function ($email) {
+                if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
+                    throw new \RuntimeException("The email you entered is invalid.");
                 }
-            );
-
+                return $email;
```
Comment (lchrusciel) [inline src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php]: Missing blank line

File: src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php [hunk 4]
```diff
@@ -28,27 +30,47 @@
...
-            $roles = $this->getHelper('dialog')->ask(
-                $output,
-                'Please enter user\'s roles (separated by space):'
-            );
+            $question = new Question('Please enter user\'s roles (separated by space):');
+            $question->setValidator(function ($roles) {
+                if (strlen($roles) < 1) {
+                    throw new \RuntimeException("The value cannot be blank.");
+                }
+                return $roles;
```
Comment (lchrusciel) [inline src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php]: Missing blank line

File: src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php [hunk 5]
```diff
@@ -64,26 +86,29 @@ protected function execute(InputInterface $input, OutputInterface $output)
...
+     * @throws \InvalidArgumentException
      */
-    protected function findUserByEmail($email)
+    protected function findUserByEmail($email, $userType)
     {
         /** @var UserInterface $user */
-        $user = $this->getUserRepository()->findOneByEmail($email);
+        $user = $this->getUserRepository($userType)->findOneByEmail($email);
 
         if (null === $user) {
```
Comment (lchrusciel) [inline src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php]: Assert::notNull

File: src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php [hunk 6]
```diff
@@ -93,25 +118,58 @@ protected function findUserByEmail($email)
...
-    protected function getEntityManager()
+    protected function getEntityManager($userType)
     {
-        return $this->getContainer()->get('sylius.manager.shop_user');
+        $class = $this->getUserModelClass($userType);
+        return $this->getContainer()->get('doctrine')->getManagerForClass($class);
     }
 
     /**
+     * @param $userType
```
Comment (lchrusciel) [inline src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php]: Missing blank line

File: src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php [hunk 7]
```diff
@@ -93,25 +118,58 @@ protected function findUserByEmail($email)
...
      * @return UserRepositoryInterface
      */
-    protected function getUserRepository()
+    protected function getUserRepository($userType)
+    {
+        $class = $this->getUserModelClass($userType);
+        return $this->getEntityManager($userType)->getRepository($class);
```
Comment (lchrusciel) [inline src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php]: Missing blank line

File: src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php [hunk 8]
```diff
@@ -93,25 +118,58 @@ protected function findUserByEmail($email)
...
+        $userTypes = array_filter($config, function ($userTypeConfig) {
+            return isset($userTypeConfig['user']['classes']['model']) && is_a($userTypeConfig['user']['classes']['model'], UserInterface::class, true);
+        });
+
+        return array_keys($userTypes);
+    }
+
+    /**
+     * @param $userType
+     * @return string
```
Comment (lchrusciel) [inline src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php]: Missing blank line

File: src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php [hunk 9]
```diff
@@ -93,25 +118,58 @@ protected function findUserByEmail($email)
...
+     * @throws \InvalidArgumentException
```
Comment (lchrusciel) [inline src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php]: Missing blank line

File: src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php [hunk 10]
```diff
@@ -93,25 +118,58 @@ protected function findUserByEmail($email)
...
+     */
+    protected function getUserModelClass($userType)
+    {
+        $config = $this->getContainer()->getParameter('sylius.user.users');
+        if (empty($config[$userType]['user']['classes']['model'])) {
```
Comment (lchrusciel) [inline src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php]: Assert::notEmpty

File: src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php [hunk 11]
```diff
@@ -93,25 +118,58 @@ protected function findUserByEmail($email)
...
+            throw new \InvalidArgumentException(sprintf('User type %s misconfigured.', $userType));
+        }
+        return $config[$userType]['user']['classes']['model'];
```
Comment (lchrusciel) [inline src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php]: Missing blank line

File: src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php [hunk 12]
```diff
@@ -93,25 +118,58 @@ protected function findUserByEmail($email)
...
     }
 
     /**
      * @param OutputInterface $output
```
Comment (lchrusciel) [inline src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php]: Missing parameter in doc block

File: src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php [hunk 13]
```diff
@@ -28,27 +30,47 @@
      */
     protected function interact(InputInterface $input, OutputInterface $output)
     {
+
+        // User types configured in the Bundle
+        $availableUserTypes = $this->getAvailableUserTypes();
+        if (empty($availableUserTypes)) {
```
Comment (lchrusciel) [inline src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php]: Assert::notEmpty

File: src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php [hunk 14]
```diff
@@ -28,27 +30,47 @@
      */
     protected function interact(InputInterface $input, OutputInterface $output)
     {
+
```
Comment (lchrusciel) [inline src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php]: redundant blank line

File: src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php (hunk 6 above)
Comment (pamil) [inline src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php]: And parameter type

**Comment by pjedrzejewski** [comment]
Nice work Benoit. Thank you so much! :) If you find time, please apply the comments from review in a separate PR, these are mostly small issues. Appreciate your time! 👍

**Comment by bpolaszek** [comment]
Hi Pawel,

No problem. I can fix the blank lines (thought `php-cs-fixer` would have done all this), can you just please be more explicit about the `Assert::` things I have to fix?
I recently discovered `webmozart/assert` library and I understand what it is for, I just need to be sure on how to use it to be Sylius-compliant.

Thank you,
Ben
