### PR TITLE
[Fixtures] Fix fixtures to use codes for references

### LINKED ISSUE #4799: Cant' load sample data
Hi,

I'm trying to load sample data on a clean install of sylius but im getting this error:

```
php app/console sylius:install

Installing Sylius...

Step 1 of 4. Checking system requirements.
+--------------------+----------------+
| Issue              | Recommendation |
+--------------------+----------------+
| short_open_tag     |                |
| session.auto_start |                |
+--------------------+----------------+
Success! Your system can run Sylius properly.

Step 2 of 4. Setting up the database.
Creating Sylius database for environment dev.
It appears that your database already exists. Would you like to reset it? (y/N) y
 8/8 [||||||||||||||||||||||||||||] 100%Warning! This will erase your database. Your current environment is dev.
Load sample data? (y/N) y
Loading sample data...
 0/3 [|                           ]   0%
                                                           
  [OutOfBoundsException]                                   
  Reference to: (Sylius.Taxonomy.Category) does not exist  
```

It's maybe any configuration?

### PR DESCRIPTION
**Pull request by michalmarcinkowski**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | yes
| Deprecations?   | no
| Related tickets | fixes #4799
| License         | MIT

### CODE REVIEW

File: src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadTaxonsData.php [hunk 1]
```diff
@@ -27,21 +27,21 @@ class LoadTaxonsData extends DataFixture
     public function load(ObjectManager $manager)
     {
         $manager->persist($this->createTaxons(
-            'CATEGORY', [$this->defaultLocale => 'Category', 'es_ES' => 'Categoria'],
+            'category', [$this->defaultLocale => 'Category', 'es_ES' => 'Categoria'],
```
Comment (aramalipoor) [inline src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadTaxonsData.php]: If you're changing this to lowercase you have fix [this line](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml#L262) too ;)

Comment (michalmarcinkowski) [inline src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadTaxonsData.php]: Good catch! Thanks for being watchful :) Adjusted the search filters.

**Comment by pjedrzejewski** [comment]
Thank you Michał!
