### PR TITLE
set default value for Channel taxCalculationStrategy

### LINKED ISSUE #11414: Channel class, default taxCalculationStrategy value
**Sylius version affected**: 1.6+

**Description**  
Field `taxCalculationStrategy` of `Sylius\Component\Core\Model\Channel` :
* has no default value in class [Channel.php#L36](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Model/Channel.php#L36)
* getter and setter uses `string|null` [Channel.php#L143](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Model/Channel.php#L143)
* field is **not** nullable in ORM [Channel.orm.xml#L21](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml#L21)

**Steps to reproduce**  
Creation from the BO is not a problem since the field is of type select, the first value `order_items_based` is therefore used.
But creation by Factory or Api call, throw error.

**Possible Solution**  
Change in  [Channel.php#L36](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Model/Channel.php#L36)
```diff
-    protected $taxCalculationStrategy;
+    protected $taxCalculationStrategy = 'order_items_based';
```

What do you think about that ?

I can do the PR to fix it :wink:

### PR DESCRIPTION
**Pull request by oallain**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #11414 
| License         | MIT

### CODE REVIEW

**Comment by pamil** [comment]
Oh, I've just seen #11414. I'm not feeling comfortable with hardcoding the strategy, we should find some way to at least rely on some constraint or just use the first strategy that is available.

**Comment by lchrusciel** [comment]
Neither do I, the current solution is a no-go right now. 

Maybe we should provide such config through our factory service? This is the default method of creating new objects in Sylius.

**Comment by oallain** [comment]
Hi @lchrusciel @pamil ,

I create a ChannelFactory in Core, tell me if this is what you expected?

File: src/Sylius/Component/Core/Factory/ChannelFactory.php [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+
+    /**
+     * {@inheritdoc}
+     */
+    public function createNamed(string $name): ChannelInterface
+    {
+        /** @var ChannelInterface $channel */
+        $channel = $this->decoratedFactory->createNew();
+        $channel->setTaxCalculationStrategy('order_items_based');
+        $channel->setName($name);
```
Comment (lchrusciel) [inline src/Sylius/Component/Core/Factory/ChannelFactory.php:49]: Not needed as it is already covered by the inner function

File: src/Sylius/Component/Core/Factory/ChannelFactory.php [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+
+        return $channel;
+    }
```
Comment (mamazu) [inline src/Sylius/Component/Core/Factory/ChannelFactory.php:52]:
```suggestion
class ChannelFactory implements ChannelFactoryInterface
{
    /** @var FactoryInterface */
    private $decoratedFactory;
    
    /** @var string */
    private $defaultCalculationStrategy;

    public function __construct(FactoryInterface $decoratedFactory, string $defaultCalculationStrategy)
    {
        $this->decoratedFactory = $decoratedFactory;
        $this->defaultCalculationStrategy = $defaultCalculationStrategy;
    }

    /**
     * {@inheritdoc}
     */
    public function createNew(): ChannelInterface
    {
        /** @var ChannelInterface $channel */
        $channel = $this->decoratedFactory->createNew();
        $channel->setTaxCalculationStrategy('order_items_based');

        return $channel;
    }

    /**
     * {@inheritdoc}
     */
    public function createNamed(string $name): ChannelInterface
    {
        $channel = $this->createNew();
        $channel->setName($name);

        return $channel;
    }
```

Comment (mamazu) [reply src/Sylius/Component/Core/Factory/ChannelFactory.php:52]: That is probably what @pamil meant. And I agree with that.

Comment (lchrusciel) [reply src/Sylius/Component/Core/Factory/ChannelFactory.php:52]: @mamazu proposal makes sense. However, I need to ask one more thing. Do we need `createNamed` in the first place? It seems to be unused in this scope and therefore we should remove it in the first place IMHO. Other than this, its good to go.

Comment (mamazu) [reply src/Sylius/Component/Core/Factory/ChannelFactory.php:52]: Agreed. Because then we also don't need an extra interface for it.

Comment (oallain) [reply src/Sylius/Component/Core/Factory/ChannelFactory.php:52]: Thanks for feedbacks, i'll change it :)

Comment (oallain) [reply src/Sylius/Component/Core/Factory/ChannelFactory.php]: Hi,

I use `defaultCalculationStrategy` as parameter of ChannelFactory as proposed by @mamazu but i have keep function `createNamed()` because she is use in

https://github.com/Sylius/Sylius/blob/2875e9e2549eca13d53bc3cd3b6617da7d44ac04/src/Sylius/Component/Core/spec/Test/Services/DefaultChannelFactorySpec.php#L68

What do you think ?

Comment (mamazu) [reply src/Sylius/Component/Core/Factory/ChannelFactory.php]: Well the `createNamed` doesn't really fit the style of Sylius. But other than that it looks good.

File: src/Sylius/Component/Core/Factory/ChannelFactory.php [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+
+    /**
+     * {@inheritdoc}
+     */
+    public function createNamed(string $name): ChannelInterface
+    {
+        /** @var ChannelInterface $channel */
+        $channel = $this->decoratedFactory->createNew();
+        $channel->setTaxCalculationStrategy($this->defaultCalculationStrategy);
```
Comment (lchrusciel) [inline src/Sylius/Component/Core/Factory/ChannelFactory.php:52]:
```suggestion
        $channel = $this->createNew();
```

File: src/Sylius/Component/Core/Factory/ChannelFactoryInterface.php [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+ */
+
+declare(strict_types=1);
+
+namespace Sylius\Component\Core\Factory;
+
+use Sylius\Component\Core\Model\ChannelInterface;
+use Sylius\Component\Resource\Factory\FactoryInterface;
+
+interface ChannelFactoryInterface extends FactoryInterface
```
Comment (lchrusciel) [inline src/Sylius/Component/Core/Factory/ChannelFactoryInterface.php:19]: Is this interface even needed, as we have the interface from component namespace? https://github.com/Sylius/Sylius/blob/7901f9a3c65f626a6b40fa9b7ffa8c3a2df18ab3/src/Sylius/Component/Channel/Factory/ChannelFactoryInterface.php#L21

If so, it should be extended rather than replaced.

File: src/Sylius/Component/Core/Factory/ChannelFactory.php [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+
+class ChannelFactory implements ChannelFactoryInterface
+{
+    /** @var FactoryInterface */
+    private $decoratedFactory;
+
+    /** @var string */
+    private $defaultCalculationStrategy;
+
+    public function __construct(FactoryInterface $decoratedFactory, string $defaultCalculationStrategy)
```
Comment (lchrusciel) [inline src/Sylius/Component/Core/Factory/ChannelFactory.php:27]: IMHO current ChannelFactory should be injected
```suggestion
    public function __construct(Sylius\Component\Channel\Factory\ ChannelFactoryInterface $decoratedFactory, string $defaultCalculationStrategy)
```

**Comment by lchrusciel** [comment]
Sorry for pushing it back and forth, but not spotting the current factory implementation was my mistake from the early beginning

File: src/Sylius/Component/Core/Factory/ChannelFactoryInterface.php (hunk 4 above)
Comment (oallain) [reply src/Sylius/Component/Core/Factory/ChannelFactoryInterface.php:19]: IMHO, we need it while we don't have the covariance provided by PHP 7.4.

File: src/Sylius/Component/Core/Factory/ChannelFactory.php (hunk 5 above)
Comment (oallain) [reply src/Sylius/Component/Core/Factory/ChannelFactory.php:27]: I try but i got :

>   [TypeError]                                                                  
  Argument 1 passed to Sylius\Component\Core\Factory\ChannelFactory::__constr  
  uct() must implement interface Sylius\Component\Core\Factory\ChannelFactory  
  Interface, instance of Sylius\Component\Resource\Factory\Factory given, cal  
  led in /home/travis/build/Sylius/Sylius/var/cache/test_cached/ContainerJNMx  
  Xga/getChannelFactoryInterfaceService.php on line 12  

:disappointed:

**Comment by oallain** [comment]
Hi @lchrusciel 

All looks good, but Travis failed.
Can you (or anyone) can help me ?

Thanks

**Comment by mamazu** [comment]
The reason some of your tests may fail is because currently the master is broken. So just wait for them to fix it and then rebase again. (Or fix it yourself and make a separate pull request)

**Comment by lchrusciel** [comment]
We can try to rebase now, it should work ;)

File: src/Sylius/Component/Core/Factory/ChannelFactoryInterface.php (hunk 4 above)
Comment (lchrusciel) [reply src/Sylius/Component/Core/Factory/ChannelFactoryInterface.php:19]: However, all of the current implementations, that are based on the previous interface cannot be changed, due to BC Policy. If we want to extend the previous implementation we need to extend the previous interface

**Comment by oallain** [comment]
Hi @lchrusciel ,

Rebase is done, and "application" is green on Travis, but "doc" still red :disappointed:

**Comment by mamazu** [comment]
Can you rebase again now?

**Comment by oallain** [comment]
@mamazu ,

It's worse :wink:

**Comment by mamazu** [comment]
Hm, but the master is green. Very odd.

**Comment by oallain** [comment]
My target is Sylius:1.7, should i change the target?

**Comment by mamazu** [comment]
As this is a new feature the master branch would be great.

**Comment by oallain** [comment]
@mamazu 

I change target to master and it's green now :) 

Thanks !

**Comment by oallain** [comment]
Hello @lchrusciel @mamazu 

I rebase (again) and now Travis is green :smile: (But Symfony/Insight is Pending :joy: )

Regards

**Comment by mamazu** [comment]
Hm, someone from Sylius needs to restart this job.

**Comment by lchrusciel** [comment]
Hey Olivier 👋 

I didn't find time to take over this PR, however, I won't merge it without change to https://github.com/Sylius/Sylius/pull/11418#discussion_r441566110. Right now this PR contains BC Break.

**Comment by oallain** [comment]
Hello,

I am facing a dilemma and I don't know what/how to do :

1) Either the new `Sylius\Component\Core\Factory\ChannelFactoryInterface` extends `Sylius\Component\Channel\Factory\ChannelFactoryInterface` and in this case, the return types should be different but this is only possible with the covariance provided by PHP 7.4 - so BC with PHP < 7.4
2) Either the new `Sylius\Component\Core\Factory\ChannelFactoryInterface` return `Sylius\Component\Channel\Model\ChannelInterface` and not `Sylius\Component\Core\Model\ChannelInterface`.
2) Either keep this PR like this, however, all of the current implementations, that are based on the previous interface cannot be changed, like say Lukasz in https://github.com/Sylius/Sylius/pull/11418#discussion_r441566110 - so BC with older implementations

What is the best solution ?

**Comment by oallain** [comment]
I just push with solution 2) :wink: 

Looking forward to your feedback.

**Comment by mamazu** [comment]
I would suggest option 1 with the return type not being typehinted but just annotated in the doc type. Then psalm or phpstan or any other static code analysis tool can pick it up and it doesn't break things. (And this is also the best way to go in my opinion)

Option 2 is not great. Because the interface of the component is smaller than the interface of the core bundle (as far as I know) so this would also be sub-optimal.

Option 3: I don't know if there is already a branch in Sylius that is for 2.0 where those BC breaks will probably be bundled into. I also made a breaking change as a PR which also still has no place to go really.

**Comment by lchrusciel** [comment]
Option 3 is a no-go for us. Option 2 is what we are doing for the last few years and this is what I would recommend. However, as @mamazu stated, probably improved option 1 (with docblock) is the best solution right now.

**Comment by oallain** [comment]
Hello, @mamazu 

This rebase is :green_heart: (green) :tada:

**Comment by lchrusciel** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "tax-calculation-strategy"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Review by lchrusciel — APPROVED** [review]

**Comment by lchrusciel** [comment]
Thanks, @oallain! :1st_place_medal:
