### PR TITLE
[Product] Fixed product attribute translations #11570

### LINKED ISSUE #11570: [UX][BO] Product attribute edition
**Sylius version affected**: 1.7+

**Description**  
Select attributs on product edit page in BO are not translated.

**Steps to reproduce**  
On the product edit page in BO. If I display the attributes tab, when I change the sub-tab for the differents locales, the values of the attributes of types select remain in the default language. While the other attributes (of type text for example) have their values which change according to the locale.

### PR DESCRIPTION
**Pull request by DufourVictor**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.11                  |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                      |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | fixes #11570                     |
| License         | MIT                                                          |

Bug :
Select attributes on product edit page in BO are not translated.

Fix : 
Get locale from context and translate with this locale.

### CODE REVIEW

**Comment by Zales0123** [comment]
Hello @DufourVictor! Do you think you would be able to provide a Behat scenario to reproduce this bug and prove it's fixed? It would be great 🖖

**Comment by DufourVictor** [comment]
Unbelievable @NoResponseMate I had started to work on the tests but never had time to finish. Thanks a lot!

File: src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php [hunk 1]
```diff
@@ -463,12 +463,21 @@ public function iAddTheOptionToIt($optionName)
...
     {
         $this->createSimpleProductPage->addAttribute($attribute, $value ?? '', $language);
     }
 
+    /**
+     * @When I select :value value in :language for the :attribute attribute
+     */
+    public function iSelectValueInLanguageForTheAttribute(string $value, string $language, string $attribute): void
+    {
+        $this->createSimpleProductPage->selectAttributeValue($attribute, $value, $language);
```
Comment (GSadee) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php:478]: I would be in favour of using `localeCode` instead of `language`

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you, @DufourVictor! :1st_place_medal:
