### PR TITLE
Check different shipping address field and display shipping address form

### LINKED ISSUE #11348: Going back to Addresses step is not fully functionnal
**Sylius version affected**: 1.7.0

**Description**  
If you fill the billing AND shipping addresses in the checkout, then you go to Shipping method, then you go back to the addresses: the checkbox "Use different address for shipping?" isn't checked anymore.

address_bug

**Steps to reproduce**  

See above.

**Possible Solution**  

I don't have any, I think it's because of the switch of the billing and shipping addresses.

### PR DESCRIPTION
**Pull request by vvasiloi**
When shipping and billing addresses are different

| Q               | A
| --------------- | -----
| Branch?         | 1.7
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | yes
| Related tickets | fixes #11348
| License         | MIT

### CODE REVIEW

**Comment by vvasiloi** [comment]
I started it from master, but then I noticed the issue has the "bug" label, so I switched to 1.7.

File: src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php [hunk 1]
```diff
@@ -284,6 +300,7 @@ protected function getDefinedElements(): array
             'login_password' => '[data-test-password-input]',
             'login_validation_error' => '[data-test-login-validation-error]',
             'next_step' => '[data-test-next-step]',
+            'shipping_address' => '#sylius-shipping-address',
```
Comment (pamil) [inline src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php:303]:
```suggestion
            'shipping_address' => '[data-test-shipping-address]',
```

File: src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php [hunk 2]
```diff
@@ -29,32 +30,61 @@
...
+    private $addressComparator;
+
+    public function __construct(string $dataClass, array $validationGroups = [], ?AddressComparatorInterface $addressComparator = null)
+    {
+        parent::__construct($dataClass, $validationGroups);
+
+        if (null === $addressComparator) {
+            @trigger_error(
+                sprintf(
+                    'Not passing an $addressComparator to %s constructor is deprecated since Sylius 1.7 and will be removed in Sylius 2.0.',
```
Comment (pamil) [inline src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:43]:
```suggestion
                    'Not passing an $addressComparator to "%s" constructor is deprecated since Sylius 1.8 and will be impossible in Sylius 2.0.',
```

File: src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php [hunk 3]
```diff
@@ -29,32 +30,61 @@
...
                 $order = $event->getData();
-
                 /** @var OrderInterface $order */
                 Assert::isInstanceOf($order, OrderInterface::class);
 
                 $channel = $order->getChannel();
 
+                $differentBillingOrShippingAddressChecked = null !== $this->addressComparator
+                    && null !== $order->getBillingAddress() && null !== $order->getShippingAddress()
+                    && !$this->addressComparator->equal($order->getBillingAddress(), $order->getShippingAddress());
```
Comment (pamil) [inline src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:69]: Could you extract this conditional to a private method? It's really tough to understand the flow now.

File: src/Sylius/Bundle/CoreBundle/Resources/config/services/checkout.xml [hunk 4]
```diff
@@ -39,6 +39,7 @@
         <service id="sylius.form.type.checkout_address" class="Sylius\Bundle\CoreBundle\Form\Type\Checkout\AddressType">
             <argument>%sylius.model.order.class%</argument>
             <argument>%sylius.form.type.checkout_address.validation_groups%</argument>
+            <argument type="service" id="sylius.address_comparator"/>
```
Comment (pamil) [inline src/Sylius/Bundle/CoreBundle/Resources/config/services/checkout.xml:42]:
```suggestion
            <argument type="service" id="sylius.address_comparator" />
```

File: src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php [hunk 5]
```diff
@@ -29,32 +30,61 @@
...
+
                 $form
+                    ->add('differentBillingAddress', CheckboxType::class, [
+                        'mapped' => false,
+                        'required' => false,
+                        'label' => 'sylius.form.checkout.addressing.different_billing_address',
+                        'attr' => [
+                            'checked' => $differentBillingOrShippingAddressChecked,
```
Comment (pamil) [inline src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:77]: I wonder whether we can just set the data here like:

```php
$data = $event->getData();
$data['differentBillingAddress'] = $data['differentShippingAddress'] = $differentBillingOrShippingAddressChecked;
$event->setData($data);
```

Could you check it out? This way we could leave these two fields outside of the event listener and achieve better backwards compatibility.

File: src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php [hunk 6]
```diff
@@ -29,32 +30,61 @@
...
-                'required' => false,
-                'label' => 'sylius.form.checkout.addressing.different_billing_address',
-            ])
-            ->add('differentShippingAddress', CheckboxType::class, [
-                'mapped' => false,
-                'required' => false,
-                'label' => 'sylius.form.checkout.addressing.different_shipping_address',
-            ])
-            ->addEventListener(FormEvents::PRE_SET_DATA, static function (FormEvent $event): void {
+            ->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event): void {
```
Comment (pamil) [inline src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:59]: To be reverted:

```suggestion
            ->addEventListener(FormEvents::PRE_SET_DATA, static function (FormEvent $event): void {
```

File: src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php [hunk 7]
```diff
@@ -29,32 +30,61 @@
...
                 $form = $event->getForm();
                 $order = $event->getData();
-
```
Comment (pamil) [inline src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:51]: To be reverted.

File: src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php (hunk 5 above)
Comment (vvasiloi) [reply src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:77]: The data here holds the value of the checkbox, i.e. `value` attribute, not the `checked` attribute/property, so it won't work.

File: src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php (hunk 6 above)
Comment (vvasiloi) [reply src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:59]: It can't be made static, because it uses `$this`

File: src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php (hunk 7 above)
Comment (vvasiloi) [reply src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:51]: There will be a CS check error if I do that.

Comment (vvasiloi) [reply src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:51]:
```
src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:63
 ----------------------------------------------------------------------------------------------------------------
 Missing variable $order before or after the documentation comment.

(SlevomatCodingStandard\Sniffs\Commenting\InlineDocCommentDeclarationSniff.MissingVariable)
```

Comment (vvasiloi) [reply src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:51]: I moved it before the `$order` is set.

Comment (vvasiloi) [reply src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:51]: Now I get psalm errors https://psalm.dev/docs/running_psalm/issues/RedundantConditionGivenDocblockType/
The only way I found to not get any is to remove the docblock.
Is there another way?

Comment (pamil) [reply src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:51]: I guess I'm OK with CS check error, we should disable that sniff anyway, it's more important to get Psalm passing.

Comment (pamil) [reply src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:51]: So moving this docblock just before `Assert` would be the best solution here.

Comment (vvasiloi) [reply src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:51]: Still get that psalm error.

Comment (vvasiloi) [reply src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php:51]: The docblock is here for intelligent code completion and the assert if for the actual type checking.
The only way I can think of to achieve both is this:
```
                if (!($order instanceof OrderInterface)) {
                    // or just return;
                    throw new \InvalidArgumentException(
                        'Expected an instance of %2$s. Got: %s',
                        OrderInterface::class,
                        get_class($order)
                    );
                }
```

**Comment by lchrusciel** [comment]
Hey Victor :wave:

Could you rebase your fix to the newest master? Also, there is a small issue with the psalm checks.

**Comment by vvasiloi** [comment]
@lchrusciel done!

**Comment by lchrusciel** [comment]
Thanks, Victor! :tada:
