### PR TITLE
[Promotion] Generating long coupons

### LINKED ISSUE #10912: [Promotion] Unable to generate coupons
**Sylius version affected**: 1.6

**Description**  
```
Invalid coupons code length or coupons amount. It is not possible to generate 50 unique coupons with code length equals 16. Possible generate amount is -9223372036854775808.
```

**Steps to reproduce**  
See screenshot: https://www.dropbox.com/s/x4fbw8wohwnweom/Screenshot%202019-12-09%2019.28.31.png?dl=0

Another one: https://www.dropbox.com/s/na4xbazvadlpz7d/Screenshot%202019-12-09%2019.33.07.png?dl=0

### PR DESCRIPTION
**Pull request by GSadee**
| Q               | A
| --------------- | -----
| Branch?         | 1.6
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #10912, based on #11064 and #11097
| License         | MIT

### CODE REVIEW

File: src/Sylius/Component/Promotion/Generator/PercentageGenerationPolicy.php [hunk 1]
```diff
@@ -68,6 +68,11 @@ private function calculatePossibleGenerationAmount(PromotionCouponGeneratorInstr
             $instruction->getSuffix()
         );
 
-        return (int) floor((16 ** $expectedCodeLength) * $this->ratio - $generatedAmount);
+        $codeCombination = 16 ** $expectedCodeLength * $this->ratio;
+        if ($codeCombination >= PHP_INT_MAX) {
+            return PHP_INT_MAX - $generatedAmount;
+        }
+
+        return (int) $codeCombination - $generatedAmount;
```
Comment (GSadee) [inline src/Sylius/Component/Promotion/Generator/PercentageGenerationPolicy.php]: Example:
When: `$expectedAmount = 20;`
Then: `$codeCombination = {float} 6.0446290980731E+23;`
And: `$codeCombination >= PHP_INT_MAX` is true
So the value `PHP_INT_MAX - $generatedAmount` will be returned

IMO this fix (without changing current behaviour and without BC breaks) makes sense, but WDYT /cc @Sylius/core-team ? 😃

Comment (lchrusciel) [reply src/Sylius/Component/Promotion/Generator/PercentageGenerationPolicy.php]: In PromotionCouponGenerator we are allowing for coupons up to 40 characters. If we can process with calculation, maybe we should increase this amount? 

Also, how much of precision will we lost when we will convert to float?

Comment (GSadee) [reply src/Sylius/Component/Promotion/Generator/PercentageGenerationPolicy.php]: The problem is that we cannot convert to float because of BC Policy, we need to return here an integer value, so `PHP_INT_MAX` is the max value that could be returned. IMO this fix resolves the bug, we are able to generate coupons even for 40 characters, but there will be a limit to `PHP_INT_MAX` coupons that can be generated. Increasing this value could be also a problem for form (`PromotionCouponGeneratorInstructionType`) where is an integer field for the amount.

Comment (pamil) [reply src/Sylius/Component/Promotion/Generator/PercentageGenerationPolicy.php]: Thanks for the explanation!

Comment (pamil) [reply src/Sylius/Component/Promotion/Generator/PercentageGenerationPolicy.php]: Thanks for the explanation!

**Comment by pamil** [comment]
Thank you, Grzegorz! :tada:
