### PR TITLE
[DEPRECATIONS] Mark `CartActions` interface and `OrderItemController` as deprecated

### LINKED ISSUE #17588: OrderItemController removed in Sylius 2.0 without deprecation
**Sylius version affected**: 2.0

**Description**  
These classes were removed in Sylius 2.0 without deprecation in Sylius 1.14:

* `Sylius\Bundle\OrderBundle\Controller\OrderItemController`
* `Sylius\Component\Order\CartActions`

How can a product be added to the cart if your project doesn't use the Symfony UX component?

**Steps to reproduce**  
Try to migrate a Sylius 1.14 project with a OrderItemController override.

**Possible Solution**  
Deprecate these class in Sylius 1.14 to help the migration.

Add the deleted class into the migration guide.

### PR DESCRIPTION
**Pull request by tomkalon**
…in preparation for Sylius 2.0.

| Q               | A
|-----------------|-----
| Branch?         | 1.14
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | yes
| Related tickets | https://github.com/Sylius/Sylius/issues/17588
| License         | MIT

Adding deprecations:
- Sylius\Bundle\OrderBundle\Controller\OrderItemController
- Sylius\Component\Order\CartActions

### CODE REVIEW

File: src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php [hunk 1]
```diff
@@ -32,6 +32,7 @@
 use Symfony\Component\HttpKernel\Exception\HttpException;
 use Symfony\Component\Validator\ConstraintViolationListInterface;
 
+/** @deprecated since Sylius 1.14 and will be removed in Sylius 2.0. */
```
Comment (TheMilek) [inline src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php:41]: lets make it align with the other deprecations, like [here](https://github.com/Sylius/Sylius/blob/1.14/src/Sylius/Bundle/AdminBundle/Controller/Dashboard/StatisticsController.php#L21-L27)

**Review by Rafikooo — APPROVED** [review]
