### PR TITLE
Base URL support in ThemeBundle (fixes #8278)

### LINKED ISSUE #8278: framework.assets.base_urls conflicts with theme asset path resolving (breaks CDN support)
URL without `framework.assets.base_urls` defined: http://example.com/bundles/_themes/themename/base-theme/theme/svg/tj-logo.svg

URL with `framework.assets.base_urls` defined to ['http://example.com/']: http://example.com/bundles/theme/svg/tj-logo.svg

```yml
framework:
    assets:
        base_urls: ['http://example.com/']
```

According to https://symfony.com/doc/current/reference/configuration/framework.html#base-urls.

Use case is that I want to load my assets over a CDN. Most assets are going well, but the ones connected to a theme are now given a wrong URL.

The theme path resolver doesn't get the path supplied at all, so it seems to bypass these things. I'm not sure it hits the PathPackage::getUrl() though, but I have the impression that it also skips that one.

### PR DESCRIPTION
**Pull request by stefandoorn**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | yes |
| BC breaks?      | no |
| Related tickets | fixes #8278 |
| License         | MIT |

Overrides Symfony's UrlPackage to allow theme bundle to handle different base URL's. Allows users that use themes, also to use CDN base URL's for assets.

### CODE REVIEW

File: src/Sylius/Bundle/ThemeBundle/Asset/Package/UrlPackage.php [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+        }
+
+        return $this->getBaseUrl($path) . $url;
+    }
+
+    /**
+     * @param $urls
+     * @return array
+     */
+    private function getSslUrls($urls): array
```
Comment (pamil) [inline src/Sylius/Bundle/ThemeBundle/Asset/Package/UrlPackage.php]: `iterable/array $urls`?

File: src/Sylius/Bundle/ThemeBundle/spec/Asset/Package/UrlPackageSpec.php [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+{
+    function let(
+        VersionStrategyInterface $versionStrategy,
+        ThemeContextInterface $themeContext,
+        PathResolverInterface $urlResolver
+    ): void {
+        $this->beConstructedWith(['https://cdn-url.com/'], $versionStrategy, $themeContext, $urlResolver);
+    }
+
+    function it_implements_package_interface(): void
```
Comment (pamil) [inline src/Sylius/Bundle/ThemeBundle/spec/Asset/Package/UrlPackageSpec.php]: We might also add `it_extends_symfony_url_package` spec.

File: src/Sylius/Bundle/ThemeBundle/spec/Asset/Package/UrlPackageSpec.php [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+    {
+        $this->shouldImplement(PackageInterface::class);
+    }
+
+    function it_returns_vanilla_url_if_there_are_no_active_themes_and_with_base_url(
+        VersionStrategyInterface $versionStrategy,
+        ThemeContextInterface $themeContext,
+        PathResolverInterface $urlResolver
+    ): void
+    {
```
Comment (pamil) [inline src/Sylius/Bundle/ThemeBundle/spec/Asset/Package/UrlPackageSpec.php]: CS :)

File: src/Sylius/Bundle/ThemeBundle/Asset/Package/UrlPackage.php [hunk 4]
```diff
@@ -0,0 +1,132 @@
...
+        $baseUrls,
+        VersionStrategyInterface $versionStrategy,
+        ThemeContextInterface $themeContext,
+        PathResolverInterface $pathResolver,
+        ?ContextInterface $context = null
+    ) {
+        parent::__construct($baseUrls, $versionStrategy, $context);
+
+        if (!is_array($baseUrls)) {
+            $baseUrls = (array)$baseUrls;
```
Comment (pamil) [inline src/Sylius/Bundle/ThemeBundle/Asset/Package/UrlPackage.php]: CS: We usually leave a space after typecasting.

File: src/Sylius/Bundle/ThemeBundle/spec/Asset/Package/UrlPackageSpec.php (hunk 2 above)
Comment (stefandoorn) [reply src/Sylius/Bundle/ThemeBundle/spec/Asset/Package/UrlPackageSpec.php]: Added.

**Comment by pamil** [comment]
Thanks Stefan! 🎉

**Comment by pjedrzejewski** [comment]
You rock Stefan, this is huge help before release, thanks!
