### PR TITLE
Send environment during GUS version check

### LINKED ISSUE #8108: Sylius/GUS broken comparison logic.
There is no comparison logic on Sylius side so actually notification widget will always display that new version of sylius is available.

### PR DESCRIPTION
**Pull request by pamil**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | yes |
| BC breaks?      | no |
| Related tickets | fixes #8108 |
| License         | MIT |

### CODE REVIEW

File: src/Sylius/Bundle/AdminBundle/Tests/Controller/NotificationControllerTest.php [hunk 1]
```diff
@@ -13,6 +13,7 @@
 
 use GuzzleHttp\ClientInterface;
 use GuzzleHttp\Exception\ConnectException;
+use GuzzleHttp\Psr7\Uri;
```
Comment (lchrusciel) [inline src/Sylius/Bundle/AdminBundle/Tests/Controller/NotificationControllerTest.php]: Is it needed?

Comment (pamil) [inline src/Sylius/Bundle/AdminBundle/Tests/Controller/NotificationControllerTest.php]: Not really.
