### PR TITLE
Fix finding json by choice in the Postgres

### LINKED ISSUE #15390: Bug on removing product attribute value (postgres only)
**Sylius version affected**: 1.x.y

**Description**  
The PostgreSQL database schema contains JSON typed property on table sylius_product_attribute_value (the json_value field). The JSON type breaks the functionality of removing select-typed attribute value from the attribute, when it's used in the product.

**Steps to reproduce**  
1. Create a "Select" typed product attribute with 3 options.
2. Assign different options if the attribute to the product.
3. Try to remove one option form the attribute, which is used in the product.

**Possible Solution**  
I've did some research on PostgreSQL documentation, which says the JSON type is stored as clean text value, so it's possible just to write the migration to convert that column type into TEXT.

Reflinks:

- https://www.postgresql.org/docs/current/datatype-json.html
- https://www.postgresql.org/docs/current/datatype-character.html

### PR DESCRIPTION
**Pull request by jakubtobiasz**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13
| Bug fix?        | kinda
| New feature?    | 
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #15390
| License         | MIT

### CODE REVIEW

File: src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php
Comment (jakubtobiasz) [inline src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php:1]: This code is copied from the library I've removed, as we needed only 2 classes from it :p.

File: src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractPostgresqlJsonFunctionNode.php
Comment (jakubtobiasz) [inline src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractPostgresqlJsonFunctionNode.php:1]: Same here

File: src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php [hunk 1]
```diff
@@ -27,8 +29,18 @@ class ProductAttributeValueRepository extends EntityRepository implements Produc
 {
     public function findByJsonChoiceKey(string $choiceKey): array
     {
-        return $this->createQueryBuilder('o')
-            ->andWhere('o.json LIKE :key')
+        $connection = $this->getEntityManager()->getConnection();
+        $isPostgres = $this->isPostgres($connection);
+
+        $qb = $this->createQueryBuilder('o');
```
Comment (diimpp) [inline src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php]: Full name matches existing codebase better.

```suggestion
        $queryBuilder = $this->createQueryBuilder('o');
```

File: src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php [hunk 2]
```diff
@@ -27,8 +29,18 @@ class ProductAttributeValueRepository extends EntityRepository implements Produc
...
+
+        if ($isPostgres) {
+            $qb->andWhere('JSONB_ARRAY_ELEMENTS_TEXT(o.json) LIKE :key');
+        } else {
+            $qb->andWhere('o.json LIKE :key');
+        }
+
+        return $qb
```
Comment (diimpp) [inline src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php]:
```suggestion
        return $queryBuilder
```

File: src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php [hunk 3]
```diff
@@ -27,8 +29,18 @@ class ProductAttributeValueRepository extends EntityRepository implements Produc
...
     {
-        return $this->createQueryBuilder('o')
-            ->andWhere('o.json LIKE :key')
+        $connection = $this->getEntityManager()->getConnection();
+        $isPostgres = $this->isPostgres($connection);
+
+        $qb = $this->createQueryBuilder('o');
+
+        if ($isPostgres) {
+            $qb->andWhere('JSONB_ARRAY_ELEMENTS_TEXT(o.json) LIKE :key');
```
Comment (diimpp) [inline src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php]:
```suggestion
            $queryBuilder->andWhere('JSONB_ARRAY_ELEMENTS_TEXT(o.json) LIKE :key');
```

File: src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php [hunk 4]
```diff
@@ -79,4 +91,12 @@ public function createByProductCodeAndLocaleQueryBuilder(
             ->setParameter('locale', $localeCode)
         ;
     }
+
+    protected function isPostgres(Connection $connection): bool
```
Comment (diimpp) [inline src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php]: Better to match naming.

```suggestion
    protected function isPostgreSQLPlatform(Connection $connection): bool
    protected function isPostgreSQLDatabasePlatform(Connection $connection): bool
```

File: src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php [hunk 5]
```diff
@@ -0,0 +1,176 @@
+<?php
+
```
Comment (diimpp) [inline src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php]: Should it have some license block? If none will be added, then next coding style check will change it to sylius one.

File: src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php [hunk 6]
```diff
@@ -0,0 +1,176 @@
...
+        if (!empty($this->optionalArgumentTypes)) {
+            $this->parseOptionalArguments($parser, $argumentParsed);
+        }
+
+        $parser->match(Lexer::T_CLOSE_PARENTHESIS);
+    }
+
+    /**
+     * @param Parser $parser
+     * @param bool $argumentParsed
```
Comment (diimpp) [inline src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php]:
```suggestion
```

File: src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php [hunk 7]
```diff
@@ -0,0 +1,176 @@
...
+        if ($lookaheadType != Lexer::T_STRING) {
+            $parser->syntaxError('string');
+        }
+
+        return $this->matchStringLiteral($parser, $lexer);
+    }
+
+    /**
+     * @param Parser $parser
+     * @return Literal
```
Comment (diimpp) [inline src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php]:
```suggestion
```

File: src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php [hunk 8]
```diff
@@ -0,0 +1,176 @@
...
+        return sprintf('%s(%s)', $this->getSQLFunction(), implode(', ', $arguments));
+    }
+
+    protected function getSQLFunction(): string
+    {
+        return static::FUNCTION_NAME;
+    }
+
+    /**
+     * @param SqlWalker $sqlWalker
```
Comment (diimpp) [inline src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php]:
```suggestion
```

File: src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractPostgresqlJsonFunctionNode.php [hunk 9]
```diff
@@ -0,0 +1,40 @@
...
+use Doctrine\DBAL\Exception;
+use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
+use Doctrine\ORM\Query\SqlWalker;
+
+abstract class AbstractPostgresqlJsonFunctionNode extends AbstractJsonFunctionNode
+{
+    /**
+     * @param SqlWalker $sqlWalker
+     * @throws Exception
+     */
```
Comment (diimpp) [inline src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractPostgresqlJsonFunctionNode.php]: docblock will be inherited.

```suggestion
```

File: src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractPostgresqlJsonFunctionNode.php [hunk 10]
```diff
@@ -0,0 +1,40 @@
...
+    protected function validatePlatform(SqlWalker$sqlWalker): void
+    {
+        if (!$sqlWalker->getConnection()->getDatabasePlatform() instanceof PostgreSQLPlatform) {
+            throw Exception::notSupported(static::FUNCTION_NAME);
+        }
+    }
+
+    /**
+     * @return string
+     */
```
Comment (diimpp) [inline src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractPostgresqlJsonFunctionNode.php]:
```suggestion
```

File: src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php [hunk 11]
```diff
@@ -79,4 +91,12 @@ public function createByProductCodeAndLocaleQueryBuilder(
...
+    {
+        return
+            class_exists(PostgreSQLPlatform::class) &&
```
Comment (diimpp) [inline src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php]: Is it possible for this class not to exist, if `doctrine/dbal` is installed? Otherwise check is unnecessary.

File: src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php
Comment (diimpp) [reply src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php:1]: Was it removed in this PR? Composer files don't have removal of any dependencies as far as I can see.

Would be cool to leave some credit to that library though, like a `@see` block.

P.S. Is self-maintenance of those ast functions worth dependency removal?

File: src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php [hunk 12]
```diff
@@ -0,0 +1,176 @@
+<?php
+
+namespace Sylius\Bundle\ProductBundle\Doctrine\Query\Function;
```
Comment (diimpp) [inline src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php]: Should we sync namespaces with already existing AST functions?

https://github.com/Sylius/Sylius/blob/1.13/src/Sylius/Bundle/CoreBundle/Doctrine/DQL/DateFormat.php

> Doctrine\Query\Function
> Doctrine\Query\AST\Function
> Doctrine\DQL\Function

This one feels most appropriate as it follows `doctrine/orm` naming schema.
> Doctrine\ORM\Query\AST\Function

File: src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php
Comment (jakubtobiasz) [reply src/Sylius/Bundle/ProductBundle/Doctrine/Query/Function/AbstractJsonFunctionNode.php:1]: You're right about the `@see` directive. I don't see any reason to keep any library as a dependency for 1 abstract class, as the second one is really simple.

The dependency can be seen while going through commits.

File: src/Sylius/Bundle/CoreBundle/Migrations/Version20240318083808.php [hunk 13]
```diff
@@ -0,0 +1,26 @@
+<?php
+
+declare(strict_types=1);
+
+namespace Sylius\Bundle\CoreBundle\Migrations;
+
+use Doctrine\DBAL\Schema\Schema;
+use Sylius\Bundle\CoreBundle\Doctrine\Migrations\AbstractPostgreSQLMigration;
+
+final class Version20240318083808 extends AbstractPostgreSQLMigration
```
Comment (TheMilek) [inline src/Sylius/Bundle/CoreBundle/Migrations/Version20240318083808.php:10]: Have you tested how it affects the existing values in the database, is it safe?

**Review by TheMilek — DISMISSED** [review]

File: src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php [hunk 14]
```diff
@@ -27,8 +29,18 @@ class ProductAttributeValueRepository extends EntityRepository implements Produc
...
     public function findByJsonChoiceKey(string $choiceKey): array
     {
-        return $this->createQueryBuilder('o')
-            ->andWhere('o.json LIKE :key')
+        $connection = $this->getEntityManager()->getConnection();
+        $isPostgres = $this->isPostgreSQLPlatform($connection);
+
+        $queryBuilder = $this->createQueryBuilder('o');
+
+        if ($isPostgres) {
```
Comment (NoResponseMate) [inline src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php]:
```suggestion
        $queryBuilder = $this->createQueryBuilder('o');

        if ($this->isPostgresSQLPlatform()) {
```
Don't see a point in getting and passing the connection in here if it's completely dislocated with the rest of the method, just put it in the `::isPostgresSQLPlatform`

File: src/Sylius/Bundle/ProductBundle/Doctrine/ORM/Query/AST/Function/AbstractJsonFunctionNode.php [hunk 15]
```diff
@@ -0,0 +1,183 @@
...
+                return new Literal(Literal::NUMERIC, $lexer->token->value);
+            default:
+                $parser->syntaxError('numeric');
+        }
+    }
+
+    private function matchStringLiteral(Parser $parser, Lexer $lexer): Literal
+    {
+        $parser->match(Lexer::T_STRING);
+        return new Literal(Literal::STRING, $lexer->token->value);
```
Comment (NoResponseMate) [inline src/Sylius/Bundle/ProductBundle/Doctrine/ORM/Query/AST/Function/AbstractJsonFunctionNode.php]:
```suggestion
        $parser->match(Lexer::T_STRING);

        return new Literal(Literal::STRING, $lexer->token->value);
```

File: src/Sylius/Bundle/ProductBundle/Doctrine/ORM/Query/AST/Function/JsonbArrayElementsText.php [hunk 16]
```diff
@@ -0,0 +1,31 @@
...
+{
+    public const FUNCTION_NAME = 'JSONB_ARRAY_ELEMENTS_TEXT';
+
+    /** @var string[] */
+    protected array $requiredArgumentTypes = [self::STRING_PRIMARY_ARG];
+
+    protected function getSqlForArgs(array $arguments): string
+    {
+        [$leftArg] = $arguments;
+        return sprintf('(SELECT * FROM jsonb_array_elements_text(%s))', $leftArg);
```
Comment (NoResponseMate) [inline src/Sylius/Bundle/ProductBundle/Doctrine/ORM/Query/AST/Function/JsonbArrayElementsText.php]:
```suggestion
        return sprintf('(SELECT * FROM jsonb_array_elements_text(%s))', array_shift($arguments));
```

File: src/Sylius/Bundle/CoreBundle/Migrations/Version20240318083808.php (hunk 13 above)
Comment (jakubtobiasz) [reply src/Sylius/Bundle/CoreBundle/Migrations/Version20240318083808.php:10]: Yup, it just converted, as they're compatible types

**Review by Wojdylak — APPROVED** [review]

**Review by NoResponseMate — APPROVED** [review]

**Comment by NoResponseMate** [comment]
Thank you, @jakubtobiasz!

File: src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php [hunk 17]
```diff
@@ -13,6 +13,8 @@
 
 namespace Sylius\Bundle\ProductBundle\Doctrine\ORM;
 
+use Doctrine\DBAL\Connection;
```
Comment (diimpp) [inline src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php:16]: Not used anymore

Comment (NoResponseMate) [reply src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php:16]: Yeah, there are a few obsolete imports, missing strict types declarations, code style issues etc. I just ignored them since the automated ecs fixer will take care of them 💃
