### PR TITLE
Decorate OpenApi documentation (Api Platform 2.6). Fixes #13384

### LINKED ISSUE #13384: Swagger documentation normalizers don't work with Api Platform 2.6
**Sylius version affected**: current master

**Description**  
Sylius ships for decorating documentation normalizers which are meant to improve some bits in swagger UI. They don't work with Api Platform 2.6 though.

**Steps to reproduce**  
1. Install Sylius 1.10 anew, make sure that composer installs Api Platform 2.6 along with it.
2. Enable and open api docs
3. Observe how none of the changes are made by Documentation Normalizers (e.g. authentication paths aren't documented).

**Possible Solution**  
Porting current normalizers to Api Platform 2.6 is pretty straightforward, and I intend to make a PR with the necessary changes.

### PR DESCRIPTION
**Pull request by rimas-kudelis**
| Q               | A
| --------------- | -----
| Branch?         | 1.10
| Bug fix?        | not sure
| New feature?    | not sure
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #13384
| License         | MIT

I don't think this breaks anything (very reassuring, I know :sunglasses:), since it only adds extra bits to the OpenApi documentation generated by ApiPlatform 2.6 to make it on par with what we have for Api Platform 2.5.

No tests, and I don't think I could add any quickly. Sorry!

### CODE REVIEW

File: src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php [hunk 1]
```diff
@@ -31,10 +31,12 @@ public function load(array $configs, ContainerBuilder $container): void
...
         $loader->load('services.xml');
 
-        if (!$container->hasParameter('enable_swagger') || !$container->getParameter('enable_swagger')) {
-            return;
+        if ($container->hasParameter('enable_swagger') && $container->getParameter('enable_swagger')) {
+            $loader->load('integrations/swagger.xml');
         }
 
-        $loader->load('integrations/swagger.xml');
+        if (class_exists(\ApiPlatform\Core\OpenApi\OpenApi::class)) {
```
Comment (rimas-kudelis) [inline src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php:38]: I'm testing for class existence here because the `api_platform.openapi.factory` service apparently is not defined yet and `$container->has('api_platform.openapi.factory')` returns `false`.

To avoid service not found errors when the service indeed doesn't exist for some reason, I've added `decoration-on-invalid="ignore"` to all service definitions. 

Not sure if this is the best approach though.

**Review by lchrusciel — COMMENTED** [review]
Hey Rimas, thanks a lot for your contribution!

I've checked out you branch, and I'm still not seeing documentation fixed :( Can you check if truly work?

**Comment by rimas-kudelis** [comment]
Hi Lukasz! I tried again, and yes, it works for me:
paveikslas
paveikslas
Without my patch, I don't see these endpoints.

**Comment by Rafikooo** [comment]
Hi @rimas-kudelis, I've checked out your branch also and it looks like everything is fine 

Screenshot 2021-12-21 at 13 27 24
Screenshot 2021-12-21 at 13 29 08

**Comment by rimas-kudelis** [comment]
@lchrusciel wanna give this another try? Maybe you forgot to clear cache the last time, or something like that? :)

**Comment by lchrusciel** [comment]
ok, problem was on the not clearing the cache level... I didn't notice, that new implementation is changing order of endpoints 😅

**Review by Zales0123 — APPROVED** [review]

**Comment by lchrusciel** [comment]
Thanks, Rimas! 🏅
