### PR TITLE
[CatalogPromotion] Fix too early data setting during catalog promotion form submission

### LINKED ISSUE #14137: Catalog Promotion: Bug when submitting editing Catalog Promotion Action with Entity Associated with it
**Sylius version affected**:  

Observed on **1.11.0** and **1.11.6**

**Description**  

In our company, in our implementation of Sylius, we have custom tags that are used in a form of **Cart Promotion** and **Catalog Promotion**.

We use the autocomplete **ResourceAutocompleteChoiceType**. Since each tag is indeed a entity that will be later be stored in the
configuration column of **_sylius_catalog_promotion_action_** and **_sylius_promotion_action_** (serialized).

This works well in the Cart Promotion Section > Action, but it does not in the Catalog Promotion one > Action.
In **Catalog Promotion** it works in the creation process but when updating (edit) there is the following bug:

`A cycle was detected. Listeners to the PRE_SET_DATA event must not call getNormData() if the form data has not already been set.`

It seems that the data during the edition submit is handled incorrectly when an entity / collection are being handled. 

**Steps to reproduce**  

Screenshot 2022-07-07 at 18 30 19

1) Have a tag entity simply with and id and a code.
2) Create Form Type that uses uses the tag entity and has as a parent the `ResourceAutocompleteChoiceType`.
3) Create an action that uses the previous TagConfiguration
3) Create a Catalog Promotion with the the action containing the tag selector and add a tag.
4) The creation must succeed and the edition should fail

**What we observed:**  

1) We have noticed in  in `Sylius\Bundle\PromotionBundle\Form\Type\CatalogPromotionActionType`
in line 66. `$formData->setConfiguration($data['configuration']);`
`$formData` indeed contains entities and collection and `$data['configuration']`  injects into the $formData the data in form of arrays.
We don't have all this form manipulation in the cart section.

2) This only occurs in the edition section (inside the block starting at line 64 of `Sylius\Bundle\PromotionBundle\Form\Type\CatalogPromotionActionType`

`

             if ($formData !== null) {
                    $formData->setType($data['type']);
                    $formData->setConfiguration($data['configuration']);

                    if ($data['type'] === FixedDiscountPriceCalculator::TYPE) {
                        foreach ($data['configuration'] as $channelConfiguration) {
                            if ($channelConfiguration['amount'] === '') {
                                return;
                            }
                        }
                    }

                    if ($data['type'] === PercentageDiscountPriceCalculator::TYPE) {
                        if ($data['configuration']['amount'] === '') {
                            return;
                        }
                    }

                    $form->setData($formData);
                }
`

3) Perhaps the standard transformers do not manipulate entities as they should. As a test we created a transformer doing nothing but returning the receiving data and the edition is persisted correctly.

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.11 |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | fixes #14137 |
| License         | MIT                                                          |

### CODE REVIEW

File: src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionActionType.php [hunk 1]
```diff
@@ -68,11 +68,8 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 $form = $event->getForm();
                 $formData = $form->getData();
 
-                if ($formData !== null) {
-                    $formData->setType($data['type']);
-                    $formData->setConfiguration($data['configuration']);
-
-                    $form->setData($formData);
+                if ($formData !== null && $formData?->getType() !== $data['type']) {
```
Comment (NoResponseMate) [inline src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionActionType.php]:
```suggestion
                if ($formData !== null && $formData->getType() !== $data['type']) {
```
unnecessary since you're already checking for that

File: src/Sylius/Bundle/PromotionBundle/Tests/Form/CatalogPromotionActionTypeTest.php [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+    {
+        return [
+            new CatalogPromotionActionType(
+                CatalogPromotionAction::class,
+                [],
+                [
+                    'configuration_type' => new ConfigurationType(),
+                ],
+            ),
+        ];
```
Comment (NoResponseMate) [inline src/Sylius/Bundle/PromotionBundle/Tests/Form/CatalogPromotionActionTypeTest.php]:
```suggestion
        return [
            new CatalogPromotionActionType(CatalogPromotionAction::class, [], [
                'configuration_type' => new ConfigurationType(),
            ]),
        ];
```
WDYT?

**Review by NoResponseMate — APPROVED** [review]

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thanks, Łukasz! :1st_place_medal:
