### PR TITLE
Bugfix/fix autocomplete in admin to be case insensitive

### LINKED ISSUE #18384: Making autocomplete case-insensitive on Postgres
### Description

Postgres is case sensitive in queries by default, whereas MySQL is not. So if you're using Postgres as your database for Sylius and you search something in an autocomplete field (products or taxons for example) then it only finds results matching the exact casing you've used in your search.

This could be fixed by adding `lower()` functions in `Sylius\Bundle\AdminBundle\Form\Type\TranslatableAutocompleteType`.

Maybe you would want this as a configuration option; I'm not sure what the performance impact would be on large databases with MySQL for example.

### Example

In `src/Sylius/Bundle/AdminBundle/Form/Type/TranslatableAutocompleteType.php`:

```php
<?php
...
final class TranslatableAutocompleteType extends AbstractType
{
...
    private static function getComparisons(Expr $expr, array $fields): iterable
    {
        foreach ($fields as $field) {
            yield $expr->like($expr->lower($field), 'LOWER(:query)');
        }
    }
}
```

### PR DESCRIPTION
**Pull request by michalkaczmarek-bitbag**
This is a continuation of pull request https://github.com/Sylius/Sylius/pull/18477
| Q               | A
|-----------------|-----
| Branch?         | 2.1
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | https://github.com/Sylius/Sylius/issues/18384
| License         | MIT

## Summary by CodeRabbit

* **Bug Fixes**
  * Parent taxon autocomplete search is now case-insensitive for more reliable results.

* **New Features**
  * Admin taxon form returns richer autocomplete results for parent selection.
  * Added UI actions to search and verify parent taxon results.
  * Support for creating taxons with explicit codes where needed.

* **Tests**
  * New BDD tests covering case-insensitive parent taxon autocomplete and related scenarios.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php [hunk 1]
```diff
@@ -230,6 +231,16 @@ public function theTaxonShouldAppearInTheRegistry(TaxonInterface $taxon): void
         Assert::same($this->formElement->getCode(), $taxon->getCode());
     }
 
+    /**
+     * @Given /^I search for parent taxon "([^"]*)"$/
+     */
+    public function iSearchForParentTaxon(string $searchTerm)
```
Comment (Rafikooo) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php]:
```suggestion
    public function iSearchForParentTaxon(string $searchTerm): void
```

File: src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php [hunk 2]
```diff
@@ -230,6 +231,16 @@ public function theTaxonShouldAppearInTheRegistry(TaxonInterface $taxon): void
...
+    {
+        $this->sharedStorage->set('autocompleteSearchResults', $this->formElement->searchParentTaxon($searchTerm));
```
Comment (Rafikooo) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php:237]: searchParentTaxon called twice

File: src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php [hunk 3]
```diff
@@ -487,4 +498,20 @@ public function itShouldBeDisabled(): void
     {
         Assert::false($this->formElement->isEnabled());
     }
+
+    /**
+     * @Then /^I should see "([^"]*)" in the found results$/
+     */
+    public function iShouldSeeInTheFoundResults(string $taxonName)
```
Comment (Rafikooo) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php]:
```suggestion
    public function iShouldSeeInTheFoundResults(string $taxonName): void
```

File: src/Sylius/Behat/Element/Admin/Taxon/FormElement.php [hunk 4]
```diff
@@ -141,4 +141,17 @@ protected function expandTranslationAccordion(string $localeCode): void
...
     }
+
+    public function searchParentTaxon(string $searchTerm): array
+    {
+        DriverHelper::waitForPageToLoad($this->getSession());
+
+        $searchResults = $this->autocompleteHelper->search(
+            $this->getDriver(),
+            $this->getElement('parent')->getXpath(),
+            $searchTerm
```
Comment (Rafikooo) [inline src/Sylius/Behat/Element/Admin/Taxon/FormElement.php]:
```suggestion
            $searchTerm,
```

**Review by TheMilek — APPROVED** [review]
