### PR TITLE
Fix migration

### LINKED ISSUE #11592: An existing migration is blocking future migrations
**Sylius version affected**: **since 1.1.0**

**Description**  
If you add a field using annotations to the ProductAttribute entity then you end up with an error during migrations.
Here I've added a `filterable` field and I get this:

image

This is caused because we ask doctrine to load the attributes during a migration:
https://github.com/Sylius/Sylius/blob/f08c3bf8f70e8f13da1ca3efa8440846297f0c76/app/migrations/Version20171003103916.php

**Steps to reproduce**  

Add a field to your entity, generate the migration and migrate the database from the beginning.

**Possible Solution**  

Using a specific method of the Repository, limiting the fields to select.

```php
    public function findByTypeForMigration(string $type)
    {
        return $this
            ->createQueryBuilder('o')
            ->select([
                'o.id',
                'o.code',
                'o.type',
                'o.storageType',
                'o.configuration',
                'o.createdAt',
                'o.updatedAt',
                'o.position'
            ])
            ->where('o.type = :type')
            ->setParameter('type', $type)
            ->getQuery()
            ->getResult()
        ;
    }
```

### PR DESCRIPTION
**Pull request by jacquesbh**
_Previous title: Add method findTypeForMigration to ProductAttributeRepository_

| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #11592
| License         | MIT

I don't know how to test these except by running the database migrations.  
So…

I've added the repository in Core because I think it is where it belongs since
the Migrations are in the main App.

### CODE REVIEW

File: app/migrations/Version20171003103916.php [hunk 1]
```diff
@@ -37,7 +37,7 @@ public function up(Schema $schema): void
         $defaultLocale = $this->container->getParameter('locale');
         $productAttributeRepository = $this->container->get('sylius.repository.product_attribute');
 
-        $productAttributes = $productAttributeRepository->findBy(['type' => SelectAttributeType::TYPE]);
+        $productAttributes = $productAttributeRepository->findByTypeForMigration(SelectAttributeType::TYPE);
```
Comment (lchrusciel) [inline app/migrations/Version20171003103916.php:40]: Despite the typehint, from the repository, you can fetch query builder. Therefore, I would say it would be better to just write custom method only in this migration file rather than place it in generally available place

Comment (jacquesbh) [reply app/migrations/Version20171003103916.php]: Yep. Much easier, you perfectly right. I've done the change.

**Comment by lchrusciel** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "fix-migration"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by lchrusciel** [comment]
Thank you, Jacques! :1st_place_medal:
