### PR TITLE
Fix ChannelCollector related serialization issue in Symfony profiler

### LINKED ISSUE #10223: Issue with the "Profiler"
**Sylius version affected**: 1.4.1 (and probably 1.3.x)

**Description**  
Got issue with the symfony/web-profiler-bundle: "An error occurred while loading the web debug toolbar, on a fresh install.

On a fresh install of Symfony with some "simple" entities, I don't have the issues.

For the "payload" below, the exact error was: 

> Notice: unserialize(): Error at offset 1345 of 2296 bytes

```php
ErrorException
in vendor/symfony/http-kernel/DataCollector/DataCollector.php (line 53)
DataCollector->unserialize('a:3:{s:7:"channel";O:26:"App\\Entity\\Channel\\Channel":21:{s:15:"' . "\0" . '*' . "\0" . 'baseCurrency";O:28:"App\\Entity\\Currency\\Currency":4:{s:5:"' . "\0" . '*' . "\0" . 'id";i:1;s:7:"' . "\0" . '*' . "\0" . 'code";s:3:"EUR";s:12:"' . "\0" . '*' . "\0" . 'createdAt";O:8:"DateTime":3:{s:4:"date";s:26:"2019-03-11 19:56:33.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}s:12:"' . "\0" . '*' . "\0" . 'updatedAt";O:8:"DateTime":3:{s:4:"date";s:26:"2019-03-11 19:56:33.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}}s:16:"' . "\0" . '*' . "\0" . 'defaultLocale";O:24:"App\\Entity\\Locale\\Locale":4:{s:5:"' . "\0" . '*' . "\0" . 'id";i:1;s:7:"' . "\0" . '*' . "\0" . 'code";s:5:"en_US";s:12:"' . "\0" . '*' . "\0" . 'createdAt";O:8:"DateTime":3:{s:4:"date";s:26:"2019-03-11 19:56:33.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}s:12:"' . "\0" . '*' . "\0" . 'updatedAt";O:8:"DateTime":3:{s:4:"date";s:26:"2019-03-11 19:56:33.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}}s:17:"' . "\0" . '*' . "\0" . 'defaultTaxZone";N;s:25:"' . "\0" . '*' . "\0" . 'taxCalculationStrategy";s:17:"order_items_based";s:13:"' . "\0" . '*' . "\0" . 'currencies";O:33:"Doctrine\\ORM\\PersistentCollection":2:{s:13:"' . "\0" . '*' . "\0" . 'collection";O:43:"Doctrine\\Common\\Collections\\ArrayCollection":1:{s:53:"' . "\0" . 'Doctrine\\Common\\Collections\\ArrayCollection' . "\0" . 'elements";a:1:{i:0;r:29456;}}s:14:"' . "\0" . '*' . "\0" . 'initialized";b:1;}s:10:"' . "\0" . '*' . "\0" . 'locales";O:33:"Doctrine\\ORM\\PersistentCollection":2:{s:13:"' . "\0" . '*' . "\0" . 'collection";O:43:"Doctrine\\Common\\Collections\\ArrayCollection":1:{s:53:"' . "\0" . 'Doctrine\\Common\\Collections\\ArrayCollection' . "\0" . 'elements";a:1:{i:0;r:29467;}}s:14:"' . "\0" . '*' . "\0" . 'initialized";b:1;}s:12:"' . "\0" . '*' . "\0" . 'themeName";N;s:15:"' . "\0" . '*' . "\0" . 'contactEmail";N;s:30:"' . "\0" . '*' . "\0" . 'skippingShippingStepAllowed";b:0;s:29:"' . "\0" . '*' . "\0" . 'skippingPaymentStepAllowed";b:0;s:30:"' . "\0" . '*' . "\0" . 'accountVerificationRequired";b:1;s:18:"' . "\0" . '*' . "\0" . 'shopBillingData";O:58:"Proxies\\__CG__\\Sylius\\Component\\Core\\Model\\ShopBillingData":8:{s:17:"__isInitialized__";b:0;s:5:"' . "\0" . '*' . "\0" . 'id";i:1;s:10:"' . "\0" . '*' . "\0" . 'company";N;s:8:"' . "\0" . '*' . "\0" . 'taxId";N;s:14:"' . "\0" . '*' . "\0" . 'countryCode";N;s:9:"' . "\0" . '*' . "\0" . 'street";N;s:7:"' . "\0" . '*' . "\0" . 'city";N;s:11:"' . "\0" . '*' . "\0" . 'postcode";N;}s:5:"' . "\0" . '*' . "\0" . 'id";i:1;s:7:"' . "\0" . '*' . "\0" . 'code";s:7:"default";s:7:"' . "\0" . '*' . "\0" . 'name";s:7:"Default";s:14:"' . "\0" . '*' . "\0" . 'description";N;s:11:"' . "\0" . '*' . "\0" . 'hostname";N;s:8:"' . "\0" . '*' . "\0" . 'color";N;s:12:"' . "\0" . '*' . "\0" . 'createdAt";O:8:"DateTime":3:{s:4:"date";s:26:"2019-03-11 19:56:33.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}s:12:"' . "\0" . '*' . "\0" . 'updatedAt";O:8:"DateTime":3:{s:4:"date";s:26:"2019-03-11 19:56:33.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}s:10:"' . "\0" . '*' . "\0" . 'enabled";b:1;}s:8:"channels";a:1:{i:0;r:29455;}s:22:"channel_change_support";b:1;}')
in vendor/symfony/http-kernel/Profiler/FileProfilerStorage.phpunserialize (line 285)
in vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php->createProfileFromData (line 122)
in vendor/symfony/http-kernel/Profiler/Profiler.php->read (line 86)
in vendor/symfony/web-profiler-bundle/Controller/ProfilerController.php->loadProfile (line 143)
in vendor/symfony/http-kernel/HttpKernel.php->toolbarAction (line 150)
in vendor/symfony/http-kernel/HttpKernel.php->handleRaw (line 67)
in vendor/symfony/http-kernel/Kernel.php->handle (line 198)
Kernel->handle(object(Request)) in public/index.php (line 25)
in /Users/gounlaf/.composer/vendor/laravel/valet/server.php require (line 158)
```

**Steps to reproduce**  
1. Do a fresh install
2. Open the web application
3. Notice that calls to web profiler produce errors 500.

**Possible Solution**  

I don't know if it's related:
- to the profiler itself
- to the way Sylius declare/map Entities

Regards,

### PR DESCRIPTION
**Pull request by ostrolucky**
| Q               | A
| --------------- | -----
| Branch?         | 1.4
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | unlikely, but possible
| Deprecations?   | no
| Related tickets | fixes #10223
| License         | MIT

This is very annoying long standing issue.

I'm pretty sure this will fix the issue (it does in our case). As a side effect, this is more efficient, as there is less data needed to be serialized. 

This issue is related to circular references inside Channel model. In our case we can reproduce with

```php
$n = new Channel();
$locale = new Locale();

$n->addLocale($locale);
$n->setDefaultLocale($locale);

$this->data = [
    'channel' => null,
    'channels' => [$n],
    'channel_change_support' => $channelChangeSupport,
];
```

inside ChannelCollector

I'm aware changing return type is technically BC break, but it's unlikely somebody uses this class. If this is an issue, please advise how to continue.

### CODE REVIEW

File: src/Sylius/Bundle/ChannelBundle/Collector/ChannelCollector.php [hunk 1]
```diff
@@ -35,12 +35,12 @@ public function __construct(
...
         $this->data = [
             'channel' => null,
-            'channels' => $channelRepository->findAll(),
+            'channels' => array_map([$this, 'pluckChannel'], $channelRepository->findAll()),
             'channel_change_support' => $channelChangeSupport,
         ];
     }
 
-    public function getChannel(): ?ChannelInterface
+    public function getChannel(): array
```
Comment (pamil) [inline src/Sylius/Bundle/ChannelBundle/Collector/ChannelCollector.php]: It should be `?array`, in case the current channel could not be resolved.

Comment (ostrolucky) [reply src/Sylius/Bundle/ChannelBundle/Collector/ChannelCollector.php]: good point, fixed
