### PR TITLE
user provider fix exception

### LINKED ISSUE #10879: [BUG] UserProvider should throw UnsupportedUserException and not UnexpectedValueException
**Sylius version affected**: 1.6.2

**Description**  
When using different user providers with multiple firewall contexts and some are outside the Sylius-User Provider scope then a `refreshUser` can throw (depending on which UserProviders are registered first and if they provide a user or not) an UnexpectedValueException as Symfony checks all UserProviders when calling `refreshUser`.

If the user is not supported, Symfony expects a `UnsupportedUserException` where they would try the next provider and they throw their own exception if no provider supports the user.
See also: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L174

**Steps to reproduce**  
see above.

**Possible Solution**  
Instead of `Assert::instanceOf` at https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UserBundle/Provider/AbstractUserProvider.php#L71
(refreshUser of the AbstractUserProvider).
Do an instanceof check and throw an `\Symfony\Component\Security\Core\Exception\UnsupportedUserException` instead.

### PR DESCRIPTION
**Pull request by oallain**
| Q               | A
| --------------- | -----
| Branch?         | 1.5 and more
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #10879 
| License         | MIT

UserProvider should throw UnsupportedUserException and not UnexpectedValueException.

### CODE REVIEW

File: src/Sylius/Bundle/UserBundle/Provider/AbstractUserProvider.php [hunk 1]
```diff
@@ -67,8 +66,11 @@ public function loadUserByUsername($username): UserInterface
      */
     public function refreshUser(UserInterface $user): UserInterface
     {
-        /** @var SyliusUserInterface $user */
-        Assert::isInstanceOf($user, SyliusUserInterface::class);
+        if(!$user instanceof SyliusUserInterface) {
```
Comment (lchrusciel) [inline src/Sylius/Bundle/UserBundle/Provider/AbstractUserProvider.php]: I'm wondering if it shouldn't be part of `supportsClass` function

Comment (oallain) [reply src/Sylius/Bundle/UserBundle/Provider/AbstractUserProvider.php]: I don't believe, `supportsClass` does not have the same purpose.

**Comment by lchrusciel** [comment]
Should be targeted to 1.6 I suppose. 

We've dropped support for 1.5

**Comment by Zales0123** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "user-provider-fix-exception"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by lchrusciel** [comment]
Thanks, @oallain! :tada:
