### PR TITLE
Fix "jumping" taxons while moving up or down

### LINKED ISSUE #9909: Updating taxon position not work properly
**Sylius version affected**: 1.3.3

**Description**  
Using leaf nodes up and down not position the taxon correctly

**Steps to reproduce**  
Create taxons and use the leaf nodes.

**Possible Solution**  
Not investigated yet.

captura de pantalla de 2018-11-08 14-54-22

### PR DESCRIPTION
**Pull request by jakubtobiasz**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #9909, based on #11905
| License         | MIT

Basing on #11905 I removed the "feature" part, to merge the "bug-fixing" part into `1.12`. We'll consider later adding "Move top" and "Move end" features, but probably it'll be considered in terms of `2.0` with the new Admin Panel.

Thanks @igormukhingmailcom for your work! I'm happy we're finally going to merge your commits :).

Previously:
CleanShot 2023-09-05 at 15 37 49

Now:
CleanShot 2023-09-05 at 15 39 33

### CODE REVIEW

**Review by SzymonFilipek — DISMISSED** [review]
Changes passed QA check

File: src/Sylius/Component/Taxonomy/Positioner/TaxonPositioner.php [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+    private function swapTaxonPositions(TaxonInterface $firstTaxon, TaxonInterface $secondTaxon): void
+    {
+        $firstTaxonPosition = $firstTaxon->getPosition();
+        $secondTaxonPosition = $secondTaxon->getPosition();
+
+        $firstTaxon->setPosition($secondTaxonPosition);
+        $secondTaxon->setPosition($firstTaxonPosition);
+
+        $this->taxonManager->persist($firstTaxon);
+        $this->taxonManager->persist($secondTaxon);
```
Comment (igormukhingmailcom) [inline src/Sylius/Component/Taxonomy/Positioner/TaxonPositioner.php]: Persisting not required here, as entities are not new.

File: src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php [hunk 2]
```diff
@@ -166,4 +166,54 @@ protected function createTranslationBasedQueryBuilder(?string $locale): QueryBui
...
+            ->getQuery()
+            ->getOneOrNullResult()
+        ;
+    }
+
+    public function findOneBelow(TaxonInterface $taxon): ?TaxonInterface
+    {
+        $query = $this->createQueryBuilder('o');
+
+        if ($taxonParent = $taxon->getParent()) {
```
Comment (igormukhingmailcom) [inline src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php]: `if (null !== ($taxonParent = $taxon->getParent())) {`

File: src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php [hunk 3]
```diff
@@ -166,4 +166,54 @@ protected function createTranslationBasedQueryBuilder(?string $locale): QueryBui
 
         return $queryBuilder;
     }
+
+    public function findOneAbove(TaxonInterface $taxon): ?TaxonInterface
+    {
+        $query = $this->createQueryBuilder('o');
+
+        if ($taxonParent = $taxon->getParent()) {
```
Comment (igormukhingmailcom) [inline src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php]: `if (null !== ($taxonParent = $taxon->getParent())) {`

**Comment by igormukhingmailcom** [comment]
Thanks for the fixes, @jakubtobiasz :)

**Comment by ehibes** [comment]
Hi guys,
Why not use nested set behavior for taxons position ? It’s already implemented on database...  otherwise I don't see what use it would be.
#7585 this issue is about it too.

**Comment by jakubtobiasz** [comment]
Hi @ehibes 👋🏼,
thanks for sharing your thoughts. This PR aims to fix the existing behavior, the issue you share might be considered in a longer term (e.g. Sylius `2.0` or `3.0` as it might require analysis + refactoring and changes in the behavior).

**Comment by jakubtobiasz** [comment]
Thanks for leaving the review @igormukhingmailcom 😅

File: src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php [hunk 4]
```diff
@@ -144,6 +144,12 @@ public function getFirstTaxonOnTheList(): string
         return $this->getLeaves()[0]->getText();
     }
 
+    public function getLastTaxonOnTheList(): string
+    {
+        $leaves = $this->getLeaves();
+        return $leaves[count($leaves) - 1]->getText();
```
Comment (GSadee) [inline src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php]:
```suggestion
        $leaves = $this->getLeaves();

        return $leaves[count($leaves) - 1]->getText();
```

File: src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/taxon.yml [hunk 5]
```diff
@@ -69,3 +69,21 @@ sylius_admin_ajax_taxon_move:
         _sylius:
             permission: true
             form: Sylius\Bundle\TaxonomyBundle\Form\Type\TaxonPositionType
+
+sylius_admin_ajax_taxon_move_up:
+    path: /{id}/move/up
```
Comment (GSadee) [inline src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/taxon.yml]:
```suggestion
    path: /{id}/move-up
```
🤔

File: src/Sylius/Component/Taxonomy/Positioner/TaxonPositioner.php [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+final class TaxonPositioner implements TaxonPositionerInterface
+{
+    public function __construct (
+        private TaxonRepositoryInterface $taxonRepository,
+    ) {
+    }
+
+    public function moveUp(TaxonInterface $taxon): void
+    {
+        $taxonAbove = $this->taxonRepository->findOneAbove($taxon);
```
Comment (GSadee) [inline src/Sylius/Component/Taxonomy/Positioner/TaxonPositioner.php]: Is this taking one above (or below) taxon really needed here? We could only check the current position of the taxon and properly change it here without getting the one from db.

If I see correctly, the only problem that was with the earlier implementation was that when modifying the position at move up, we subtracted by making the position -1 when the taxon had 0 before and it was moved to the end. All that was really needed was to check the existing position before modifying even in JS, and that should work 🤔.

File: src/Sylius/Component/Taxonomy/spec/Positioner/TaxonPositionerSpec.php [hunk 7]
```diff
@@ -0,0 +1,87 @@
...
+        $taxonToBeMoved->getPosition()->willReturn(1);
+        $taxonAbove->getPosition()->willReturn(0);
+
+        $taxonToBeMoved->setPosition(0)->shouldBeCalled();
+        $taxonAbove->setPosition(1)->shouldBeCalled();
+
+        $this->moveUp($taxonToBeMoved);
+    }
+
+    public function it_should_do_nothing_when_taxon_above_does_not_exist(
```
Comment (GSadee) [inline src/Sylius/Component/Taxonomy/spec/Positioner/TaxonPositionerSpec.php]:
```suggestion
    public function it_does_nothing_when_taxon_above_does_not_exist(
```

File: src/Sylius/Component/Taxonomy/spec/Positioner/TaxonPositionerSpec.php [hunk 8]
```diff
@@ -0,0 +1,87 @@
...
+        $taxonToBeMoved->getPosition()->willReturn(0);
+        $taxonBelow->getPosition()->willReturn(1);
+
+        $taxonToBeMoved->setPosition(1)->shouldBeCalled();
+        $taxonBelow->setPosition(0)->shouldBeCalled();
+
+        $this->moveDown($taxonToBeMoved);
+    }
+
+    public function it_should_do_nothing_when_taxon_below_does_not_exist(
```
Comment (GSadee) [inline src/Sylius/Component/Taxonomy/spec/Positioner/TaxonPositionerSpec.php]:
```suggestion
    public function it_does_nothing_when_taxon_below_does_not_exist(
```

File: src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php [hunk 9]
```diff
@@ -0,0 +1,56 @@
+<?php
+
+/*
+ * This file is part of the Sylius package.
+ *
+ * (c) Paweł Jędrzejewski
```
Comment (diimpp) [inline src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php]:
```patch
--- (c) Paweł Jędrzejewski
+++ (c) Sylius Sp. z o.o.
```

File: src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php [hunk 10]
```diff
@@ -166,4 +166,56 @@ protected function createTranslationBasedQueryBuilder(?string $locale): QueryBui
...
+            $query
+                ->andWhere('o.parent IS NULL')
+            ;
+        }
+
+        return $query
+            ->andWhere('o.position < :taxonPosition')
+            ->setParameter('taxonPosition', $taxon->getPosition())
+            ->addOrderBy('o.position', 'DESC')
+            ->setMaxResults(1)
```
Comment (diimpp) [inline src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php]: Is it necessary in presence of `getOneOrNullResult`? Which will throw exception like so

```php
        if (count($result) > 1) {
            throw new NonUniqueResultException();
        }
```

File: src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php [hunk 11]
```diff
@@ -166,4 +166,56 @@ protected function createTranslationBasedQueryBuilder(?string $locale): QueryBui
...
+            $query
+                ->andWhere('o.parent IS NULL')
+            ;
+        }
+
+        return $query
+            ->andWhere('o.position > :taxonPosition')
+            ->setParameter('taxonPosition', $taxon->getPosition())
+            ->addOrderBy('o.position', 'ASC')
+            ->setMaxResults(1)
```
Comment (diimpp) [inline src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php]: Same question

File: src/Sylius/Bundle/TaxonomyBundle/Resources/config/services.xml [hunk 12]
```diff
@@ -26,6 +26,11 @@
             <argument type="service" id="sylius.factory.taxon" />
         </service>
 
+        <service id="sylius.controller.taxon_position" class="Sylius\Bundle\TaxonomyBundle\Controller\TaxonPositionController">
+            <argument type="service" id="sylius.repository.taxon" />
+            <argument type="service" id="doctrine.orm.entity_manager" />
```
Comment (diimpp) [inline src/Sylius/Bundle/TaxonomyBundle/Resources/config/services.xml]:
```patch
--- id="doctrine.orm.entity_manager"
+++ id="sylius.manager.taxon"
```

File: src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php [hunk 13]
```diff
@@ -0,0 +1,56 @@
...
+{
+    public function __construct(
+        private TaxonRepositoryInterface $taxonRepository,
+        private ObjectManager $taxonManager,
+    ) {
+    }
+
+    public function moveUpAction(int $id): Response
+    {
+        /** @var TaxonInterface|null $taxonToBeMoved */
```
Comment (diimpp) [inline src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php]: I've no preferences on this, but this alternative should be working in terms of unneeded docblock.
```patch
---      /** @var TaxonInterface|null $taxonToBeMoved */
---      $taxonToBeMoved = $this->taxonRepository->find($id);
---      Assert::notNull($taxonToBeMoved);
+++      $taxonToBeMoved = $this->taxonRepository->find($id);
+++      Assert::nullOrIsInstanceOf($taxonToBeMoved, TaxonInterface::class);
 ```

File: src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php [hunk 14]
```diff
@@ -0,0 +1,56 @@
...
+            $taxonToBeMoved->setPosition($taxonToBeMoved->getPosition() - 1);
+        }
+        $this->taxonManager->flush();
+
+        return new JsonResponse();
+    }
+
+    public function moveDownAction(int $id): Response
+    {
+        /** @var TaxonInterface|null $taxonToBeMoved */
```
Comment (diimpp) [inline src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php]: Same

File: src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php [hunk 15]
```diff
@@ -166,4 +166,56 @@ protected function createTranslationBasedQueryBuilder(?string $locale): QueryBui
 
         return $queryBuilder;
     }
+
+    public function findOneAbove(TaxonInterface $taxon): ?TaxonInterface
```
Comment (diimpp) [inline src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php]: This new repository method is not used anywhere in the codebase

File: src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php [hunk 16]
```diff
@@ -166,4 +166,56 @@ protected function createTranslationBasedQueryBuilder(?string $locale): QueryBui
...
+            ->andWhere('o.position < :taxonPosition')
+            ->setParameter('taxonPosition', $taxon->getPosition())
+            ->addOrderBy('o.position', 'DESC')
+            ->setMaxResults(1)
+            ->getQuery()
+            ->getOneOrNullResult()
+        ;
+    }
+
+    public function findOneBelow(TaxonInterface $taxon): ?TaxonInterface
```
Comment (diimpp) [inline src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php]: This new repository method is not used anywhere in the codebase

**Review by diimpp — CHANGES_REQUESTED** [review]
New repository methods are unused anywhere in the codebase

File: src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php (hunk 13 above)
Comment (jakubtobiasz) [reply src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php]: PHPStorm stops providing suggestions in that case :( (I replace `nullOrIsInstanceOf` with `isInstanceOf` as it's the correct one).

File: src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php (hunk 14 above)
Comment (jakubtobiasz) [reply src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php]: PHPStorm stops providing suggestions in that case :( (I replace `nullOrIsInstanceOf` with `isInstanceOf` as it's the correct one).

File: src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php (hunk 10 above)
Comment (jakubtobiasz) [reply src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php]: I wanted to eliminate a need to handle the exception.

File: src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php (hunk 11 above)
Comment (jakubtobiasz) [reply src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php]: I wanted to eliminate a need to handle the exception.

File: src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php [hunk 17]
```diff
@@ -0,0 +1,56 @@
...
+    public function __construct(
+        private TaxonRepositoryInterface $taxonRepository,
+        private ObjectManager $taxonManager,
+    ) {
+    }
+
+    public function moveUpAction(int $id): Response
+    {
+        /** @var TaxonInterface|null $taxonToBeMoved */
+        $taxonToBeMoved = $this->taxonRepository->find($id);
```
Comment (diimpp) [inline src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php]: It would be good to handle not found error in similar way as it's done at [AdminBundle](https://github.com/Sylius/Sylius/blob/c3b913cda2467e4d2db40535395f1282fb6d7ebc/src/Sylius/Bundle/AdminBundle/Controller/CustomerStatisticsController.php#L41-L47)

```php
        $customer = $this->customerRepository->find($customerId);
        if (null === $customer) {
            throw new HttpException(
                Response::HTTP_BAD_REQUEST,
                sprintf('Customer with id %s doesn\'t exist.', (string) $customerId),
            );
        }
```
Sorry, missed it at first review.

File: src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php [hunk 18]
```diff
@@ -0,0 +1,56 @@
...
+        Assert::isInstanceOf($taxonToBeMoved);
+
+        if ($taxonToBeMoved->getPosition() > 0) {
+            $taxonToBeMoved->setPosition($taxonToBeMoved->getPosition() - 1);
+            $this->taxonManager->flush();
+        }
+
+        return new JsonResponse();
```
Comment (diimpp) [inline src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonPositionController.php]: Optional nitpicking :) 
```patch
--- return new JsonResponse();
+++ return new JsonResponse('', Response::HTTP_NO_CONTENT);
```

File: src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_treeWithButtons.html.twig [hunk 19]
```diff
@@ -34,10 +34,10 @@
 
                                     <div class="divider"></div>
 
-                                    <div class="item sylius-taxon-move-up" data-url="{{ path('sylius_admin_ajax_taxon_move', { id: taxon.id }) }}" data-id="{{ taxon.id }}" data-position="{{ taxon.position }}">
+                                    <div class="item sylius-taxon-move-up" data-url="{{ path('sylius_admin_ajax_taxon_move_up', { id: taxon.id }) }}">
```
Comment (diimpp) [inline src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_treeWithButtons.html.twig:37]: It might be worth mentioning in UPGRADE as functionality will break for anyone with overridden template

**Comment by igormukhingmailcom** [comment]
Is this works?

```
$taxonToBeMoved->setPosition($taxonToBeMoved->getPosition() - 1);
```

It just doing the same `-1` as we had before (when things did not work), but on backend side rather than on front-end side - that is all the difference. Did someone tested this by hands?

**Comment by jakubtobiasz** [comment]
@igormukhingmailcom 
CleanShot 2023-09-13 at 14 41 10
There's an if statement preventing moving the taxon to `-1` positions. Behat tests are passing that way, and we tested it yesterday.

File: src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_treeWithButtons.html.twig (hunk 19 above)
Comment (jakubtobiasz) [reply src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_treeWithButtons.html.twig:37]: Good idea, added.

**Review by diimpp — APPROVED** [review]

File: features/taxonomy/managing_taxons/reordering_taxon.feature [hunk 20]
```diff
@@ -24,6 +24,20 @@ Feature: Reordering taxons
         And I should see the taxon named "Watches" in the list
         But the first taxon on the list should be "Watches"
 
+    @ui @javascript
+    Scenario: Moving up the first taxon on list
+        When I want to see all taxons in store
+        And I move up "T-Shirts" taxon
+        Then I should see 4 taxons on the list
+        And the first taxon on the list should be "T-Shirts"
```
Comment (GSadee) [inline features/taxonomy/managing_taxons/reordering_taxon.feature:32]:
```suggestion
        And the first taxon on the list should still be "T-Shirts"
```
This would describe the behaviour even better, the same in the below scenario

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you, Jacob! :1st_place_medal:
