### PR TITLE
[ApiBundle][Image] Prevent resolving non-serialized image paths

### LINKED ISSUE #16294: [Api] `Serializer\ImageSerializer` missing `$data['path']` check
**Sylius version affected**: 1.13

**Description**  
Potential hard to debug place, which can be solved with extra assert.

`ImageNormalizer` operates on assumption, that serialized image will have `path` array element, at the same time `ImageInterface` is commonly used by end-users and serialization of their custom images is up to them, hence presence of `path` is not guaranteed. 

https://github.com/Sylius/Sylius/blob/89bd5e320982faba5a82e9f6fa59a2aaf79ff530/src/Sylius/Bundle/ApiBundle/Serializer/ImageNormalizer.php#L74-L78

**Steps to reproduce**
1. Implement new `CoolImage implements ImageInterface`.
2. Expose `CoolImage` as serialized resource in APIP based api endpoint, but don't serialize `path`.
3. Receive error about "Path is undefined" instead of empty api output. 

**Possible Solution**  

```patch
+++     Assert::notEmpty($data['path], 'Image must have "path" serialized.');
        try {
            return $this->cacheManager->getBrowserPath(parse_url($data['path'], \PHP_URL_PATH), $filter);
        } catch (NonExistingFilterException|\OutOfBoundsException) {
            throw new InvalidArgumentException(sprintf('Filter "%s" is not configured.', $filter));
        }
```
or

```patch
+++     if (empty($data['path])) {
+++         return '';
+++     }
        try {
            return $this->cacheManager->getBrowserPath(parse_url($data['path'], \PHP_URL_PATH), $filter);
        } catch (NonExistingFilterException|\OutOfBoundsException) {
            throw new InvalidArgumentException(sprintf('Filter "%s" is not configured.', $filter));
        }
```

### PR DESCRIPTION
**Pull request by Wojdylak**
| Q               | A
|-----------------|-----
| Branch?         | 1.13
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #16294
| License         | MIT

### CODE REVIEW

**Review by mpysiak — DISMISSED** [review]

File: src/Sylius/Bundle/ApiBundle/Serializer/ImageNormalizer.php [hunk 1]
```diff
@@ -40,7 +40,7 @@ public function __construct(
 
     public function normalize($object, $format = null, array $context = [])
     {
-        Assert::isInstanceOf($object, ImageInterface::class);
+        Assert::isInstanceOf($object, Image::class);
```
Comment (GSadee) [inline src/Sylius/Bundle/ApiBundle/Serializer/ImageNormalizer.php]: I'm not sure if this change will resolve the initial problem, because still if `path` is not serialised then `$data['path']` will be empty, we should probably omit the `resolvePath` method when the path is not serialised and leave the interface as it was 🤔

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you, Karol! :1st_place_medal:
