### PR TITLE
[Theme] Support for fallback locales; integration tests for translation compiler passes

### LINKED ISSUE #4343: [Theme] Translator fallbacks not working
We're not using themes yet, I've just updated to master and fallback locales don't work. Is there something I need to configure?

0.16 (well about 4 weeks ago..):

image

master:

screen shot 2016-02-28 at 17 30 32

### PR DESCRIPTION
**Pull request by pamil**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #4343
| License         | MIT
| Doc PR          | -

### CODE REVIEW

File: src/Sylius/Bundle/ThemeBundle/Translation/DependencyInjection/Compiler/TranslatorFallbackLocalesPass.php [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+        } catch (\InvalidArgumentException $exception) {
+            return;
+        }
+
+        $methodCalls = array_filter($symfonyTranslator->getMethodCalls(), function (array $methodCall) {
+            return 'setFallbackLocales' === $methodCall[0];
+        });
+
+        foreach ($methodCalls as $methodCall) {
+            $syliusTranslator->addMethodCall($methodCall[0], $methodCall[1]);
```
Comment (peteward) [inline src/Sylius/Bundle/ThemeBundle/Translation/DependencyInjection/Compiler/TranslatorFallbackLocalesPass.php]: :+1:

**Comment by pjedrzejewski** [comment]
Thank you Kamil!

File: src/Sylius/Bundle/ThemeBundle/Translation/DependencyInjection/Compiler/TranslatorFallbackLocalesPass.php [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+ */
+final class TranslatorFallbackLocalesPass implements CompilerPassInterface
+{
+    /**
+     * {@inheritdoc}
+     */
+    public function process(ContainerBuilder $container)
+    {
+        try {
+            $symfonyTranslator = $container->findDefinition('translator.default');
```
Comment (stloyd) [inline src/Sylius/Bundle/ThemeBundle/Translation/DependencyInjection/Compiler/TranslatorFallbackLocalesPass.php]: Currious: why using `try/catch` instead of `has()` on container?

Comment (pamil) [inline src/Sylius/Bundle/ThemeBundle/Translation/DependencyInjection/Compiler/TranslatorFallbackLocalesPass.php]: I need that definition anyway.

Comment (michalmarcinkowski) [inline src/Sylius/Bundle/ThemeBundle/Translation/DependencyInjection/Compiler/TranslatorFallbackLocalesPass.php]: If you need that, why catching exception at all? Should we silence the exception?

Comment (pamil) [inline src/Sylius/Bundle/ThemeBundle/Translation/DependencyInjection/Compiler/TranslatorFallbackLocalesPass.php]: [Symfony documentation](http://symfony.com/doc/current/components/dependency_injection/compilation.html#prepending-configuration-passed-to-the-extension):

> Make sure your compiler pass does not require services to exist. Abort the method call if some required service is not available.

And `matthiasnoback/symfony-dependency-injection-test` [encourages to keep up with this practice](https://github.com/matthiasnoback/SymfonyDependencyInjectionTest#standard-test-for-unobtrusiveness):

> The AbstractCompilerPassTestCase class always executes one specific test - compilation_should_not_fail_with_empty_container() - which makes sure that the compiler pass is unobtrusive. For example, when your compiler pass assumes the existence of a service, an exception will be thrown, and this test will fail

Comment (michalmarcinkowski) [inline src/Sylius/Bundle/ThemeBundle/Translation/DependencyInjection/Compiler/TranslatorFallbackLocalesPass.php]: Ok, so it's not compiler pass responsibility :+1:
