### PR TITLE
[Admin][Promotion] Fix the prevention of generating too many coupons

### LINKED ISSUE #10795: [Promotion] Coupons generation check fails
**Sylius version affected**: 1.6, master

**Description** 
Before the coupons generation is some check mechanism that does not work properly. 

**Steps to reproduce** 
1. Create coupon based promotion (or edit one to coupon-based)
1. Go to the **Generate coupons** section
1. Enter **prefix**: _BRNO-_, **code length**: _1_
1. Enter the **amount** _8_ and generate it
1. Repeat the process 2 more times and you will get the **500**

**Possible Solution** 
Check the already generated coupons and give relevant notice to the user.
The check would not be so easy. It could be required to store additional data from coupon generation form to the database.

Btw the current check doesn't work properly - it shows 8 possible coupons when having code length 1, but the right result is 16 (0-9,A-E).

### PR DESCRIPTION
**Pull request by GSadee**
| Q               | A
| --------------- | -----
| Branch?         | 1.6
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #10795
| License         | MIT

### CODE REVIEW

File: src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php [hunk 1]
```diff
@@ -99,9 +99,9 @@ public function iWantToGenerateNewCouponsForThisPromotion(PromotionInterface $pr
      * @When /^I specify their code length as (\d+)$/
      * @When I do not specify their code length
      */
-    public function iSpecifyTheirCodeLengthAs($codeLength = null)
+    public function iSpecifyTheirCodeLengthAs(int $codeLength = null): void
```
Comment (pamil) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php]:
```suggestion
    public function iSpecifyTheirCodeLengthAs(?int $codeLength = null): void
```

File: src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php [hunk 2]
```diff
@@ -166,9 +166,9 @@ public function iChangeItsUsageLimitTo($limit)
      * @When I do not specify its amount
      * @When I choose the amount of :amount coupons to be generated
      */
-    public function iSpecifyItsAmountAs($amount = null)
+    public function iSpecifyItsAmountAs(int $amount = null): void
```
Comment (pamil) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php]:
```suggestion
    public function iSpecifyItsAmountAs(?int $amount = null): void
```

File: features/promotion/managing_coupons/being_unable_to_generate_too_many_coupons_with_prefix_and_suffix.feature [hunk 3]
```diff
@@ -0,0 +1,45 @@
+@managing_promotion_coupons
+Feature: Being unable to generate too many coupons with prefix and suffix
+    In order to avoid generating duplicated coupons for my promotions
+    As an Administrator
+    I want to be prevented from generating too many coupons with the same prefix or suffix
+
```
Comment (pamil) [inline features/promotion/managing_coupons/being_unable_to_generate_too_many_coupons_with_prefix_and_suffix.feature]: When I first read this scenario, I didn't understand why it's not possible to generate 2 more coupons if 8 are generated already.

What do you think about adding the following section before `Background`?

```gherkin
Rules:
    - Generated coupon code uses 16 characters (numbers from 0 to 9, letters from A to F)
    - To prevent guessing coupons codes, it is not allowed to generate more than 50% of possible coupons
```

File: src/Sylius/Bundle/PromotionBundle/Doctrine/ORM/PromotionCouponRepository.php [hunk 4]
```diff
@@ -45,6 +45,30 @@ public function countByCodeLength(int $codeLength): int
...
+        }
+        if ($suffix !== null) {
+            $codeLength += strlen($suffix);
+        }
+        $codeTemplate = $prefix . '%' . $suffix;
+
+        return (int) $this->createQueryBuilder('o')
+            ->select('COUNT(o.id)')
+            ->andWhere('LENGTH(o.code) = :codeLength')
+            ->andWhere('o.code LIKE :prefixAndSuffix')
```
Comment (pamil) [inline src/Sylius/Bundle/PromotionBundle/Doctrine/ORM/PromotionCouponRepository.php]: Personal preference, it brings more context into this query.

```suggestion
            ->andWhere('o.code LIKE :codeTemplate')
```

File: src/Sylius/Component/Promotion/Repository/PromotionCouponRepositoryInterface.php [hunk 5]
```diff
@@ -23,6 +23,12 @@ public function createQueryBuilderByPromotionId($promotionId): QueryBuilder;
 
     public function countByCodeLength(int $codeLength): int;
```
Comment (pamil) [inline src/Sylius/Component/Promotion/Repository/PromotionCouponRepositoryInterface.php]: I wonder whether we could merge the new method with this one (`countByCodeLength(5) === countByCodeLengthWithPrefixAndSuffix(5, null, null)`), but I'm not sure, just thinking out loud.

**Comment by pamil** [comment]
Thanks, Grzegorz! :tada:
