### PR TITLE
Replace behat/transliterator with symfony/string

### LINKED ISSUE #18944: Remove usage of `behat/transliterator`
### Sylius version(s) affected

2.*

### Description

The package `behat/transliterator` is abandoned.

> Package behat/transliterator is abandoned, you should avoid using it. No replacement was suggested.

### How to reproduce

Install a fresh Sylius-standard and this warning will be displayed among others.

### Possible Solution

Maybe consider using `symfony/string` instead.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by marekrzytki**
| Q               | A
|-----------------|-----
| Branch?         | 2.3
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | yes
| Deprecations?   | no
| Related tickets | fixes #18944
| License         | MIT

## Summary by CodeRabbit

* **New Features**
  * Slug generation now supports Symfony's Slugger (symfony/string) for improved transliteration.

* **Deprecated**
  * bêhat/transliterator marked deprecated for removal in Sylius 3.0.
  * Legacy slug helpers (including nameToSlug) deprecated in favor of Slugger-based generation; omitting the new slugger will be deprecated.

* **Tests**
  * Tests added/updated to cover slugger and fallback behaviors.

* **Documentation**
  * UPGRADE-2.3.md updated with migration notes and removal timeline.

### CODE REVIEW

File: src/Sylius/Component/Product/Generator/SlugGenerator.php [hunk 1]
```diff
@@ -13,15 +13,19 @@
...
 final class SlugGenerator implements SlugGeneratorInterface
 {
+    public function __construct(private SluggerInterface $slugger)
+    {
+    }
+
     public function generate(string $name): string
     {
         // Manually replacing apostrophes since Transliterator started removing them at v1.2.
         $name = str_replace('\'', '-', $name);
```
Comment (Prometee) [inline src/Sylius/Component/Product/Generator/SlugGenerator.php:41]: Is this still required ?

File: src/Sylius/Bundle/AdminBundle/Generator/TaxonSlugGenerator.php [hunk 2]
```diff
@@ -38,7 +40,6 @@ public function generate(string $name, string $localeCode, ?TaxonInterface $pare
 
     private function transliterate(string $string): string
     {
-        // Manually replacing apostrophes since Transliterator started removing them at v1.2.
-        return Transliterator::transliterate(str_replace('\'', '-', $string));
+        return $this->slugger->slug(str_replace('\'', '-', $string))->lower()->toString();
```
Comment (Prometee) [inline src/Sylius/Bundle/AdminBundle/Generator/TaxonSlugGenerator.php]: Is the `str_replace` still required ?

File: src/Sylius/Component/Taxonomy/Generator/TaxonSlugGenerator.php [hunk 3]
```diff
@@ -39,7 +43,6 @@ public function generate(TaxonInterface $taxon, ?string $locale = null): string
 
     private function transliterate(string $string): string
     {
-        // Manually replacing apostrophes since Transliterator started removing them at v1.2.
-        return Transliterator::transliterate(str_replace('\'', '-', $string));
+        return $this->slugger->slug(str_replace('\'', '-', $string))->lower()->toString();
```
Comment (Prometee) [inline src/Sylius/Component/Taxonomy/Generator/TaxonSlugGenerator.php]: Is the `str_replace` still required ?

**Review by Prometee — CHANGES_REQUESTED** [review]
Can we add a test with "'" character to see if the `str_replace` is still required ?

File: src/Sylius/Component/Product/Generator/SlugGenerator.php (hunk 1 above)
Comment (marekrzytki) [reply src/Sylius/Component/Product/Generator/SlugGenerator.php:41]: No, removed

File: src/Sylius/Bundle/AdminBundle/Generator/TaxonSlugGenerator.php (hunk 2 above)
Comment (marekrzytki) [reply src/Sylius/Bundle/AdminBundle/Generator/TaxonSlugGenerator.php]: No, removed

File: src/Sylius/Component/Taxonomy/Generator/TaxonSlugGenerator.php (hunk 3 above)
Comment (marekrzytki) [reply src/Sylius/Component/Taxonomy/Generator/TaxonSlugGenerator.php]: No, removed

**Review by Prometee — DISMISSED** [review]

File: src/Sylius/Bundle/AdminBundle/Generator/TaxonSlugGenerator.php [hunk 4]
```diff
@@ -13,14 +13,16 @@
...
 use Sylius\Component\Taxonomy\Generator\TaxonSlugGeneratorInterface as BaseTaxonSlugGeneratorInterface;
+use Symfony\Component\String\Slugger\SluggerInterface;
 
 final readonly class TaxonSlugGenerator implements TaxonSlugGeneratorInterface
 {
-    public function __construct(private BaseTaxonSlugGeneratorInterface $slugGenerator)
-    {
+    public function __construct(
+        private BaseTaxonSlugGeneratorInterface $slugGenerator,
+        private SluggerInterface $slugger
```
Comment (Rafikooo) [inline src/Sylius/Bundle/AdminBundle/Generator/TaxonSlugGenerator.php]: Shouldn't be nullable?

File: src/Sylius/Bundle/AdminBundle/Generator/TaxonSlugGenerator.php [hunk 5]
```diff
@@ -16,11 +16,22 @@
...
+        private BaseTaxonSlugGeneratorInterface $slugGenerator,
+        private ?SluggerInterface $slugger
+    ) {
+        if (null === $this->slugger) {
+            trigger_deprecation(
+                'sylius/sylius',
+                '2.3',
+                'Not passing $slugger through constructor is deprecated and will be prohibited in Sylius 3.0.',
+                self::class,
+            );
```
Comment (TheMilek) [inline src/Sylius/Bundle/AdminBundle/Generator/TaxonSlugGenerator.php:34]:
```suggestion
            trigger_deprecation(
                'sylius/admin-bundle',
                '2.3',
                'Not passing a "%s" to "%s" is deprecated and will be required in Sylius 3.0.',
                SluggerInterface:class,
                self::class,
            );
```

[Example](https://github.com/Sylius/Sylius/blob/2.3/src/Sylius/Bundle/ShopBundle/Locale/StorageBasedLocaleSwitcher.php)

File: src/Sylius/Bundle/AdminBundle/Generator/TaxonSlugGenerator.php [hunk 6]
```diff
@@ -16,11 +16,22 @@
...
 use Sylius\Component\Taxonomy\Generator\TaxonSlugGeneratorInterface as BaseTaxonSlugGeneratorInterface;
+use Symfony\Component\String\Slugger\SluggerInterface;
 
 final readonly class TaxonSlugGenerator implements TaxonSlugGeneratorInterface
 {
-    public function __construct(private BaseTaxonSlugGeneratorInterface $slugGenerator)
-    {
+    public function __construct(
+        private BaseTaxonSlugGeneratorInterface $slugGenerator,
+        private ?SluggerInterface $slugger
```
Comment (TheMilek) [inline src/Sylius/Bundle/AdminBundle/Generator/TaxonSlugGenerator.php]:
```suggestion
        private ?SluggerInterface $slugger = null
```

File: src/Sylius/Component/Core/Formatter/StringInflector.php [hunk 7]
```diff
@@ -35,6 +35,9 @@ public static function nameToProductCode(string $value): string
         return preg_replace('/[^\w-]/', '', $value) ?? '';
     }
 
+    /**
+     * @deprecated This method will be removed in 3.0 - use vendor/symfony/string/Slugger/SluggerInterface.php instead
```
Comment (TheMilek) [inline src/Sylius/Component/Core/Formatter/StringInflector.php]:
```suggestion
     * @deprecated This method will be removed in 3.0 - use Symfony\Component\String\Slugger\SluggerInterface::slug() instead
```
https://github.com/Sylius/Sylius/blob/1.14/src/Sylius/Bundle/OrderBundle/Controller/OrderController.php#L236-L238 as a example

File: src/Sylius/Component/Product/Generator/SlugGenerator.php [hunk 8]
```diff
@@ -14,11 +14,28 @@
...
+    public function __construct(private ?SluggerInterface $slugger)
+    {
+        if (null === $this->slugger) {
+            trigger_deprecation(
+                'sylius/sylius',
+                '2.3',
+                'Not passing $slugger through constructor is deprecated and will be prohibited in Sylius 3.0.',
+                self::class,
+            );
+        }
```
Comment (TheMilek) [inline src/Sylius/Component/Product/Generator/SlugGenerator.php]: same like above

File: src/Sylius/Component/Taxonomy/Generator/TaxonSlugGenerator.php [hunk 9]
```diff
@@ -15,10 +15,23 @@
...
+    public function __construct(private ?SluggerInterface $slugger)
+    {
+        if (null === $this->slugger) {
+            trigger_deprecation(
+                'sylius/sylius',
+                '2.3',
+                'Not passing $slugger through constructor is deprecated and will be prohibited in Sylius 3.0.',
+                self::class,
+            );
+        }
```
Comment (TheMilek) [inline src/Sylius/Component/Taxonomy/Generator/TaxonSlugGenerator.php]: as above

File: src/Sylius/Bundle/AdminBundle/Generator/TaxonSlugGenerator.php (hunk 6 above)
Comment (marekrzytki) [reply src/Sylius/Bundle/AdminBundle/Generator/TaxonSlugGenerator.php]: Fixed for all cases

File: src/Sylius/Component/Product/Generator/SlugGenerator.php [hunk 10]
```diff
@@ -14,11 +14,29 @@
...
 use Behat\Transliterator\Transliterator;
+use Symfony\Component\String\Slugger\SluggerInterface;
 
 final class SlugGenerator implements SlugGeneratorInterface
 {
+    public function __construct(private ?SluggerInterface $slugger = null)
+    {
+        if (null === $this->slugger) {
+            trigger_deprecation(
+                'sylius/sylius',
```
Comment (TheMilek) [inline src/Sylius/Component/Product/Generator/SlugGenerator.php]:
```suggestion
                'sylius/product',
```

File: src/Sylius/Component/Taxonomy/Generator/TaxonSlugGenerator.php [hunk 11]
```diff
@@ -15,10 +15,24 @@
...
+use Symfony\Component\String\Slugger\SluggerInterface;
 use Webmozart\Assert\Assert;
 
 final class TaxonSlugGenerator implements TaxonSlugGeneratorInterface
 {
+    public function __construct(private ?SluggerInterface $slugger = null)
+    {
+        if (null === $this->slugger) {
+            trigger_deprecation(
+                'sylius/sylius',
```
Comment (TheMilek) [inline src/Sylius/Component/Taxonomy/Generator/TaxonSlugGenerator.php]:
```suggestion
                'sylius/taxonomy',
```

**Review by TheMilek — DISMISSED** [review]

**Review by TheMilek — APPROVED** [review]
