### PR TITLE
Abstracts out ShopBasedCartContext::reset to an interface

### LINKED ISSUE #15021: Missing method on interface for ShopBasedCartContext
**Sylius version affected**: 1.12

**Description**  
The Sylius\Component\Core\Cart\Context\ShopBasedCartContext class has a public method reset invoked by Symfony on kernel.reset tag. The problem is that this method is not added to any interface. It could not be added in CartContextInterface because it will be a BC, but a new interface should be added to inform users that decorate that class of this method.

**Steps to reproduce**  
Decorate the service sylius.context.cart.new_shop_based by implementing the CartContextInterface. 

**Possible Solution**  
Add a new ShopBasedCartContextInterface?

### PR DESCRIPTION
**Pull request by palttamas**
`ShopBasedCartContext` now implements the new `ResettingCartContextInterface`.
    
The service `sylius.context.cart.new_shop_based` is no longer explicitly tagged with the `kernel.reset` tag.
    
Cart contexts that implement the `ResettingCartContextInterface` will be automatically tagged with the `kernel.reset` tag.

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12                   |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                      |
| BC breaks?      | no                                                       |
| Deprecations?   | no  |
| Related tickets | [fixes #15021 ](https://github.com/Sylius/Sylius/issues/15021)                    |
| License         | MIT                                                          |

### CODE REVIEW

File: src/Sylius/Bundle/OrderBundle/DependencyInjection/Compiler/TagCartContextsPass.php [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+
+        foreach ($taggedServices as $id => $tags) {
+            $definition = $container->getDefinition($id);
+
+            if(is_subclass_of($definition->getClass(), ResettingCartContextInterface::class)) {
+                $definition->addTag('kernel.reset', ['method' => 'reset']);
+            }
+        }
+    }
+}
```
Comment (jakubtobiasz) [inline src/Sylius/Bundle/OrderBundle/DependencyInjection/Compiler/TagCartContextsPass.php]: New line is missing here.

File: src/Sylius/Bundle/OrderBundle/DependencyInjection/Compiler/TagCartContextsPass.php [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+        $taggedServices = $container->findTaggedServiceIds(RegisterCartContextsPass::CART_CONTEXT_SERVICE_TAG);
+
+        foreach ($taggedServices as $id => $tags) {
+            $definition = $container->getDefinition($id);
+
+            if(is_subclass_of($definition->getClass(), ResettingCartContextInterface::class)) {
+                $definition->addTag('kernel.reset', ['method' => 'reset']);
+            }
+        }
+    }
```
Comment (jakubtobiasz) [inline src/Sylius/Bundle/OrderBundle/DependencyInjection/Compiler/TagCartContextsPass.php]:
```suggestion
    public function process(ContainerBuilder $container) : void
    {
        $taggedServices = $container->findTaggedServiceIds(RegisterCartContextsPass::CART_CONTEXT_SERVICE_TAG);

        foreach ($taggedServices as $id => $tags) {
            $definition = $container->getDefinition($id);

            if(is_subclass_of($definition->getClass(), ResettingCartContextInterface::class)) {
                $definition->addTag('kernel.reset', ['method' => 'reset']);
            }
        }
    }
```

There's no need for an extra private method.

File: src/Sylius/Bundle/OrderBundle/Tests/DependencyInjection/Compiler/TagCartContextsPassTest.php [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+        $definition = $this->container->findDefinition('acme.cart_context_resetting');
+
+        self::assertThat($definition, self::logicalNot(new DefinitionHasTagConstraint('kernel.reset', ['method' => 'reset'])));
+    }
+
+    protected function registerCompilerPass(ContainerBuilder $container): void
+    {
+        $container->addCompilerPass(new TagCartContextsPass());
+    }
+}
```
Comment (jakubtobiasz) [inline src/Sylius/Bundle/OrderBundle/Tests/DependencyInjection/Compiler/TagCartContextsPassTest.php]: Missing new line

File: src/Sylius/Bundle/OrderBundle/Tests/DependencyInjection/Compiler/TagCartContextsPassTest.php [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+use Sylius\Component\Order\Context\ResettingCartContextInterface;
+use Symfony\Component\DependencyInjection\ContainerBuilder;
+use Symfony\Component\DependencyInjection\Definition;
+
+final class TagCartContextsPassTest extends AbstractCompilerPassTestCase
+{
+
+    /**
+     * @test
+     */
```
Comment (jakubtobiasz) [inline src/Sylius/Bundle/OrderBundle/Tests/DependencyInjection/Compiler/TagCartContextsPassTest.php]:
```suggestion
    /** @test */
```
Small change to keep all tests consistent :). Applies to all test methods.

File: src/Sylius/Component/Core/Cart/Context/ShopBasedCartContextInterface.php [hunk 5]
```diff
@@ -0,0 +1,21 @@
...
+
+namespace Sylius\Component\Core\Cart\Context;
+
+use Sylius\Component\Order\Context\CartContextInterface;
+use Sylius\Component\Order\Context\ResettingCartContextInterface;
+
+interface ShopBasedCartContextInterface extends CartContextInterface, ResettingCartContextInterface
+{
+
+}
```
Comment (jakubtobiasz) [inline src/Sylius/Component/Core/Cart/Context/ShopBasedCartContextInterface.php]: Missing new line

Comment (jakubtobiasz) [inline src/Sylius/Component/Core/Cart/Context/ShopBasedCartContextInterface.php]: We're going to add the `reset` method on the `CartContextInterface` in the `2.0`, so I think we should remove this interface, and just declare `ResettingCartContextInterface` explicitly on `ShopBasedCartContext`.

File: src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php [hunk 6]
```diff
@@ -26,7 +26,7 @@
 use Sylius\Component\Order\Model\OrderInterface as BaseOrderInterface;
 use Webmozart\Assert\Assert;
 
-final class ShopBasedCartContext implements CartContextInterface
+final class ShopBasedCartContext implements ShopBasedCartContextInterface
```
Comment (jakubtobiasz) [inline src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php]:
```suggestion
final class ShopBasedCartContext implements CartContextInterface, ResettingCartContextInterface
```

Explanation below 👇🏼.

File: src/Sylius/Component/Order/Context/ResettingCartContextInterface.php [hunk 7]
```diff
@@ -0,0 +1,18 @@
...
+ */
+
+declare(strict_types=1);
+
+namespace Sylius\Component\Order\Context;
+
+interface ResettingCartContextInterface
+{
+    public function reset(): void;
+}
```
Comment (jakubtobiasz) [inline src/Sylius/Component/Order/Context/ResettingCartContextInterface.php]: Missig new line

File: src/Sylius/Component/Order/Context/ResettingCartContextInterface.php [hunk 8]
```diff
@@ -0,0 +1,18 @@
...
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+declare(strict_types=1);
+
+namespace Sylius\Component\Order\Context;
+
+interface ResettingCartContextInterface
```
Comment (jakubtobiasz) [inline src/Sylius/Component/Order/Context/ResettingCartContextInterface.php]: As I wrote in other comment – in Sylius `2.0` we're going to add the `reset` method directly on the `CartContextInterface`, so let's add a deprecation note here. Just in case :P.

```suggestion
/** @deprecated since 1.13 and will be removed in Sylius 2.0. */
interface ResettingCartContextInterface
```

**Review by jakubtobiasz — CHANGES_REQUESTED** [review]
Hi 👋🏼!
Thanks for your contribution! I left you some comments (mostly cosmetic ones).

File: src/Sylius/Component/Order/Context/ResettingCartContextInterface.php (hunk 8 above)
Comment (palttamas) [reply src/Sylius/Component/Order/Context/ResettingCartContextInterface.php]: If you keep the `ResettingCartContextInterface` in 2.0 and make `CartContextInterface` extend it, then there is no need for the deprecation.

File: src/Sylius/Bundle/OrderBundle/DependencyInjection/Compiler/TagCartContextsPass.php (hunk 2 above)
Comment (palttamas) [reply src/Sylius/Bundle/OrderBundle/DependencyInjection/Compiler/TagCartContextsPass.php]: Then should the class name be `TagCartContextsWithKernelResetPass` ?

File: src/Sylius/Component/Order/Context/ResettingCartContextInterface.php (hunk 8 above)
Comment (jakubtobiasz) [reply src/Sylius/Component/Order/Context/ResettingCartContextInterface.php]: I know we can keep `ResettingCartContextInterface`, but we had many discussions how to handle it. AFAIR our ideal solution was to add this method to the `CartContextInterface`, but we couldn't due to BC policy.

File: src/Sylius/Bundle/OrderBundle/DependencyInjection/Compiler/TagCartContextsPass.php (hunk 2 above)
Comment (jakubtobiasz) [reply src/Sylius/Bundle/OrderBundle/DependencyInjection/Compiler/TagCartContextsPass.php]: That's a good question :D. I looked at our existing Compiler Passes, and there's no schema we could apply here. From what I know, tomorrow more people will review this PR, so let's way for their opinion.

**Comment by palttamas** [comment]
@jakubtobiasz I think I made all the requested changes

File: psalm.xml [hunk 9]
```diff
@@ -59,6 +59,7 @@
                 <referencedClass name="Symfony\Component\Serializer\Normalizer\CacheableSupportsMethodInterface" /> <!-- deprecated in Symfony 6.3 -->
                 <referencedClass name="Symfony\Component\Serializer\Normalizer\ContextAwareDenormalizerInterface" /> <!-- deprecated in Symfony 6.1 -->
                 <referencedClass name="Symfony\Component\Serializer\Normalizer\ContextAwareNormalizerInterface" /> <!-- deprecated in Symfony 6.1 -->
+                <referencedClass name="Sylius\Component\Order\Context\ResettingCartContextInterface" /> <!-- deprecated in Sylius 2.0 -->
```
Comment (NoResponseMate) [inline psalm.xml]:
```suggestion
                <referencedClass name="Sylius\Component\Order\Context\ResettingCartContextInterface" /> <!-- deprecated in Sylius 1.13 -->
```
Although we could just drop the comment like in other internal deprecations.

File: src/Sylius/Bundle/OrderBundle/DependencyInjection/Compiler/TagCartContextsPass.php [hunk 10]
```diff
@@ -0,0 +1,34 @@
...
+
+declare(strict_types=1);
+
+namespace Sylius\Bundle\OrderBundle\DependencyInjection\Compiler;
+
+use Sylius\Component\Order\Context\ResettingCartContextInterface;
+use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
+use Symfony\Component\DependencyInjection\ContainerBuilder;
+
+final class TagCartContextsPass implements CompilerPassInterface
```
Comment (NoResponseMate) [inline src/Sylius/Bundle/OrderBundle/DependencyInjection/Compiler/TagCartContextsPass.php]:
```suggestion
final class ResettingCartContextsPass implements CompilerPassInterface
```
?
At a glance, I'd assume that `TagCartContextsPass` is responsible for tagging services w/ the `sylius.context.cart` tag instead.

File: src/Sylius/Component/Order/Context/ResettingCartContextInterface.php [hunk 11]
```diff
@@ -0,0 +1,19 @@
...
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+declare(strict_types=1);
+
+namespace Sylius\Component\Order\Context;
+
+/** @deprecated since 1.13 and will be removed in Sylius 2.0. */
+interface ResettingCartContextInterface
```
Comment (NoResponseMate) [inline src/Sylius/Component/Order/Context/ResettingCartContextInterface.php]: Couldn't we just use the `Symfony\Contracts\Service\ResetInterface` instead of creating a new, immediately deprecated one?

File: psalm.xml (hunk 9 above)
Comment (palttamas) [reply psalm.xml]: The build doesn't pass, thus i had to add it

File: src/Sylius/Component/Order/Context/ResettingCartContextInterface.php (hunk 11 above)
Comment (palttamas) [reply src/Sylius/Component/Order/Context/ResettingCartContextInterface.php]: I would go as far to extend the ResetInterface, but i honestly don't see the benefit of using `ResetInterface` over a bespoke one.

```

class X {
    public function __construct(
        \Symfony\Contracts\Service\ResetInterface $resetableCartButUpToMeWhatToNameThis,
    )
    {

    }
}
```
vs

```
class X {
    public function __construct(
        Sylius\Component\Order\Context\ResettingCartContextInterface $canGiveThisParamAnyName,
    )
    {

    }
}

```

IMO the second usage expresses a lot more, using a generic interface makes the intent lost. I can't imagine a scenario where you would be applying the same calls to classes that implement `ResetInterface`. I'm curious what was the rationale behind introducing that at Symfony.

Edit: i guess it makes sense to extend the ResetInterface, in case something wants to grab all services that implement that and call reset, could be related to the `kernel.reset` tag?

Comment (palttamas) [reply src/Sylius/Component/Order/Context/ResettingCartContextInterface.php]: Not arguing though, happy to make the change. Leave a thumbs down and I'll proceed with your suggestion

Comment (NoResponseMate) [reply src/Sylius/Component/Order/Context/ResettingCartContextInterface.php]: Putting aside the fact that we're introducing a new interface that is immediately deprecated and presumably won't exist in the next major.
My main issue with creating this new interface is that the intent is the same: this service is stateful and should be reset. That's precisely what the `ResetInterface` is for, there's even [autoconfiguration](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L628) set on the framework extension that auto tags any service with this interface with `kernel.reset`.
IMO the Symfony logic in this case fits to a tee.

File: psalm.xml (hunk 9 above)
Comment (NoResponseMate) [reply psalm.xml]: I meant the comment alone, not the whole line

**Comment by jakubtobiasz** [comment]
I let myself implement @NoResponseMate suggestions as we'd like to merge this PR this week :).

**Review by jakubtobiasz — APPROVED** [review]

**Review by NoResponseMate — APPROVED** [review]

**Review by TheMilek — APPROVED** [review]

**Comment by TheMilek** [comment]
Thank you, Tamas! :tada:

**Comment by palttamas** [comment]
Sorry guys, haven't had time to look at this, thanks for merging :heart:

**Comment by jakubtobiasz** [comment]
Np, we thank you for opening this PR 🫶🏼
