### PR TITLE
[API] Fix ProductVariantNormalizer exception catching

### LINKED ISSUE #13099: [API] ProductVariantNormalizer doesn't handle channel not found exception
**Sylius version affected**: 1.11

**Description**  
In https://github.com/Sylius/Sylius/pull/13035 the call to the channel context was moved outside the try-catch block, so the exception is not caught anymore:
https://github.com/Sylius/Sylius/blob/e602281396c5c17939102169283ba1c1ecb6a324/src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantNormalizer.php#L67-L75

Also, the calculator throws `Sylius\Component\Core\Exception\MissingChannelConfigurationException, so maybe that's the exception that should be caught there.

Right now neither exception is caught.

### PR DESCRIPTION
**Pull request by NoResponseMate**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.11 |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | fixes #13099                      |
| License         | MIT                                                          |

### CODE REVIEW

File: src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductVariantNormalizerSpec.php [hunk 1]
```diff
@@ -153,7 +155,29 @@ function it_returns_catalog_promotions_if_applied(
         ;
     }
 
-    function it_doesnt_return_prices_if_channel_is_not_found(
+    function it_doesnt_resturn_prices_and_promotions_when_channel_is_not_found(
```
Comment (coldic3) [inline src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductVariantNormalizerSpec.php]:
```suggestion
    function it_doesnt_return_prices_and_promotions_when_channel_is_not_found(
```

**Review by coldic3 — APPROVED** [review]

File: src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductVariantNormalizerSpec.php (hunk 1 above)
Comment (NoResponseMate) [reply src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductVariantNormalizerSpec.php]: 🤦

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you, Jan! :tada:
