### PR TITLE
[Shop] Fix disappearing provinces from address forms

### LINKED ISSUE #6651: Bug - Province isn't prepolulated again when error in form data
When you create an address. If you have a mistake in your data (eg you didn't enter first name). When it reloads the form, the province value isn't prefilled with what was previously entered. Every other field is though. 
address-province-bug

### PR DESCRIPTION
**Pull request by NeverResponse**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | fixes #6651 |
| License         | MIT |

### CODE REVIEW

**Comment by NeverResponse** [comment]
I was testing it on address book page and it was working like a charm. Checkout, however, is a different story. Workin on it

File: src/Sylius/Behat/Context/Transform/AddressContext.php [hunk 1]
```diff
@@ -69,12 +81,25 @@ public function createNewAddress($countryName)
...
      * @Transform /^address to "([^"]+)", "([^"]+)", "([^"]+)", "([^"]+)" for "([^"]+)"$/
      */
-    public function createNewAddressWith($cityName, $street, $postcode, $countryName, $customerName, $provinceName = null)
+    public function createNewAddressWith(
+        $cityName,
+        $street,
+        $postcode,
+        $countryName,
+        $customerName,
+        $provinceName = null)
```
Comment (pamil) [inline src/Sylius/Behat/Context/Transform/AddressContext.php]: CS

**Comment by pjedrzejewski** [comment]
Thank you Jasiek.
