### PR TITLE
[ProductAttribute] Fix select product attribute choice value delete

### LINKED ISSUE #8308: Select attribute values get lost on attribute value rename
### Steps to reproduce:
1. create a select attribute with the following configuration: name "Mug material" - values: "Banana skin" and "Prcelan"
2. create a product and assign the attribute "Mug material" with the value "Prcelan"
3. realize you have a typo in the product attribute value: it is "Prcelan" instead of "Porcelain" 
image
4. modify the attribute value from "Prcelan" to "Porcelain"
image
5. observe the product attributes
image

### What happens:
The product attribute value gets lost

### What should happen:
"Prcelan" should be linked to the product through a reference, otherwise, whenever the attribute value gets changed, the products get obsolete references.

Based on the feedback from @pamil on #8220

### PR DESCRIPTION
**Pull request by GSadee**
| Q               | A
| --------------- | -----
| Branch?         | 1.0
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | partially fixes #8308
| License         | MIT

### CODE REVIEW

File: src/Sylius/Behat/Page/Admin/ProductAttribute/UpdatePage.php [hunk 1]
```diff
@@ -62,7 +63,13 @@ public function changeAttributeValue(string $oldValue, string $newValue): void
...
     public function hasAttributeValue(string $value): bool
     {
-        return null !== $this->getElement('attribute_choice_list_element', ['%value%' => $value]);
+        try {
+            $attributeValue = $this->getElement('attribute_choice_list_element', ['%value%' => $value]);
+        } catch (ElementNotFoundException $exception) {
+            return false;
+        }
+
+        return null !== $attributeValue;
```
Comment (Zales0123) [inline src/Sylius/Behat/Page/Admin/ProductAttribute/UpdatePage.php]: I think it's not possible for `getElement(...)` to return `null` value - so we could just type `return true;` here.

File: src/Sylius/Behat/Context/Ui/Admin/ManagingProductAttributesContext.php [hunk 2]
```diff
@@ -273,6 +281,24 @@ function () use ($productAttribute, $oldValue, $newValue) {
     }
 
     /**
+     * @When /^(the administrator) deletes the value "([^"]*)" from (this product attribute)$/
```
Comment (Zales0123) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingProductAttributesContext.php]: `"([^"]*)"` -> `"([^"]+)"` 💃

File: src/Sylius/Bundle/ProductBundle/EventListener/SelectProductAttributeChoiceRemoveListener.php [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+     */
+    public function postUpdate(LifecycleEventArgs $event): void
+    {
+        /** @var ProductAttributeInterface $productAttribute */
+        $productAttribute = $event->getEntity();
+
+        if (
+            $productAttribute instanceof ProductAttributeInterface &&
+            $productAttribute->getType() === SelectAttributeType::TYPE
+        ) {
```
Comment (Zales0123) [inline src/Sylius/Bundle/ProductBundle/EventListener/SelectProductAttributeChoiceRemoveListener.php]: What about the reverse condition and early return?

File: src/Sylius/Behat/Context/Setup/ProductAttributeContext.php [hunk 4]
```diff
@@ -115,13 +116,19 @@ public function theStoreHasAProductAttribute(string $type, string $name): void
 
     /**
      * @Given the store has a select product attribute :name with value :value
+     * @Given the store has a select product attribute :name with values :firstValue and :secondValue
      */
-    public function theStoreHasASelectProductAttributeWithValue(string $name, string $value): void
+    public function theStoreHasASelectProductAttributeWithValue(string $name, ...$values): void
```
Comment (pamil) [inline src/Sylius/Behat/Context/Setup/ProductAttributeContext.php]: `string ...$values` is perfectly fine here

File: src/Sylius/Behat/Context/Setup/ProductAttributeContext.php [hunk 5]
```diff
@@ -140,37 +147,67 @@ public function thisAttributeHasSetMinValueAsAndMaxValueAs(ProductAttributeInter
...
+        string $productAttributeName,
+        string $attributeValue
     ) {
+        $values = [$this->faker->uuid => $attributeValue];
+
+        $this->createSelectProductAttributeValue($product, $productAttributeName, $values);
+    }
+
+    /**
+     * @Given /^(this product) has select attribute "([^"]+)" with values "([^"]+)" and "([^"]+)"$/
```
Comment (pamil) [inline src/Sylius/Behat/Context/Setup/ProductAttributeContext.php]: I guess it can be merged through variadics support with the previous step: 
`@Given /^(this product) has select attribute "([^"]+)" with value "([^"]+)"$/`

File: src/Sylius/Bundle/ProductBundle/EventListener/SelectProductAttributeChoiceRemoveListener.php [hunk 6]
```diff
@@ -0,0 +1,101 @@
...
+     * @param LifecycleEventArgs $event
+     */
+    public function postUpdate(LifecycleEventArgs $event): void
+    {
+        /** @var ProductAttributeInterface $productAttribute */
+        $productAttribute = $event->getEntity();
+
+        if (
+            !($productAttribute instanceof ProductAttributeInterface) ||
+            $productAttribute->getType() !== SelectAttributeType::TYPE
```
Comment (pamil) [inline src/Sylius/Bundle/ProductBundle/EventListener/SelectProductAttributeChoiceRemoveListener.php]: It's my personal preference, but making it a two `if` expressions seems to look cleaner.

File: src/Sylius/Bundle/ProductBundle/EventListener/SelectProductAttributeChoiceRemoveListener.php [hunk 7]
```diff
@@ -0,0 +1,101 @@
...
+        ) {
+            return;
+        }
+
+        $entityManager = $event->getEntityManager();
+
+        $unitOfWork = $entityManager->getUnitOfWork();
+        $changeSet = $unitOfWork->getEntityChangeSet($productAttribute);
+
+        if (
```
Comment (pamil) [inline src/Sylius/Bundle/ProductBundle/EventListener/SelectProductAttributeChoiceRemoveListener.php]: We can skip this `if` by providing `[]` as the default choices if they do not exist (`$changeSet['configuration'][0]['choices'] ?? []` etc., so `$removedChoices` will be empty as well -> `array_diff_key([], []) === []`).

File: src/Sylius/Bundle/ProductBundle/EventListener/SelectProductAttributeChoiceRemoveListener.php [hunk 8]
```diff
@@ -0,0 +1,101 @@
...
+                if (!empty($newValue)) {
+                    $productAttributeValue->setValue($newValue);
+
+                    continue;
+                }
+
+                $entityManager->remove($productAttributeValue);
+            }
+
+            $entityManager->flush();
```
Comment (pamil) [inline src/Sylius/Bundle/ProductBundle/EventListener/SelectProductAttributeChoiceRemoveListener.php]: Do we need it after every removed choice key? Why wouldn't we remove all of these at once?

File: src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php [hunk 9]
```diff
@@ -0,0 +1,33 @@
...
+class ProductAttributeValueRepository extends EntityRepository implements ProductAttributeValueRepositoryInterface
+{
+    /**
+     * {@inheritdoc}
+     */
+    public function findByJsonChoiceKey(string $choiceKey): array
+    {
+        return $this->createQueryBuilder('o')
+            ->andWhere('o.json LIKE :key')
+            ->setParameter('key', '%' . $choiceKey . '%')
```
Comment (pamil) [inline src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php]: I'm wondering if we can add some additional chars to this parameter (like `%"$key"%`)

File: src/Sylius/Bundle/ProductBundle/spec/EventListener/SelectProductAttributeChoiceRemoveListenerSpec.php [hunk 10]
```diff
@@ -0,0 +1,172 @@
...
+use Sylius\Component\Attribute\AttributeType\SelectAttributeType;
+use Sylius\Component\Product\Model\ProductAttributeInterface;
+use Sylius\Component\Product\Model\ProductAttributeValueInterface;
+use Sylius\Component\Product\Repository\ProductAttributeValueRepositoryInterface;
+
+final class SelectProductAttributeChoiceRemoveListenerSpec extends ObjectBehavior
+{
+    function let(): void
+    {
+        $this->beConstructedWith('Sylius\Component\Product\Model\ProductAttributeValue');
```
Comment (pamil) [inline src/Sylius/Bundle/ProductBundle/spec/EventListener/SelectProductAttributeChoiceRemoveListenerSpec.php]: `ProductAttributeValue::class`?

**Comment by pamil** [comment]
Rebase and it's good to go! :)

**Comment by pamil** [comment]
Thanks Rzegś! 🥇
