### PR TITLE
[Admin] Fix user fields disappearing on validation fails

### LINKED ISSUE #6725: [Admin] Manage customer - problem with user fields (v1.0.0-alpha1)
On customer creation, when you fill nothing and you press create button, the password and enable field has disappeared.

I think there is a problem with AddUserFormSubscriber. The form.user is not defined when validation has failed.

capture d ecran 2016-11-15 a 10 16 45

### PR DESCRIPTION
**Pull request by tuka217**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | yes |
| Related tickets | fixes #6725 |
| License         | MIT |

### CODE REVIEW

File: src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php [hunk 1]
```diff
@@ -642,4 +642,45 @@ public function iShouldNotSeeASingleOrderFromCustomer($orderNumber)
...
+    /**
+     * @Given I do not specify any information
+     */
+    public function iDoNotSpecifyAnyInformation()
+    {
+        // Intentionally left blank.
+    }
+
+    /**
+     * @Then I should not be able to specify it password
```
Comment (pamil) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php]: it**s**

File: src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php [hunk 2]
```diff
@@ -642,4 +642,45 @@ public function iShouldNotSeeASingleOrderFromCustomer($orderNumber)
...
+     */
+    public function iShouldNotBeAbleToSpecifyItPassword()
+    {
+        Assert::false(
+            $this->createPage->hasPasswordField(), 
+            'There should not be password field, but it is.'
```
Comment (pamil) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php]: Please, nooooo, no no no, nope nope, this is the most annoying message while debugging :( :( :( 🌮

File: src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php [hunk 3]
```diff
@@ -642,4 +642,45 @@ public function iShouldNotSeeASingleOrderFromCustomer($orderNumber)
...
+    }
+
+    /**
+     * @Then I should still be on the customer creation page
+     */
+    public function iShouldBeOnTheCustomerCreationPage()
+    {
+        Assert::true(
+            $this->createPage->isOpen(),
+            'The customer creation page should be open, but it is not.'
```
Comment (pamil) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php]: Same here.

File: src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php [hunk 4]
```diff
@@ -642,4 +642,45 @@ public function iShouldNotSeeASingleOrderFromCustomer($orderNumber)
...
+    }
+
+    /**
+     * @Then I should be able to select create account option
+     */
+    public function iShouldBeAbleToDeselectCreateAccountOption()
+    {
+        Assert::false(
+            $this->createPage->hasCheckedCreateOption(),
+            'The create account option should not be selected, but it is.'
```
Comment (pamil) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php]: Same here.

File: src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php (hunk 2 above)
Comment (tuka217) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php]: So how looks proper message?

Comment (pamil) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php]: The step does say what behaviour is expected and if it's failing, it says that expected behaviour didn't occur. No message is the best message 🌯  🎉

File: features/user/managing_customers/adding_customer_account_after_failed_creation_action.feature [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+        Given I am logged in as an administrator
+
+    @ui @javascript
+    Scenario: Trying add new customer with an account without required information
+        Given I want to create a new customer account
+        When I choose create account option
+        And I do not specify any information
+        And I try to add it
+        Then I should still be on the customer creation page
+        And I should be able to specify it password
```
Comment (Zales0123) [inline features/user/managing_customers/adding_customer_account_after_failed_creation_action.feature]: ``I should be able to specify its password``

File: features/user/managing_customers/adding_customer_account_after_failed_creation_action.feature [hunk 6]
```diff
@@ -0,0 +1,55 @@
...
+Feature: Adding a new customer account after failed creation action
+    In order to be able to create customer with account even if the creation failed
+    As an Administrator
+    I want to be able to add a customer with an user account after failed creation action
+
+    Background:
+        Given I am logged in as an administrator
+
+    @ui @javascript
+    Scenario: Trying add new customer with an account without required information
```
Comment (Zales0123) [inline features/user/managing_customers/adding_customer_account_after_failed_creation_action.feature]: Shouldn't be ``Trying to add...``?

File: features/user/managing_customers/being_able_to_create_account_for_existing_customer.feature [hunk 7]
```diff
@@ -0,0 +1,29 @@
+@managing_customers
+Feature: Create account option availability
+    In order to correctly administrate customers
+    As an Administrator
+    I want not see create account option if the customer account already exist
```
Comment (Zales0123) [inline features/user/managing_customers/being_able_to_create_account_for_existing_customer.feature]: exist**s**

File: src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php [hunk 8]
```diff
@@ -642,4 +644,94 @@ public function iShouldNotSeeASingleOrderFromCustomer($orderNumber)
...
+    public function iShouldBeAbleToSpecifyItPassword()
+    {
+        Assert::true(
+            $this->createPage->hasPasswordField(),
+            'There should be password field, but it is not.'
+        );
+    }
+
+    /**
+     * @Given /^I should not be able to select create account option$/
```
Comment (Zales0123) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php]: Unneeded ``/^`` and ``$/``

Comment (Zales0123) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php]: and ``@Then``

File: src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php [hunk 9]
```diff
@@ -642,4 +644,94 @@ public function iShouldNotSeeASingleOrderFromCustomer($orderNumber)
...
+    public function iShouldNotBeAbleToSelectCreateAccountOption()
+    {
+        Assert::true(
+            $this->createPage->hasCheckedCreateOption(),
+            'The create account option should be selected, but it is not.'
+        );
+    }
+
+    /**
+     * @Given I do not choose create account option
```
Comment (Zales0123) [inline src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php]: ``@When``

File: src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js [hunk 10]
```diff
@@ -14,7 +14,7 @@
             'containerSelector': '#sylius_calculator_container'
         });
 
-        $('#sylius_customer_create_user').change(function(){
+        $('#sylius_customer_createUser').change(function(){
```
Comment (Zales0123) [inline src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js]: Why changing it?

File: src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/AddUserFormSubscriber.php [hunk 11]
```diff
@@ -54,53 +55,31 @@ public function preSetData(FormEvent $event)
...
         $data = $event->getData();
-        $normData = $event->getForm()->getNormData();
-
-        if (!isset($data['user'])) {
-            $this->removeUserField($event);
+        $form = $event->getForm();
 
-            return;
-        }
+        if(null === $form->get('createUser')->getViewData()) {
```
Comment (Zales0123) [inline src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/AddUserFormSubscriber.php]: Missing space after ``if``.

File: src/Sylius/Bundle/CoreBundle/spec/Form/EventSubscriber/AddUserFormSubscriberSpec.php [hunk 12]
```diff
@@ -0,0 +1,109 @@
...
+        Form $form,
+        Form $createUserCheckForm,
+        UserInterface $user
+    ) {
+        $event->getData()->willReturn($user);
+        $event->getForm()->willReturn($form);
+        $form->get('createUser')->willReturn($createUserCheckForm);
+        $createUserCheckForm->getViewData()->willReturn(null);
+        
+
```
Comment (Zales0123) [inline src/Sylius/Bundle/CoreBundle/spec/Form/EventSubscriber/AddUserFormSubscriberSpec.php]: Double blank line.

File: src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js (hunk 10 above)
Comment (tuka217) [inline src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js]: Because we use camelCase to named field in FormType. So we have sylisus_nameOfEntity_nameOfField. Before this field was in twig template and it has the id "sylius_customer_create_user".

File: src/Sylius/Bundle/ApiBundle/Form/EventSubscriber/AddUserFormSubscriber.php [hunk 13]
```diff
@@ -9,7 +9,7 @@
  * file that was distributed with this source code.
  */
 
-namespace Sylius\Bundle\UserBundle\Form\EventSubscriber;
+namespace Sylius\Bundle\ApiBundle\Form\EventSubscriber;
```
Comment (michalmarcinkowski) [inline src/Sylius/Bundle/ApiBundle/Form/EventSubscriber/AddUserFormSubscriber.php]: Why you moved this to ApiBundle?

Comment (tuka217) [inline src/Sylius/Bundle/ApiBundle/Form/EventSubscriber/AddUserFormSubscriber.php]: Is it truly a part of UserBundle? It not a subscriber which depends on how customer account work, which is a core think? 
Before we use this subscriber for Core CustomerType. After this fix this type has new subscriber, but the old one is still needed in ApiBundle.

File: src/Sylius/Bundle/ApiBundle/Resources/config/routing/customer.yml [hunk 14]
```diff
@@ -19,6 +19,8 @@ sylius_api_customer_show:
         _controller: sylius.controller.customer:showAction
         _sylius:
             serialization_groups: [Detailed]
+            form:
+                type: Sylius\Bundle\ApiBundle\Form\Extension\ApiCustomerType
```
Comment (michalmarcinkowski) [inline src/Sylius/Bundle/ApiBundle/Resources/config/routing/customer.yml]: Please fix it in a separate PR.

**Comment by michalmarcinkowski** [comment]
Great job Ania! 👍
