### PR TITLE
[Addressing] Make sure the CountryNameExtension::translateCountryIsoCode() always returns a string

### LINKED ISSUE #10799: Support case when CountryNameExtension::translateCountryIsoCode() doesn't have translation
**Sylius version affected**: 1.6.1

**Description**  
`Sylius\Bundle\AddressingBundle\Twig\CountryNameExtension::translateCountryIsoCode()` return type hint expects non-null result, while `Intl::getRegionBundle()->getCountryName()` might return null if no translation provided. 
Some of the edge case ISO countries, like reserved names, might not have translation. (UN, TA, XK, EZ, DG, EA, IC, AC)

**Steps to reproduce**  
Add one of countries (UN, TA, XK, EZ, 
DG, EA, IC, AC) to country list and there will be 500 error on country listing at admin UI.

**Possible Solution**  
If no translation found, return raw country code.

image

While I should just drop those countries (It worked at Sylius1.2 and SF3.4, btw), it will be nice to handle this case generally.

### PR DESCRIPTION
**Pull request by vvasiloi**
Fallback to code when there's no translation.
Fallback to empty string when there's no code.

| Q               | A
| --------------- | -----
| Branch?         | 1.5
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #10799
| License         | MIT

### CODE REVIEW

File: src/Sylius/Bundle/AddressingBundle/Twig/CountryNameExtension.php [hunk 1]
```diff
@@ -28,12 +28,20 @@ public function getFilters(): array
         ];
     }
 
+    /**
+     * @param CountryInterface|string $country
+     * @param string|null $locale
+     *
+     * @return string
+     */
```
Comment (Zales0123) [inline src/Sylius/Bundle/AddressingBundle/Twig/CountryNameExtension.php]: Docblock not needed

File: src/Sylius/Bundle/AddressingBundle/Twig/CountryNameExtension.php [hunk 2]
```diff
@@ -28,12 +28,20 @@ public function getFilters(): array
...
-        if ($country instanceof CountryInterface) {
-            return Intl::getRegionBundle()->getCountryName($country->getCode(), $locale);
+        $countryCode = $country instanceof CountryInterface ? $country->getCode() : $country;
+
+        if ($countryName = Intl::getRegionBundle()->getCountryName($countryCode, $locale)) {
+            return $countryName;
         }
 
-        return Intl::getRegionBundle()->getCountryName($country, $locale);
+        return $countryCode ?? '';
```
Comment (Zales0123) [inline src/Sylius/Bundle/AddressingBundle/Twig/CountryNameExtension.php]: I believe it can be done even simpler:

```
if ($country instanceof CountryInterface) {
    return Intl::getRegionBundle()->getCountryName($country->getCode(), $locale) ?? $country->getCode();
}

return Intl::getRegionBundle()->getCountryName($country, $locale) ?? $country;
```

File: src/Sylius/Bundle/AddressingBundle/spec/Twig/CountryNameExtensionSpec.php [hunk 3]
```diff
@@ -39,4 +40,16 @@ function it_translates_country_code_to_name_according_to_locale(): void
     {
         $this->translateCountryIsoCode('IE', 'es')->shouldReturn('Irlanda');
     }
+
+    function it_fallbacks_to_country_code_when_there_is_no_translation(): void
+    {
+        $country = 'country_code_without_translation';
```
Comment (Zales0123) [inline src/Sylius/Bundle/AddressingBundle/spec/Twig/CountryNameExtensionSpec.php]: Variable is not needed

File: src/Sylius/Bundle/AddressingBundle/spec/Twig/CountryNameExtensionSpec.php [hunk 4]
```diff
@@ -39,4 +40,16 @@ function it_translates_country_code_to_name_according_to_locale(): void
...
+        $this->translateCountryIsoCode($country)->shouldReturn($country);
+    }
+
+    function it_fallbacks_to_an_empty_string_when_there_is_no_code(): void
+    {
+        $this->translateCountryIsoCode(new Country())->shouldReturn('');
```
Comment (Zales0123) [inline src/Sylius/Bundle/AddressingBundle/spec/Twig/CountryNameExtensionSpec.php]: This should be a `CountryInterface` mock with `$country->getCode()->willReturn('country_code_without_translation')` result stubbed

File: src/Sylius/Bundle/AddressingBundle/Twig/CountryNameExtension.php (hunk 2 above)
Comment (vvasiloi) [reply src/Sylius/Bundle/AddressingBundle/Twig/CountryNameExtension.php]: This way the `if` block can return `null` (from `$country->getCode()`).
Also, if the `$country` argument is `null`, for example when chaining the filter on a `null` value in the teplate, the returned value will be `null` again.

File: src/Sylius/Bundle/AddressingBundle/spec/Twig/CountryNameExtensionSpec.php (hunk 4 above)
Comment (vvasiloi) [reply src/Sylius/Bundle/AddressingBundle/spec/Twig/CountryNameExtensionSpec.php]: You mean `$country->getCode()->willReturn(null)`?

**Comment by Zales0123** [comment]
Thank you, Victor! :tada:
