### PR TITLE
[Checkout] Prevent extra fields when login in on addressing page

### LINKED ISSUE #15183: [BUG] This form should not contain extra fields. In checkout billing address step
**Sylius version affected**: 1.12.9 (Tested on demo,sylius.com)

**Description**  
A customer starts the checkout billing address step and tries to complete with invalid data.
After submitting the invalid form user tries to login and the form and receives error of: _This form should not contain extra fields_
The extra field in this case is the Customer entity, $email parameter.
The login action submits whole form, it does not reload the page.

**Steps to reproduce**
Buyer did not log in.
Buyer added a product the cart.
Buyer started checkout process.

https://github.com/Sylius/Sylius/assets/45800655/34b2959f-621f-4417-8300-017bd71b1bb5

### PR DESCRIPTION
**Pull request by Jibbarth**
| Q               | A   |
|-----------------|-----|
| Branch?         | 1.12 |
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | no |
| Deprecations?   | no |
| Related tickets | fixes #15183 |
| License         | MIT |

Refs video in #15183

When we login in addressing page after submit once the page, the reload process after login resubmit data, and keep sending `form[customer][email]`, that it doesn't be added in form. 

So I unset these data on pre-submit. 
I also change the csrf_error message for something more "understandable".

By this way, we can still have previous submitted data for address fields.

image

The other way, suggested by @Wojdylak, is to change this line https://github.com/Sylius/Sylius/blob/1.12/src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-api-login.js#L50 
by 
```
window.location = window.location.href;
``` 

But using it, all already filled data are lost.

WDYT ? Would it be acceptable to lose such data, or should we keep them ?

### CODE REVIEW

File: src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php [hunk 1]
```diff
@@ -142,6 +142,17 @@ public function buildForm(FormBuilderInterface $builder, array $options): void
...
+                $orderData = $event->getData();
+
+                if ($options['customer'] instanceof CustomerInterface && array_key_exists('customer', $orderData)) {
+                    // Logged-in user try to submit customer while reloading page after login
+                    unset($orderData['customer']);
+                    $event->getForm()->remove('customer');
+                }
+
                 $event->setData($orderData);
             })
```
Comment (vvasiloi) [inline src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php]: I think the issue here is that the customer field is no longer added by the other listener, so this could be written as:

```suggestion
            ->addEventListener(FormEvents::PRE_SUBMIT, static function (FormEvent $event): void {
                $orderData = $event->getData();
                $form = $event->getForm();

                if (array_key_exists('customer', $orderData) && !$form->has('customer')) {
                    // Logged-in user try to submit customer while reloading page after login
                    unset($orderData['customer']);
                    $event->setData($orderData);
                }
            })
```

**Review by vvasiloi — DISMISSED** [review]
Hey @Jibbarth, thanks for your contribution! I left some feedback. Could you also add a test for it?

File: src/Sylius/Bundle/CoreBundle/Resources/translations/validators.fr.yml [hunk 2]
```diff
@@ -29,6 +29,8 @@ sylius:
             min: Le prix ne peut pas être inférieur à 0.
             not_blank: Veuillez saisir un prix.
     checkout:
+        addressing:
+            csrf_error: Merci de soumettre à nouveau le formulaire complet.
```
Comment (vvasiloi) [inline src/Sylius/Bundle/CoreBundle/Resources/translations/validators.fr.yml]: I think this one has to be done through Localize. 🤔

File: src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php (hunk 1 above)
Comment (Jibbarth) [reply src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php]: Make sense ! Thanks :slightly_smiling_face:

File: src/Sylius/Bundle/CoreBundle/Resources/translations/validators.fr.yml (hunk 2 above)
Comment (Jibbarth) [reply src/Sylius/Bundle/CoreBundle/Resources/translations/validators.fr.yml]: Wasn't aware of the process. Should I remove it ?

**Comment by Jibbarth** [comment]
Thanks for the review @vvasiloi. I will try to make a test :crossed_fingers:

**Review by NoResponseMate — APPROVED** [review]

**Review by jakubtobiasz — APPROVED** [review]

**Comment by jakubtobiasz** [comment]
Thank you, @Jibbarth!
