### PR TITLE
fix `products-by-slug` api docs

### LINKED ISSUE #13999: Missing `slug` parameter in `products-by-slug` Api endpoint docs
**Sylius version affected**: 1.11.4

**Description**  
Missing `slug` parameter in api doc for `/api/v2/shop/products-by-slug/{slug}`

**Steps to reproduce**  
* Go to https://master.demo.sylius.com/api/v2/docs
* Find and Open `/api/v2/shop/products-by-slug/{slug}`

Screenshot 2022-05-17 at 19 48 13

### PR DESCRIPTION
**Pull request by sad270**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.11         |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | fixes #13999                     |
| License         | MIT                                                          |

### CODE REVIEW

File: src/Sylius/Bundle/ApiBundle/Swagger/ProductSlugDocumentationNormalizer.php [hunk 1]
```diff
@@ -38,6 +38,8 @@ public function normalize($object, $format = null, array $context = [])
         foreach ($params as $index => $param) {
             if ($param['name'] === 'code') {
                 unset($docs['paths'][self::PRODUCT_SLUG_PATH]['get']['parameters'][$index]);
+                // reset key index after unset
+                $docs['paths'][self::PRODUCT_SLUG_PATH]['get']['parameters'] = array_values($docs['paths'][self::PRODUCT_SLUG_PATH]['get']['parameters']);
```
Comment (coldic3) [inline src/Sylius/Bundle/ApiBundle/Swagger/ProductSlugDocumentationNormalizer.php:42]: Could you move it out of the loop to line ~45?

Comment (sad270) [reply src/Sylius/Bundle/ApiBundle/Swagger/ProductSlugDocumentationNormalizer.php]: It's done !

**Review by coldic3 — APPROVED** [review]

**Review by Zales0123 — APPROVED** [review]
