### PR TITLE
make product variant comparable

### LINKED ISSUE #11487: Nesting level too deep fatal error when changing variant position
**Sylius version affected**: 1.7.3

**Description**  
When I programmatically change the position of an existing product variant, I get a fatal error "Nesting level too deep - recursive dependency? in vendor/gedmo/doctrine-extensions/lib/Gedmo/Sortable/SortableListener.php on line 471"

**Steps to reproduce**  
(pseudocode)
```
$product = productRepository->findOneBy(['code' => 'some_product']);
$variant = productVariantRepository->findOneBy(['code' => 'some_product_variant']);
$variant->setPosition(2);
$product->addVariant($variant);
productRepository->add($product);
```
The add() and position change actually does work, but the fatal error prevents further action.

**Possible Solution**
This appears similar to a issue recently reported and fixed regarding taxons:
https://github.com/Sylius/Sylius/issues/10797

Perhaps variants should implement Doctrine\Common\Comparable as well?

### PR DESCRIPTION
**Pull request by oallain**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #11487, like as #11329
| License         | MIT

### CODE REVIEW

**Comment by lchrusciel** [comment]
Hey Olivier,

can you rebase to newest 1.7? It may fix the build.

**Comment by oallain** [comment]
Hi @lchrusciel ,

Rebase is done, and "application" is green on Travis, but "doc" still red :disappointed:

**Comment by lchrusciel** [comment]
Our 1.7 branch is red, we will try to fix it in the nearest days

File: src/Sylius/Component/Core/Model/ProductVariant.php [hunk 1]
```diff
@@ -444,4 +445,12 @@ public function removeImage(ProductImageInterface $image): void
             $this->images->removeElement($image);
         }
     }
+
+    /**
+     * @inheritDoc
+     */
+    public function compareTo($other): int
+    {
+        return $this->code === $other->getCode() ? 0 : 1;
```
Comment (dudemelo) [inline src/Sylius/Component/Core/Model/ProductVariant.php:454]: > * This method should not check for identity using ===, only for semantical equality for example
> * when two different DateTime instances point to the exact same Date + **TZ.**
> https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/Comparable.php#L20-L21

I would also like to suggest using another interface because this 0 for :milk_glass:  and 1 for :coffee:  is really tricky.

Comment (lchrusciel) [reply src/Sylius/Component/Core/Model/ProductVariant.php:454]: If I understood correctly, for us it is indeed semantical equality when the codes are identical. Strong cooperation is used here more because of our standards rather than real need (as both codes will be strings)

**Comment by lchrusciel** [comment]
Can you rebase again to 1.7? We could fix it there, I assume.

**Comment by lchrusciel** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "product-variant-comparable"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by lchrusciel** [comment]
Thank you, @oallain! :tada:

File: src/Sylius/Component/Core/spec/Model/ProductVariantSpec.php [hunk 2]
```diff
@@ -273,4 +280,16 @@ function it_returns_images_by_type(ProductImageInterface $image, Product $produc
         $this->addImage($image);
         $this->getImagesByType('thumbnail')->shouldBeLike(new ArrayCollection([$image->getWrappedObject()]));
     }
+
+    function it_is_comparable(): void
+    {
+        $this->setCode('test');
+
+        $otherTaxon = new ProductVariant();
```
Comment (lchrusciel) [inline src/Sylius/Component/Core/spec/Model/ProductVariantSpec.php:288]:
```suggestion
        $otherVariant = new ProductVariant();
```
